- apps/condo/index.js
- apps/condo/jest.config.js
- apps/condo/jest.setup.js
- apps/condo/schema/Billing.test.js
- apps/condo/schema/Organization/AcceptOrRejectOrganizationInviteService.test.js
- apps/condo/schema/Organization/InviteNewOrganizationEmployeeService.test.js
- apps/condo/schema/Organization/Organization.test.js
- apps/condo/schema/Organization/OrganizationEmployee.test.js
- apps/condo/schema/Organization/RegisterNewOrganizationService.test.js
- apps/condo/schema/Property/Property.test.js
- apps/condo/schema/Ticket/Ticket.test.js
- apps/condo/schema/User.test.js
- packages/@core.keystone/test.utils.js
> Refactor tests

- apps/condo/domains/ticket/schema/Ticket.test.js
- packages/@core.keystone/fields/AutoIncrementInteger/Implementation.js
- fix autoincrement field on update
- remove comments from test
> Bug/condo/sberdoma 81/autoincrement fix

- apps/condo/containers/TicketCrudTable.tsx
- apps/condo/containers/TicketForm/UpdateTicketForm.tsx
- apps/condo/domains/common/utils/codegeneration/generate.hooks.ts
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/property/index.tsx
- apps/condo/pages/ticket/index.tsx
- packages/@core.keystone/gen.gql.react.utils.js
Instead of wrighting 
```code js
useEffect(() => {
// ....
}, [objects])
```
Use loading flag
```code js
useEffect(() => {
// ....
}, [loading])
```
> SBERDOMA-51 Remove useMemo from gen.gql.react.utils

- apps/condo/domains/common/constants/locale.js
- apps/condo/domains/common/constants/locale.spec.js
- apps/condo/pages/property/index.tsx
Fix
date-fns - changed format of localization object on it's new version, so format functions start to throw error "RangeError: locale must contain localize property"
> SBERDOMA-112 Fix localization for date-fns format

- apps/condo/domains/common/components/EmptyListView.tsx
- apps/condo/domains/common/components/MapGL.tsx
- apps/condo/domains/common/constants/map.js
- apps/condo/domains/property/gql.js
- apps/condo/domains/property/hooks/useTableColumns.tsx
- apps/condo/domains/property/schema/Property.js
- apps/condo/domains/property/schema/Property.test.js
- apps/condo/domains/property/utils/clientSchema/Property.ts
- apps/condo/domains/property/utils/testSchema/index.js
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/property/index.tsx
- apps/condo/pages/ticket/index.tsx
> SBERDOMA-112 Review fixes

- apps/condo/pages/property/index.tsx
Fix properties display on the map after adding a new property
Fix permission bug - as all properties were displayed earlier on the map without organization restriction
> Feature/condo/sberdoma 300/reload map on property add

- apps/condo/domains/common/components/containers/BaseLayout/AuthLayout.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
- apps/condo/domains/common/constants/style.js
- apps/condo/pages/auth/change-password.tsx
- apps/condo/pages/auth/forgot.tsx
- apps/condo/pages/auth/register.tsx
- apps/condo/pages/auth/signin.tsx
1. Fix chrome autofill in the registration form
2. Fix antd inputs css in formItems only
3. Remove red starts from required fields in auth forms
> SBERDOMA-30 design feedback fices

- apps/condo/domains/common/components/MapGL.tsx
- apps/condo/domains/common/constants/style.js
- apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelView.tsx
- apps/condo/domains/property/components/panels/Builder/UnitButton.tsx
- apps/condo/domains/property/hooks/useTableColumns.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/property/[id]/index.tsx
- apps/condo/pages/property/index.tsx
Fixes
1. Change map size on window resize
2. Add search text highlight
3. Remove border from property name label and remove square info pannel
4. Turned off click animation on the chessboard in view mode
5. Remove link to excel from residents pannel
6. Move the Edit button to the bottom of the page
7. Remove borders from inputs on builders pannel
8. Remove fixed height on the chessboard and fix margins
9. Change scroll container to display x-axis scrollbar
> Fix/condo/sberdoma 52/property mvp after designer review

- apps/condo/domains/organization/utils/helpers.spec.ts
- apps/condo/domains/organization/utils/helpers.ts
- apps/condo/domains/property/utils/helpers.spec.ts
- apps/condo/domains/property/utils/helpers.ts
- apps/condo/domains/ticket/gql.js
- apps/condo/domains/ticket/utils/helpers.spec.ts
- apps/condo/domains/ticket/utils/helpers.ts
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/property/index.tsx
- apps/condo/pages/ticket/index.tsx
1. Page size now can be changed
2. Xls export will export all tickets (limit 100 - because of server-side limit to 1000 requests in total ) sorted and filtered
> Bug/condo/sberdoma 383/tickets list and xls export

- apps/condo/domains/organization/schema/Organization.js
- apps/condo/domains/user/schema/User.js
Change file adapter in avatars before deploy to production (@pahaz  request)
> SBERDOMA-413 Change filestorage for avatars

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Commit `44ccccf8` has changes, that broke implemented feature.
These changes was reverted.
> SBERDOMA-305 reverted changes, that broke field display logic

- apps/condo/domains/common/components/MultipleFileUpload.tsx
- apps/condo/domains/common/utils/fileAdapter.js
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Disable file upload input while file protection in progress
> SBERDOMA-436 disable file input

- apps/condo/domains/user/components/UnitNameInput.tsx
Fix for unit using unit labels instead of ids
> SBERDOMA-436 fix unitname in ticket

- apps/condo/domains/ticket/components/TicketChanges/index.tsx
- apps/condo/pages/ticket/[id]/index.tsx
Fixed blinking when page is loaded
Display `Skeleton` while ticket changes are loading
> Feature/condo/sberdoma 348/UI for ticket changes tracking

- apps/condo/domains/common/components/MultipleFileUpload.tsx
- apps/condo/domains/common/utils/fileAdapter.js
- apps/condo/domains/common/utils/sberCloudFileAdapter.js
- apps/condo/domains/common/utils/sberCloudFileAdapter.spec.js
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/schema/TicketFile.js
- apps/condo/index.js
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- packages/@core.config/index.js
- packages/@core.keystone/schemas/User.js
File protection
To test how it works rename in .env file 
```js
{ "bucket":"doma.ai.public" }
```
to
```js
{ "bucket":"private" }
```
> Feature/condo/sberdoma 436/protect files

- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/utils/helpers.spec.ts
- apps/condo/domains/ticket/utils/helpers.ts
bonus: add highliter to tickets search
> Fix/condo/sberdoma 375/search by status in tickets plus highliter

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Fixed form of ticket creation. (Phone input now filled in container, same height with full name field)
> SBERDOMA-475 Fix phone input styling

- apps/condo/domains/notification/tasks.js
> SBERDOMA-308 sms was trying to go by email transport

- apps/condo/domains/notification/tasks.js
Remove console.log after review
> SBERDOMA-308 remove console log

- apps/condo/domains/common/constants/errors.js
- apps/condo/domains/common/utils/mail.js
- apps/condo/domains/common/utils/mail.spec.js
- apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.js
- apps/condo/domains/organization/schema/OrganizationEmployee.js
- apps/condo/domains/user/schema/User.js
Added mail normalization, covered with tests, improved validations in Schemas.
For additional info visit problem on JIRA: https://doma.atlassian.net/browse/SBERDOMA-437
> Refactor/condo/sberdoma 437/email normalization Added new unified mail normalization 

- apps/condo/domains/common/utils/pdf.ts
- apps/condo/pages/ticket/[id]/pdf.tsx
amount of lines depends on height of current pdf, so it calculates it and then add lines "while it can"
> [WIP] SBERDOMA-87 Added notes line-generation for ticket pdf

- apps/condo/domains/common/components/containers/GlobalStyle.tsx
- apps/condo/pages/property/index.tsx
Add custom styles to the radio group
> SBERDOMA-500 Black and white radio group

- apps/condo/domains/common/components/MultipleFileUpload.tsx
Multiple files can be chosen to upload
> SBERDOMA-499 Multiple file choose for upload

- apps/condo/README.md
- apps/condo/docs/migrations.md
Working with migrations has much of pitfalls, that spread by word across team.
Let's keep all of them in one place.
Outlined points are need to be discussed.
> SBERDOMA-522 documentation draft of migrations guide

- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/contact/components/ContactsEditor/useContactsEditorHook.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Video demo:
→ https://disk.yandex.ru/i/FAkpXpLzNEoSUA
Removed required validation for "phone" and "name" fields of a ticket, being created.
When some of the field is blank, `Contact` will not be created, but ticket will.
ASAP Needs reviews and merge.
> 🔥 SBERDOMA-566 removed required validation for `phone` and `name`, don't create contact if these fields are blank

- apps/condo/domains/organization/access/Organization.js
- apps/condo/domains/organization/access/OrganizationEmployee.js
- apps/condo/domains/organization/schema/Organization.test.js
- apps/condo/domains/organization/schema/OrganizationEmployee.test.js
We had an ability to change the organization even if we were deleted from that organization
Now this is fixed ✨
> SBERDOMA-568 Fix access rights related to the Organization and Organization Employee

- apps/condo/domains/contact/components/ContactsEditor/index.tsx
> SBERDOMA-498 client error

- apps/condo/domains/user/constants/common.js
> SBERDOMA-609 change smsCode to 4 symbols

- bin/create-graphql-schema.js
Sometimes the first step 
```
node ./../../bin/create-graphql-schema.js
```
do not exit properly and the second step 
```
graphql-codegen -c codegen.yaml
```
needs to be started by hands
> SBERDOMA-614 maketypes fix

- apps/condo/domains/organization/hooks/useTableColumns.tsx
- apps/condo/pages/employee/index.tsx
Roles for the table were obtained for all organizations, and not for a specific
> SBERDOMA-554 fix roles filter on organization page

- apps/condo/pages/ticket/[id]/index.tsx
made display section and floor in address on ticket page.
> SBERDOMA-538 display section and floor on ticket page

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/schema/Ticket.js
when sending a details of the ticket, it was necessary to normalize the text in it
> SBERDOMA-580 normalization ticket details

- apps/condo/domains/organization/components/CreateEmployeeForm.tsx
- apps/condo/domains/organization/components/ErrorsContainer.tsx
now we have a message about several required fields in the form for adding an employee
> SBERDOMA-558 display required email on create employee page

- apps/condo/domains/property/components/BasePropertyForm/index.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/index.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
we need to validate the names of the apartments for uniqueness. did it in this pull request
> Feature/condo/sberdoma 415/validate map units

- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/ticket/schema/Ticket.js
- apps/condo/domains/ticket/schema/TicketChange.test.js
Added client-side and server-side validation for phone input in ticket creation.
> SBERDOMA-645 Ticket creation phone input fix

- apps/condo/domains/ticket/hooks/useTableColumns.tsx
Before it was possible to see "null" in ticket overview table in this situations:
1. Unit was not specified
2. When client column was filtered by global search
Now it's fixed 👍
> SBERDOMA-667 Nulls in ticket table

- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/pages/ticket/[id]/index.tsx
- apps/condo/pages/ticket/[id]/pdf.tsx
made display isPaid ticket tag
**on /ticket/id page**
**on /ticket page**
**on /ticket/id/pdf**
> Fix/condo/sberdoma 678/display is paid ticket

- apps/condo/domains/common/components/MultipleFileUpload.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
> SBERDOMA-532 display max size of uploaded file when catch error

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Before it was possible to press keys and see something like "3asdasd" in InputNumber fields, even if it wasn't possible to select it
Now it's impossible to even type something other than numbers 👍 
Also setting min for "Units on floor" to 1, since it seems like property with less units than 1 is incorrect
> [WIP] SBERDOMA-547 Fixed ability to type letter in InputNumber fields

- apps/condo/pages/ticket/[id]/pdf.tsx
> SBERDOMA-679 display floor and section in pdf ticket view

- apps/condo/domains/ticket/hooks/useTableColumns.tsx
Made executor and assigne columns wider. 
**Before:**
**After:**
> SBERDOMA-531 fix executor and assigne columns width on /ticket page

- apps/condo/domains/property/components/BasePropertyForm/index.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
There was no uniformity in clearing form inputs, added allowClear for them
> SBERDOMA-674 add allowClear on property inputs

- apps/condo/domains/organization/components/OrganizationSelect.tsx
> SBERDOMA-693 made the organization and button font smaller

- apps/condo/domains/user/components/UserProfileForm.tsx
> SBERDOMA-536 Wider input fields for profile editing

- apps/condo/domains/common/components/TableFilter.tsx
- apps/condo/domains/common/hooks/useSearch.ts
- apps/condo/domains/contact/hooks/useTableColumns.tsx
- apps/condo/domains/organization/hooks/useTableColumns.tsx
- apps/condo/domains/property/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/pages/contact/index.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/property/index.tsx
- apps/condo/pages/ticket/index.tsx
There was a bug, where you was on nth page of table, started filtering and offset was not set to 0. As a result you were seeing nothing because amount of results decreased by filter.
Current implementation: any filtration resetting offset, and moving you on 1st page of the table 👍 
For more details and cases: visit JIRA problem's page
> SBERDOMA-575 Table filters now resetting offset

- apps/condo/domains/common/utils/createExportFile.js
- apps/condo/domains/ticket/constants/errors.js
- apps/condo/domains/ticket/schema/ExportTicketsService.js
- apps/condo/pages/ticket/index.tsx
SBERDOMA-697
1. Show error when trying to export empty tickets list
2. Add correct mime-type for xlsx
> Bug/condo/sberdoma 466/show notify on empty export

- apps/condo/pages/ticket/[id]/index.tsx
> SBERDOMA-698 fix long name overflowing

- apps/condo/domains/common/components/Comments/CommentForm.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
You can find more details in JIRA task
> SBERDOMA-699 Comments input are now limited by size and by maximum length

- apps/condo/domains/organization/utils/accessSchema.js
- apps/condo/domains/ticket/components/TicketsWidget.tsx
- apps/condo/domains/ticket/schema/TicketReportService.js
- apps/condo/domains/ticket/schema/TicketReportService.test.js
- Error display with antd notification
- Empty icon when data not delivered from api
> SBERDOMA-687 show error in notification & add empty data state

- apps/condo/domains/common/components/Highliter.tsx
- apps/condo/domains/common/constants/regexps.js
- apps/condo/domains/contact/hooks/useTableColumns.tsx
- apps/condo/domains/organization/hooks/useTableColumns.tsx
- apps/condo/domains/organization/utils/helpers.spec.ts
- apps/condo/domains/organization/utils/helpers.ts
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
global search highlighting added to contact table and employee table.
Bonuses: Can filter employee by position now + instead of empty cell displaying "—" now
> SBERDOMA-677 Highlighting global search

- apps/condo/domains/common/components/StatsCard.tsx
while the button does not work, we need to display tooltip
> SBERDOMA-709 add not implemented tooltip on details button

- apps/condo/domains/organization/components/OrganizationSelect.tsx
1. When the user switch organization - there will be no more redirect to the home page
2. When the user lost his cookies with information about the chosen organization (another browser or when logged from another account in the same browser) - select will be opened
> SBERDOMA-314 fix select to auto open if organization link is lost

- apps/condo/domains/common/components/Comments/Comment.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
> SBERDOMA-624 Display update date of comment on mouse over

- apps/condo/pages/auth/register.tsx
1) caught a server error
2) when there are more characters in the entered code than expected (4), then an error is displayed
> SBERDOMA-692 catch sms error

- apps/condo/domains/common/components/Comments/CommentForm.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
> SBERDOMA-733 remove long placeholder, add comment size counter

- apps/condo/domains/user/components/containers/AuthLayout.tsx
> SBERDOMA-715 add transparent background to header

- apps/condo/domains/organization/utils/accessSchema.js
- apps/condo/domains/ticket/schema/TicketReportService.test.js
Fix access rights check of user for the case when there are several records of his invitations @pahaz
> SBERDOMA-774 fix organization employee access rights check

- apps/condo/domains/organization/components/EmployeeProfileForm/index.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
Before was displaying "Editing my profile" on employee update page.
Now just "Editing profile"
> SBERDOMA-773 Translation fix

- apps/condo/docs/checklists/pull-request.md
> SBERDOMA-823 Add svgo to pr checklist

- apps/condo/domains/user/access/SigninResidentUserService.js
- apps/condo/domains/user/gql.js
- apps/condo/domains/user/schema/SigninResidentUserService.test.js
Fixing error with access from mobile phone to register resident
> SBERDOMA-649 Fix access for SigninResident and rename gql mutation

- apps/condo/domains/common/components/BaseSearchInput/index.tsx
> SBERDOMA-627 unbind search input value

- apps/condo/domains/common/components/TicketCard/TicketCard.tsx
- apps/condo/domains/common/components/TicketCard/TicketOverview.tsx
- apps/condo/domains/contact/components/EditContactForm.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/contact/[id]/index.tsx
- apps/condo/pages/contact/[id]/update.tsx
Page for contact editing created...
⚠️ **Please notice**: It's based on changes from this PR: https://github.com/open-condo-software/condo/pull/316
So, I'll do rebase, when it will be in master, for now creating this PR with this "tail" so that you can view it and test it by yourself
Some previews:
> SBERDOMA-759 Added page for contact editing

- apps/condo/pages/ticket/[id]/index.tsx
This field does't have corresponding input in ticket form
> SBERDOMA-711 removed orphaned 'email' field in ticket page

- apps/condo/domains/common/components/Comments/CommentForm.tsx
- apps/condo/domains/common/components/InputWithCounter.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- Add InputWithCounter component
- Use it in ticket details and ticket comment forms
> SBERDOMA-639 details max size

- apps/condo/lang/ru.json
Fixed incorrect email error translation on register screen 😄
> SBERDOMA-714 Translation fix

- apps/condo/domains/user/utils/serverSchema/guards.js
- packages/@core.keystone/setup.utils.js
> Revert "SBERDOMA-831 handle redis connection error"

- apps/condo/domains/common/components/TicketCard/TicketOverview.tsx
> SBERDOMA-841 Added width style to ticket container

- apps/condo/domains/common/components/HeaderActions.tsx
- apps/condo/pages/auth/change-password.tsx
- apps/condo/pages/auth/forgot.tsx
- apps/condo/pages/auth/register.tsx
- apps/condo/pages/auth/signin.tsx
- apps/condo/pages/contact/[id]/index.tsx
- apps/condo/pages/contact/create.tsx
- apps/condo/pages/contact/index.tsx
- apps/condo/pages/employee/[id]/index.tsx
- apps/condo/pages/employee/[id]/update.tsx
- apps/condo/pages/employee/create.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/index.tsx
- apps/condo/pages/property/[id]/index.tsx
- apps/condo/pages/property/[id]/update.tsx
- apps/condo/pages/property/create.tsx
- apps/condo/pages/property/index.tsx
- apps/condo/pages/ticket/[id]/index.tsx
- apps/condo/pages/ticket/[id]/update.tsx
- apps/condo/pages/ticket/create.tsx
- apps/condo/pages/ticket/index.tsx
- apps/condo/pages/user/index.tsx
- apps/condo/pages/user/update.tsx
Removed all duplicated header actions to common reusable components 👍
> SBERDOMA-798 Common header actions

- apps/condo/domains/common/components/containers/GlobalStyle.tsx
Hide table filter, show it on hover and when in has active state
> SBERDOMA-860 table filter

- apps/condo/domains/common/components/StatsCard.tsx
- apps/condo/domains/ticket/components/TicketsWidget.tsx
- apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
- apps/condo/pages/analytics/index.tsx
- fix organization filtering
- specification first load empty state
- add tooltip for ticketwidget
> SBERDOMA-891 fix organization filtering, first load issue

- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/ticket/[id]/index.tsx
> SBERDOMA-845 new layout of Ticket page

- apps/condo/domains/common/components/BaseSearchInput/index.tsx
> Revert "SBERDOMA-627 unbind search input value"

- apps/condo/pages/ticket/[id]/index.tsx
It's strange, how it was duplicated.
Maybe after somebody's rebase…
Nevermind…
> SBERDOMA-898 fixed duplication of ticket changes block in ticket page

- apps/condo/domains/common/components/GraphQlSearchInput.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/analytics/index.tsx
> SBERDOMA-912 - add ability to select multiple property addresses

- apps/condo/domains/common/components/Prompt.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
Prompt do not work on files change and contact change as they are using custom hooks and for files - no changes are happening on form at all
> Feature/condo/sberdoma 863/prevent user from leaving ticket edit page

- apps/condo/domains/ticket/components/TicketChart.ts
- apps/condo/domains/ticket/utils/helpers.spec.ts
- apps/condo/domains/ticket/utils/helpers.ts
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/analytics/index.tsx
- apps/condo/pages/analytics/pdf.tsx
Now you can select all ticket types
> SBERDOMA-935 add default filter option

- apps/condo/domains/common/components/Comments/CommentForm.tsx
- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/contact/components/CreateContactForm.tsx
- apps/condo/domains/contact/components/EditContactForm.tsx
- apps/condo/domains/organization/components/CreateEmployeeForm.tsx
- apps/condo/domains/organization/hooks/useCreateOrganizationModalForm.tsx
- apps/condo/domains/property/components/BasePropertyForm/index.tsx
- apps/condo/domains/user/components/UserProfileForm.tsx
- apps/condo/pages/auth/change-password.tsx
- apps/condo/pages/auth/forgot.tsx
- apps/condo/pages/auth/register.tsx
- apps/condo/pages/auth/signin.tsx
Moved common form validations in useValidations hook...
I'll add specific confluence page later 👍
> SBERDOMA-905 Common validations for frontend forms

- packages/@core.keystone/test.utils.js
- we can't display errors in real client mode at the moment
> SBERDOMA-900 debug real client mode

- apps/condo/domains/common/components/StatsCard.tsx
- apps/condo/domains/ticket/components/TicketsWidget.tsx
- apps/condo/domains/ticket/schema/TicketReportService.js
- apps/condo/domains/ticket/schema/TicketReportService.test.js
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/schema.d.ts
> SBERDOMA-932 add year period select to StatsCard component

- apps/condo/domains/ticket/schema/CreateResidentTicketService.js
- apps/condo/domains/ticket/schema/UpdateResidentTicketService.js
- apps/condo/domains/ticket/utils/testSchema/index.js
?. not working on node less then 14, remove this from backend code
> SBERDOMA-955 remove optional chainig

- apps/condo/domains/common/components/StatsCard.tsx
- apps/condo/domains/ticket/components/TicketsWidget.tsx
- apps/condo/domains/ticket/schema/TicketReportService.js
- apps/condo/domains/ticket/schema/TicketReportService.test.js
> SBERDOMA-956 unlock redirect to analytics page from ticket widget

- apps/condo/domains/billing/components/Settings/IntegrationPanel.tsx
- apps/condo/pages/settings/integration/[id]/index.tsx
Fixed: 
1. Missing translation in confirm modal
2. Card view when title is short
Before:
After:
> SBERDOMA-720 Fixed missing by rebasing translation + card view fix

- bin/generate-tickets.js
```bash
yarn workspace @app/condo generate-tickets
```
Creates 3 real property
Generates tickets 
Not creates an organization so you need at least 1 organization before running this script
> SBERDOMA-818 Ticket generator

- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/auth/register.tsx
> SBERDOMA-751 Information about lock time remain

- apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
- apps/condo/domains/ticket/schema/TicketClassifierRule.js
- apps/condo/schema.d.ts
When a category or place classifiers are reset - the problem classifier will also be reset
Fix bug with problem classifier some times do not show on the edit page
> SBERDOMA-980 Three level classifier fixes

- apps/condo/domains/common/utils/testSchema/factories.js
- apps/condo/package.json
- bin/generate-receipts.js
We are unable to generate fake billing receipts in a large quantity. This would be useful for mobile devs and web devs
* Add the service to generate billingreceipts in a large quantity
Usage: `yarn generate-receipts <context-id>`
Example: `yarn generate-receipts ae32e512-b791-4e3f-b5c5-4bcd18a94f22`
> SBERDOMA-974 Billing Receipts Generator

- apps/condo/domains/ticket/schema/GetAllResidentTicketsService.js
- apps/condo/schema.d.ts
Added unitName in ResidentTicketWhereInput as requested by Mikhail Chepelev
> SBERDOMA-975 add unitName in ResidentTicketWhereInput

- apps/condo/domains/common/components/ActionBar.tsx
- apps/condo/domains/common/components/RadioGroupWithIcon.tsx
- apps/condo/pages/analytics/detail/report_by_tickets/index.tsx
- apps/condo/pages/analytics/detail/report_by_tickets/pdf.tsx
> Fix/condo/sberdoma 981/UI layout fixes

- apps/condo/domains/billing/schema/BillingAccount.js
- apps/condo/domains/billing/schema/BillingReceipt.js
- apps/condo/domains/common/utils/makeid.utils.js
- apps/condo/domains/common/utils/userid.utils.js
- apps/condo/domains/common/utils/validation.utils.js
- apps/condo/domains/organization/schema/OrganizationEmployee.js
- apps/condo/domains/property/schema/Property.js
- apps/condo/domains/ticket/schema/Ticket.js
- apps/condo/index.js
This fixes validation error in admin UI when trying to change OrganizationEmployee entity because of lack of fields 'dv', 'sender' in request.
> SBERDOMA-962 Extends fields validations from cookies.

- apps/condo/domains/organization/access/Organization.js
- apps/condo/domains/property/access/Property.js
Add check to exclude empty ids from id_in query
full documentation on API - https://www.getpostman.com/collections/c6cb098c2dd6156d7a62
> SBERDOMA-996 mobile api fix

- apps/condo/migrations/20210817111732-0043_auto_20210817_1117.js
This PR fixes unapplied migration `20210817111732-0043_auto_20210817_1117.js`, that faced following case:
We can have hard-deleted rows in OrganizationEmployee table and orphaned rows in OrganizationEmployeeHistoryRecord,
that was correspond to them before hard-delete. Therefore after [1] a table OrganizationEmployeeHistoryRecord
can have NULL in "history_id" column in some rows. Since we don't have original rows in OrganizationEmployee
table, we can set them to some value, — `00000000-0000-0000-0000-000000000000`.
> Fix/condo/sberdoma 963/migrate orgemployee pk to UUID

- apps/condo/pages/_app.tsx
> SBERDOMA-1041 - fix menu path in analytics

- apps/condo/domains/property/schema/Property.js
- apps/condo/domains/property/schema/Property.test.js
now there will be no error if we add a property with an address that is in another organization
> SBERDOMA-1020 fix same property error

- apps/condo/domains/ticket/components/analytics/TicketChartView.tsx
- apps/condo/domains/ticket/components/analytics/TicketListView.tsx
At the suggestion of @Dimitreee now all load state will be looks like this
> SBERDOMA-1040 - replace local components loaders with antd skeleton 

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
> SBERDOMA-910 add autoSize to details TextArea

- apps/notification_bot/.env.example
- apps/notification_bot/botController.ts
- apps/notification_bot/index.ts
- apps/notification_bot/package.json
- apps/notification_bot/utils.ts
- yarn.lock
Our bot did not give us the end release-result. You would need to manually open all links and search for tasks. 
- jira integration
> SBERDOMA 1063 Jira <3 Bot

- apps/condo/domains/user/constants/common.js
- apps/condo/domains/user/schema/AuthenticateUserWithPhoneAndPasswordService.js
Remove using email from auth by phone
> SBERDOMA-1084 Remove using of email from auth by phone

- apps/condo/domains/common/utils/locale.js
- apps/condo/domains/ticket/components/ShareTicketModal.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/share.tsx
- packages/@core.next/intl.jsx
> SBERDOMA-914 fix translates for share page and add setting locale via query param

- apps/condo/domains/common/components/ActionBar.tsx
- apps/condo/domains/common/components/GraphQlSearchInput.tsx
- apps/condo/domains/ticket/components/ShareTicketModal.tsx
> SBERDOMA-889 fix suggest 

- .env.example
Feature flags workflow is not formalized
Create confluence page && fix `.env.example`
> SBERDOMA-1115 update .env.example flags

- apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
- apps/condo/domains/ticket/utils/serverSchema/analytics.helper.js
- apps/condo/schema.d.ts
Now we can't load huge data with existing getAll util
Use raw db query with knex adapter
> SBERDOMA-1128 property range limit

- apps/condo/domains/common/constants/requisites.js
Final change phone number our company on login page
> change phone number

- apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
- apps/condo/domains/ticket/utils/serverSchema/dayGroupDataMapper.js
- apps/condo/domains/ticket/utils/serverSchema/propertySummaryDataMapper.js
> SBERDOMA-1128 - analytics xlsx generation fix

- apps/condo/domains/notification/adapters/smsAdapter.js
- apps/condo/domains/notification/adapters/smsAdapter.spec.js
Changed phone number validation for smsc.ru adapter. 
It was CIS-only. Now - all countries
> SBERDOMA-1147 change phone validation for smsc

- apps/condo/domains/common/components/ActionBar.tsx
- apps/condo/domains/property/components/PropertyForm/UpdatePropertyForm.tsx
fullscreen option to true by default
> Fix/condo/sberdoma 1150/action bar css fix

- apps/condo/package.json
- bin/fix-chessboards.js
Script to fix maps and unitCounts field
> SBERDOMA-1124 Fix properties maps and counts

- apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/domains/property/constants/property.ts
1. To reproduce the bug - Start to add a section, don't press the Add Section button, change the name of preview section, press Save property button
2. Added tests
> DOMA-1125 Fix bug with not editable map in properties

- apps/condo/domains/common/components/TicketCard/TicketOverview.tsx
- apps/condo/domains/notification/templates.js
- apps/condo/domains/ticket/utils/helpers.ts
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/share.tsx
Fixed date-displaying in ticket sharing, added "ago" title on ticket change message, fixed unproper translations
> DOMA-1180 Fix date displaying 

- .husky/commit-msg
- apps/condo/docs/quick-start.md
- commitlint.config.js
- package.json
- yarn.lock
When committing, a pre-commit hook `commit-msg` gets applied with Husky.
Following commits are handled as valid:
1. With prefix `DOMA-123` in message
2. With prefix `HOTFIX` in message
When a commit contains meaningful message, like "pr fixes", "review fixes", "fixed bugs", it will be reported as invalid and committing will be impossible.
To get this features, please, install Husky commit hooks locally:
`yarn prepare `
To play with validation, add following script into root `package.json`:
```
"validate-commit-message": "commitlint"
```
And launch it:
```
echo "SBERDOMA-123 lorem ipsum" | yarn validate-commit-message
```
> Feature/condo/sberdoma 1168/validation of commit message

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/domains/property/hooks/useTableColumns.tsx
Fix "import + create" buttons alignment
Fix property table columns widths
Before/after
> DOMA-1206 Fix "/property" layout

- apps/condo/domains/user/components/UserPasswordResetButton.tsx
> DOMA-1229 Fix profile form reset password link

- apps/condo/domains/user/utils/testSchema/index.js
> DOMA-1230 Changed phone generation for our tests

- apps/condo/pages/reports/detail/report-by-tickets/index.tsx
- apps/condo/pages/reports/detail/report-by-tickets/pdf.tsx
Need to add `analytics_property` to environment config
> DOMA-1231 wrap analytics property page with feature flag

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/domains/property/schema/ExportPropertiesToExcelService.js
Remove deleted properties from excel export
> DOMA-1189 remove deleted properties from export

- apps/condo/pages/_app.tsx
Please, read this article to get more details: https://doma.atlassian.net/browse/DOMA-1246
I've also described working with typed JSON-fields here: https://doma.atlassian.net/wiki/spaces/SBER/pages/819363841/JSON-
> DOMA-1246 Changing BillingReceipt services caching behaviour

- apps/condo/domains/common/components/GraphQlSearchInput.tsx
- apps/condo/domains/common/components/Table/Filters.tsx
- apps/condo/domains/common/components/TableFilter.tsx
- apps/condo/domains/common/components/containers/FormList.tsx
- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/domains/common/utils/filters.utils.spec.ts
- apps/condo/domains/common/utils/filters.utils.ts
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
Description of filters using filterMeta + modal window with filters
[how to use](https://doma.atlassian.net/wiki/spaces/SBER/pages/820117521)
> DOMA-1224 multiple filters modal

- apps/condo/pages/_app.tsx
- apps/condo/pages/settings/index.tsx
Feature-flags were not correctly setup, so...added separate feature-flags for settings and for it sub-sections.
Also made sub-sections work with SSR
> DOMA-1280 Fix settings feature-flags

- apps/condo/domains/division/components/DivisionsTable.tsx
- apps/condo/domains/property/components/BuildingsTable.tsx
searching in the property and divisions page did not reset the query offset
> DOMA-1267 use useSearch hook for reset offset in search input

- apps/condo/domains/common/components/ActionBar.tsx
- apps/condo/domains/common/components/Comments/index.tsx
- apps/condo/domains/common/components/PageFieldRow.tsx
- apps/condo/domains/common/components/containers/BaseLayout/BaseLayout.tsx
- apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/SideMenu.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/TopMenuItems.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
- apps/condo/domains/common/utils/codegeneration/generate.hooks.ts
- apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
- apps/condo/domains/ticket/components/TicketStatusSelect.tsx
- apps/condo/pages/_document.tsx
- apps/condo/pages/ticket/[id]/index.tsx
> Feature/condo/doma 919/add ticket index mobile screens

- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
set offset 0 when submit or reset filters
> DOMA-1285 reset offset in filters modal

- .gitmodules
https://documenter.getpostman.com/view/16928965/UUxzB835
> DOMA-1316 add eps submodule

- .gitmodules
> Doma-1316 Eps submodule fix

- werf.yaml
Reworked https pull to git pull.
> INFRA changed callcenter build

- packages/@core.keystone/tasks.js
> DOMA-1291 add createCronTask and removeCronTask

- apps/condo/domains/common/components/Comments/index.tsx
- apps/condo/pages/ticket/[id]/index.tsx
> Fix/condo/doma 1343/ticket card disign fixes

- apps/condo/pages/_app.tsx
- apps/condo/pages/billing/index.tsx
- apps/condo/pages/settings/index.tsx
> DOMA-1250 remove billing feature flag

- apps/condo/pages/_app.tsx
- apps/condo/pages/billing/index.tsx
- apps/condo/pages/settings/index.tsx
- apps/condo/pages/settings/integration/[id]/index.tsx
Fix 404 error in settings/integration/id
> HOTFIX DOMA-1250 Fix 404 error in settings/integration/id

- apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
- apps/condo/domains/organization/components/EmployeeForm/UpdateEmployeeForm.tsx
> HOTFIX make specialization non-required and add role info card to employee update page

- apps/condo/domains/meter/components/MeterCard.tsx
- apps/condo/domains/meter/components/createMeterModal/MeterInfo.tsx
- apps/condo/domains/meter/hooks/useCreateMeterModal.tsx
- apps/condo/domains/meter/hooks/useFilters.tsx
- apps/condo/domains/meter/hooks/useTableColumns.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- Add the date of the control readings to the meter creation modal
- Do date inputs validation
- Make a onBlur trigger on input readings
> DOMA-1344 Meter front fixes

- apps/condo/domains/billing/schema/fields/BillingReceipt/Recipient.js
- apps/condo/domains/billing/utils/testSchema/index.js
- apps/condo/domains/common/schema/fields.js
- apps/condo/schema.ts
There are a screen on mobile which requires recipient name, but we return only INN (ru)
Add new field
> DOMA 1331 - add recipient.name field

- apps/condo/domains/billing/components/ServicesModal.tsx
- apps/condo/domains/billing/gql.js
- apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
- apps/condo/domains/billing/utils/clientSchema/BillingAccount.ts
We need to display `unitName` for our user
- Add an ability to display `unitName` in table 
- Add an ability to display `unitName` in receipts modal
> DOMA 1392 upgrade billing tables

- apps/condo/pages/ticket/[id]/index.tsx
> HOTFIX Show ticket action bar in mobile view

- packages/@core.keystone/schema.js
- packages/@core.keystone/schema.spec.js
How to use it:
`index.js`
```
...
function customPreprocessor () {
return ((schemaType, name, schema) => {
console.log(schemaType, name)
if (schemaType !== 'GQLListSchema') return schema
// Set plugins for all Lists!
return {
...schema,
plugins: [uuided(), versioned(), tracked(), softDeleted(), historical()],
}
})
}
...
registerSchemas(
keystone, 
[
require('@condo/domains/user/schema'),
...,
], [
customPreprocessor(),
],
)
...
```
> Global keystone preprocessors

- apps/condo/domains/common/components/Table/Renders.tsx
- apps/condo/domains/common/components/helpers/tableCellRenderer.tsx
- apps/condo/domains/organization/gql.js
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/components/ShareTicketModal.tsx
- apps/condo/pages/division/[id]/index.tsx
- apps/condo/pages/property/[id]/index.tsx
- Remove action bars from proeprty and Division pages if the user does not have a role
- Get origin for share ticket only from the SERVER_URL
These changes are needed for contactcenter
> DOMA-1404 check role in action bars and SERVER_URL origin in ticket sharing

- packages/@core.keystone/fields/AutoIncrementInteger/Implementation.js
- packages/@core.keystone/fields/AutoIncrementInteger/index.js
- packages/@core.keystone/fields/Json/Implementation.js
- packages/@core.keystone/fields/Json/index.js
- packages/@core.keystone/fields/LocalizedText/index.js
- packages/@core.keystone/fields/Options/Implementation.js
- packages/@core.keystone/fields/Options/index.js
- packages/@core.keystone/fields/Stars/Implementation.js
- packages/@core.keystone/fields/Stars/index.js
> DOMA-1435 add prisma adapter support for fields

- apps/condo/package.json
- add pino support
- fix some HTTP express bugs
> HOTFIX update dd-trace lib to the latest version

- .env.example
- apps/condo/domains/common/utils/fileAdapter.js
- apps/condo/domains/common/utils/sberCloudFileAdapter.js
- apps/condo/index.js
- bin/lint-schema.js
You need to add `FILE_FIELD_ADAPTER=local` to your `.env` file
> DOMA-1569 extract fileAdapter config

- apps/condo/domains/organization/integrations/sbbol/SbbolFintechApi.js
- apps/condo/domains/organization/integrations/sbbol/SbbolRequestApi.js
- apps/condo/domains/organization/integrations/sbbol/common.js
- apps/condo/domains/organization/integrations/sbbol/oauth2.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncPaymentRequestsForSubscriptions.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncSbbolSubscriptionPaymentRequestsState.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncSubscriptions.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncSubscriptions.spec.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncUser.spec.js
Replaced `console.log` to Pino JSON logger, used in Keystone
Used namespace `sbbol/subscriptions` namespace for Fintech API interaction.
> Feature/condo/doma 1501/replace debug message func to pino logger

- apps/condo/domains/common/components/GraphQlSearchInput.tsx
- apps/condo/domains/division/components/BaseDivisionForm/index.tsx
- apps/condo/domains/ticket/utils/clientSchema/search.ts
Bug description
1. GET_ALL_PROPERTIES_BY_VALUE_QUERY - returns only 10 records
2. When GraphQlSearchInput initialized no requests were made to load chosen properties
Before fixing:
After fixing:
> DOMA-1462 Bug when properties do not load in edit form

- apps/condo/domains/organization/integrations/sbbol/SbbolFintechApi.js
- apps/condo/domains/organization/integrations/sbbol/SbbolRequestApi.js
- apps/condo/domains/organization/integrations/sbbol/accessToken.js
- apps/condo/domains/organization/integrations/sbbol/constants.js
- apps/condo/domains/organization/integrations/sbbol/oauth2.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncPaymentRequestsForSubscriptions.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncSbbolSubscriptionPaymentRequestsState.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncSubscriptions.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncSubscriptions.spec.js
- bin/sbbol.js
Depends on #769, which was not merged until infrastructure works will be finished, so, first 16 commits are to skip in review.
Splitted `SBBOL_CONFIG` into `SBBOL_AUTH_CONFIG` and `SBBOL_FINTECH_CONFIG`.
Extracted initialization of `SbbolFintechApi` and removed duplicated code.
> Feature/condo/doma 1500/split sbbol env config

- apps/condo/domains/resident/constants.js
- apps/condo/domains/resident/gql.js
- apps/condo/domains/resident/schema/Resident.js
- apps/condo/domains/resident/schema/Resident.test.js
Payment categories are not ready for i18n
Add ID field to paymentCategories
> DOMA-1353 Add ID to paymentCategories

- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/domains/common/utils/string.utils.js
- apps/condo/domains/organization/hooks/useCreateOrganizationModalForm.tsx
- apps/condo/domains/organization/schema/Organization.js
- apps/condo/domains/organization/utils/tin.utils.js
- apps/condo/domains/organization/utils/tin.utils.spec.js
* spaces are not a problem anymore
* refactoring
* fixed/added tests
* updated string utils
> DOMA-1587 fixed tin validation

- apps/condo/domains/organization/integrations/sbbol/SbbolCryptoApi.js
- apps/condo/package.json
- bin/sbbol/crypto.js
This is a step 1 form 10 in preparation of Electronic Digital Certificate.
> DOMA-1593 script to obtain crypto information

- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/domains/common/hooks/useSearch.ts
- apps/condo/domains/common/utils/filters.utils.ts
- apps/condo/domains/ticket/hooks/useEmergencySearch.ts
- apps/condo/domains/ticket/hooks/usePaidSearch.ts
- apps/condo/pages/contact/index.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/ticket/index.tsx
- rename `setFiltersToQuery` to `updateQuery`
- added to function arguments `sort` and `offset`
- pass them on the `emplyee` and `contact` pages
> DOMA-1609 fix sort and pagination on employee and contact pages

- apps/condo/domains/common/utils/fileAdapter.js
- apps/condo/index.js
If we build condo in the current optimized mode then admin UI will not be accessible
Temporary remove the flag and add todo
> DOMA-1614 restore admin ui

- apps/condo/domains/acquiring/constants/errors.js
- apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
- apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
After last changes `billingAccount` of `ServiceConsumer` is not required anymore. So...we need to write few additional checks for it in our mobile-app mutations
> DOMA-1606 Additional billingAccount checks

- .gitmodules
We need a separate application to work with accounting bank acquiring
> DOMA-1489 Accounting bank submodule

- Dockerfile
Reverts open-condo-software/condo#771
> Revert "DOMA-831 remove useless runtime variables!"

- apps/condo/domains/billing/hooks/useServicesTableColumns.tsx
- add ... to the volume if the volume is ronuded
> DOMA-1480 Billing services table quirks 

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
> DOMA-1649 handle error when user not selected property address 

- apps/condo/domains/common/components/Table/Renders.tsx
- apps/condo/domains/division/hooks/useTableColumns.tsx
- apps/condo/domains/division/utils/clientSchema/Renders.tsx
> DOMA-1679 render empty string when no city part in render adress

- apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
1. Remove bank name and corresponding account from saving receipt
2. Change random number generator in faker from deprecated
> DOMA-1661 Fix saving receipts

- apps/condo/domains/common/components/TopNotifications.tsx
- apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/TopMenuItems.tsx
**Problem**: Organization invites is not showing in mobile version of CRM
**MVP** Show them like in desktop, but adapted styles a bit
**HOW IT LOOKS NOW**:
<details>
</details>
> DOMA-1498 Added invites to mobile version

- apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
1. Moved Residents load from server to client
2. Add creation of resident in the web interface for tests
3. Change RegisterServiceConsumerService to work with an account number - not with resident's unitName
4. Add Pino logger to receiptApi
5. Add DaDaTa fetch info about address from eps on the server side to set FIAS id of a BillingProperty and unitName
> DOMA-1661 Fix billing property save

- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/domains/property/components/BasePropertyForm/index.tsx
**Problem**: Numbers with commas pass validations but was not processed on submit
**Solution**: Add submit cleaning
**TODO (in future)**: move to Globalize for number-parsing
> DOMA-1724 Property areas with comma

- bin/fix-tickets-contacts.js
**Problem**: I was thinking, that "broken" ticket was missing only clientName and clientPhone fields, but client was specified. Now info got clarified: we got them from Mobile App, and there're missing fields: client, clientName, clientPhone
**Solution**: Fill this fields, but based on createdBy instead of client, since tickets were created from mobile app
> DOMA-1709 Expanded fix-ticket after support details

- packages/@core.next/organization.jsx
**Problem**: 
**Solution**: do not throw this error and let system do the rest :)))))
> DOMA-376 Removed error throwing on cookie resetting

- apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
> DOMA-1661 Restore Service Consumer logic

- apps/condo/domains/acquiring/schema/MultiPayment.js
1. Fix pino logs display
2. Add receipts page
3. Add service consumer page
> DOMA-1661 Fix EPS logs add pages

- apps/condo/domains/ticket/components/BaseTicketForm/ErrorsContainer.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx
- apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
- apps/condo/domains/ticket/constants/common.js
Made disabled create/update `ticket` button when required fields not filled
> DOMA-626 disable create/update ticket button

- apps/condo/pages/_app.tsx
- apps/condo/pages/_document.tsx
https://nextjs.org/docs/messages/no-document-viewport-meta
> DOMA-1735 fix head meta tag warning

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
> DOMA-1731 move map container when interacting with the last section

- apps/condo/domains/common/components/Comments/index.tsx
- apps/condo/domains/common/components/Poster.tsx
- apps/condo/domains/common/components/Text.tsx
- apps/condo/domains/common/components/TicketCard/TicketCardList.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
- apps/condo/domains/onboarding/components/OnBoardingStepItem/components.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/Fullscreen.tsx
- apps/condo/domains/ticket/components/TicketStatusSelect.tsx
- apps/condo/domains/user/components/containers/styles.tsx
- apps/condo/pages/settings/integration/[id]/index.tsx
> HOTFIX revert commit which brokes "/ticket" page

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
reset unitName select on clear property select
> DOMA-1678 set null property on clear property select

- apps/condo/domains/resident/constants.js
Add payment check
update payment categories
switch eps stand (try 2)
> DOMA-1746 EPS Terminal change

- apps/condo/domains/user/components/UserMenu/MobileUserMenu.tsx
- apps/condo/domains/user/components/UserMenu/styles.ts
> DOMA-1356 mobile menu redesign

- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/pages/ticket/index.tsx
previously filters were saved in localStorage only if you click the confirm button in the modal window
> DOMA-1732 save table filters

- apps/condo/domains/meter/schema/MeterReading.test.js
- apps/condo/domains/organization/access/Organization.js
- apps/condo/domains/resident/gql.js
- apps/condo/domains/resident/schema/ServiceConsumer.test.js
Optimizes performance for Organization access
> DOMA-1793 - performance

- apps/condo/domains/billing/schema/BillingReceipt.test.js
- apps/condo/domains/billing/schema/fields/BillingReceipt/Recipient.js
- apps/condo/domains/resident/schema/RegisterServiceConsumerService.js
- apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
- apps/condo/domains/resident/schema/ServiceConsumer.js
Adds an ability to set paymentCategory to the ServiceConsumer under registerServiceConsumer mutation
Add a bunch of new fields to billingReceipt model: 
1. Bank Name
2. OffsettingAccount (Корр Счет) in RU
3. TerritoryCode (OKTMO) in RU
> DOMA-1792 Fields and Categories

- apps/condo/domains/meter/schema/MeterReading.test.js
- apps/condo/domains/organization/access/Organization.js
- apps/condo/domains/resident/gql.js
- apps/condo/domains/resident/schema/ServiceConsumer.test.js
Add the ability to get not own organizations but in more performant way
> DOMA-1792 Fix performance of the organization fetch function

- .github/workflows/deploy_cleanup.yml
> INFRA fix cleanup job

- apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
> DOMA-1814 update section & unit number when section has been removed

- apps/condo/pages/settings/integration/[id]/index.tsx
> DOMA-1859 fix markup on the billing page

- apps/condo/domains/meter/hooks/useImporterFunction.ts
- apps/condo/domains/property/utils/clientSchema/search.ts
- apps/condo/domains/ticket/utils/clientSchema/search.ts
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
Added validation of the `unitName` specified in the row in excel table
> DOMA-1852 unitName import meter readings validation

- apps/condo/schema.ts
To make acquiring to work with eps
Attempt 2 to put bicrypt to eps
> DOMA-1864 wrap json params

- apps/condo/domains/common/components/DeleteButtonWithConfirmModal.tsx
- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalAccountNumberField.tsx
- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalDatePicker.tsx
- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalFormItem.tsx
- apps/condo/domains/meter/hooks/useUpdateMeterModal.tsx
- apps/condo/lang/ru.json
1) changed styles button delete
2) removed indents from form.item labels
3) changed the color of the form.item labels
4) when deleting a meter asked if the user is sure that he wants to delete the meter
> DOMA-1884 design review fixes

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
(This happens because now there is a limit at `useObjects` hook)
Bonus: this also will reduce the load on the server and database
> DOMA-1885 fix property data search when objects count more than 100 units

- apps/condo/domains/resident/constants.js
Add new payment category 
Add new transformations for new EPS stand
> DOMA-1864 Add new payment category, add new EPS stand

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/pages/contact/index.tsx
> DOMA-1770 added spase after import button on contact and property pages

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelView.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
> DOMA-1934 editable section name

- apps/condo/domains/user/schema/ForgotPasswordService.js
- apps/condo/domains/user/schema/ForgotPasswordService.test.js
> DOMA-1750 [Backend] Temporary auth flow remake 

- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
Sorting by custom field led to different results in 
```js
const beforePaymentResult = await ResidentBillingReceipt.getAll(residentClient, { serviceConsumer: { resident: { id: resident.id } } },
{
sortBy: ['toPay_ASC'],
},
)
```
> DOMA-2003 Fix billing TEST

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
> DOMA-2001 fix section button overflow

- apps/condo/domains/ticket/schema/ExportTicketsService.js
- apps/condo/domains/ticket/utils/serverSchema/index.js
1. There is no easy way to add DISTINCT to ARRAY_AGG with ORDER BY
2. So, we add id to SELECT (as content can be duplicated in different comments) and then make unique list on creating excel
> DOMA-1567 Fix duplicate ticket comments

- apps/condo/domains/user/components/UserMenu/DesktopUserMenu.tsx
In condo username shows with three dots ("User..."). We need to show it without dots ("User")
Update format function
> DOMA-625 Remove dots from username

- apps/condo/bin/sbbol/crypto.js
- apps/condo/domains/organization/integrations/sbbol/SbbolCryptoApi.js
- apps/condo/domains/organization/integrations/sbbol/utils/buildBicryptId.js
- apps/condo/domains/organization/integrations/sbbol/utils/buildBicryptId.spec.js
Following steps are implemented:
1. Get Crypto-information
2. Build `bicryptId`
3. Post Certificate Signing Request (CSR)
4. Get state of CSR
5. Get print version of CSR
6. Activate certificate API call
Refactored naming of scripts in `bin` and corresponding commends in `package.json`
> Feature/condo/doma 1593/get digital signature certificate from sbbol

- apps/condo/domains/common/components/containers/FormList.tsx
- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/domains/ticket/hooks/useFiltersTooltipData.ts
- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
- apps/condo/pages/ticket/index.tsx
If some of the applied filters are not in the filters in the table, but are in the modal (in the control room, for example, the `author`, `source`, `division` ...), hen when you hover over the table row, the tooltip should be displayed
> DOMA-1605 filter tooltip

- apps/condo/domains/acquiring/gql.js
- apps/condo/domains/resident/constants.js
- apps/condo/schema.ts
Fix schema to return directPaymentUrl
Add Overhaul payment category
> DOMA-2162 Fix schema add Overhaul payment category

- apps/condo/domains/contact/schema/Contact.js
- apps/condo/domains/contact/schema/Contact.test.js
**Problem**: Cannot create same contact, if it was deleted in organization
**Solution**: Fix bad-written validation logic
> [BUG 🐞] DOMA-2176 Fixed contact deletedAt scenarios

- apps/condo/domains/common/components/Import/Index.tsx
- apps/condo/domains/common/hooks/useImporter.ts
- apps/condo/domains/common/utils/importer.ts
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/meter/index.tsx
Made the display of mutation validation errors when importing `meter readings`
> DOMA-2078 import mutation errors

- apps/condo/domains/common/components/MultipleFileUpload.tsx
- apps/condo/domains/common/components/PageFieldRow.tsx
- apps/condo/domains/common/components/containers/GlobalStyle.tsx
- apps/condo/domains/property/components/UnitInfo.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/ErrorsContainer.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx
- apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
- apps/condo/domains/ticket/components/TicketStatusSelect.tsx
- apps/condo/domains/ticket/constants/common.js
- apps/condo/domains/ticket/utils/helpers.ts
- apps/condo/domains/user/components/UnitNameInput.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
- apps/condo/pages/ticket/[id]/index.tsx
- apps/condo/pages/ticket/index.tsx
Fixed markup bugs related to `DOMA-1564 ticket deadline` task
> DOMA-1564 fixes after testing

- packages/@core.keystone/setup.utils.js
**NOTE: multiplying by 1000, since keystone uses milliseconds**
> [INFRA 🌎] DOMA-2233 Expand session-cookie lifetime

- apps/condo/bin/generate-contacts.js
- apps/condo/domains/contact/components/ContactsEditor/index.tsx
**Problem**: Cannot sync contacts on create ticket page, if unitName is not specified (since some orgs have > 1.000 contacts per house.....and then GQL throws Error)
**Solution**: Limit result by 1000, then refetching contacts on input changes
> [Refactor 👨‍💻] DOMA-1874 Refactored contacts search mechanism in ticket creation

- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalAccountNumberField.tsx
- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
- apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
- apps/condo/domains/meter/hooks/useCreateMeterModal.tsx
- apps/condo/domains/meter/hooks/useMeterValidations.ts
- apps/condo/domains/meter/hooks/useUpdateMeterModal.tsx
- apps/condo/lang/en.json
- apps/condo/lang/ru.json
added meter account number client validation on create and update meter forms
> DOMA-2235 added meter account number client validation

- apps/condo/domains/common/components/TicketCard/TicketCardList.tsx
- apps/condo/domains/ticket/hooks/useCacheUtils.tsx
- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
- apps/condo/pages/contact/[id]/index.tsx
Filter contact tickets by `contact id` instead of name
> DOMA-1568 fixed contact ticket filters

- apps/condo/domains/ticket/components/TicketStatusSelect.tsx
- apps/condo/domains/ticket/constants/style.js
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/schema/TicketAnalyticsReportService.js
In the mobile application, there is no background for ticket statuses and the primary color of the status is used for the text, so it is not visible
Swapped primary and secondary status colors
> DOMA-2309 swapped primary and secondary colors

- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/contact/components/ContactsEditor/useContactsEditorHook.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
change useContactsEditorHook canCreateContact field value from ref to state
> DOMA-2291 fix contact creation at ticket create page

- apps/condo/domains/acquiring/schema/MultiPayment.js
amount = amountWithoutExplicitFee + explicitFee + explicitServiceCharge
> DOMA-2346 fix multiPayment amount calculation

- apps/condo/bin/generate-tickets.js
We need to generate tickets for specified organization to test performance of `exportTicketsToExcel` custom query
> DOMA-2243 add argument `organizationId` to `bin/generate-tickets.js`

- apps/condo/domains/ticket/schema/Ticket.js
- apps/condo/domains/ticket/schema/Ticket.test.js
Problem:
When ticket creates with contact data, but without client data, it is a bit strange and can broke something
Solution:
Fill empty client data with data from contact (if sended)
> Fix/condo/doma 2284/fill client fields with contact data

- apps/condo/domains/onboarding/components/WelcomePopup.tsx
The onboarding modal was displayed incorrectly in the safari browser, fixed it
> DOMA-2390 fixed incorrect display onboarding modal in safari

- apps/condo/pages/settings/acquiring/[id]/index.tsx
- apps/condo/pages/settings/index.tsx
Removes feature flag for `acquirnig`, rendering `acquirnig` as available feature for all users
> DOMA-2312 Remove feature flag from acquiring integration

- apps/condo/bin/README.md
- apps/condo/bin/sbbol/credentials.js
- apps/condo/bin/test-sbbol-oauth-by-hands.js
- apps/condo/domains/organization/integrations/sbbol/oauth2.js
- apps/condo/domains/organization/integrations/sbbol/routes.js
- apps/condo/domains/organization/integrations/sbbol/utils/getOrganizationAccessToken.js
- apps/condo/domains/organization/integrations/sbbol/utils/index.js
- packages/@core.keystone/test.utils.js
How-to test it:
Take PROD envs: `SBBOL_PFX`,`SBBOL_AUTH_CONFIG`,`SBBOL_FINTECH_CONFIG`.
1) check the AUTH by: `yarn workspace @app/condo node ./bin/test-sbbol-oauth-by-hands.js`
2) check the CHANGE TOKEN by: `yarn workspace @app/condo node ./bin/sbbol/credentials.js change-client-secret`
> HOTFIX SBBOL PROD

- apps/condo/domains/billing/schema/BillingReceipt.js
> DOMA-2433 Fix receiver find on receipt create

- apps/condo/domains/common/components/ExportToExcelActionBar.tsx
Button disappears because of the action bar and re-render
> DOMA-2200 Export to excel button disappears fixed

- apps/condo/domains/common/constants/errors.js
- apps/condo/domains/contact/components/ContactsEditor/useContactsEditorHook.tsx
- apps/condo/domains/contact/schema/Contact.js
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/constants.js
> Doma-2350 error message for creating Contact on Ticket form

- apps/condo/domains/common/utils/tables.utils.ts
- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
- apps/condo/domains/ticket/utils/helpers.ts
1. added search tickets by date
2. fixed search by number that breaks graphql request on floating point numbers
> Doma-1823 search tickets by date

- apps/condo/domains/notification/templates.js
excess letters after the phrase 'Application... was shared with you'.
> DOMA-1706. Excess symbols ")}" in mail of despetcherskaya

- apps/condo/domains/acquiring/utils/serverSchema/feeDistribution.js
1. Add receipts, payments generators
2. Fix fee distribution schema
3. Add retries on fetching order info from securepay
4. Change production envs for Atol and rb integration
5. Downgrade Atol API integration to v4 from v5
> DOMA-1235 Update RB 

- apps/condo/domains/meter/gql.js
- apps/condo/domains/meter/schema/ExportMeterReadingsService.js
- apps/condo/domains/meter/schema/ExportMeterReadingsService.test.js
- apps/condo/domains/meter/utils/testSchema/index.js
The reason was in missing `dv` and `sender` fields in `ExportMeterReadingsInput`
> DOMA-2522 error 400 by exporting meter

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
> DOMA-1802 section deep copy

- apps/condo/domains/common/components/icons/ArrowSemiBold.tsx
- apps/condo/domains/onboarding/components/OnBoardingStepItem/components.tsx
- apps/condo/domains/onboarding/components/OnBoardingStepItem/index.tsx
> DOMA-1958 fix onboarding arrow

- apps/condo/domains/common/components/Focus/FocusElement.tsx
- fix toltip which appeared after the second step of onboarding
> DOMA-1965 fix onboarding tooltip

- apps/condo/pages/reports/detail/report-by-tickets/index.tsx
fix issue with ticketType used prev value triggered from TicketAnalyticsPageFilter component
> DOMA-2439 `ticketType` cache issue

- .env.example
- apps/condo/domains/common/components/InputWithCounter.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/useTicketValidations.tsx
> Bug/condo/doma 2337/fix problem not rq field

- apps/condo/domains/acquiring/gql.js
- apps/condo/domains/acquiring/hooks/usePaymentsTableFilters.ts
- apps/condo/domains/acquiring/utils/clientSchema/PaymentsFilterTemplate.ts
- apps/condo/schema.ts
This PR fixes the following bugs:
> DOMA-2546 fix filter templates behavior

- apps/condo/domains/common/utils/logger.js
Flant is having problems working with colors in logs :(
> DOMA-2599 remove beautiful colors from logger

- apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Localized placeholder was added
> DOMA-2603 Date picker at reports page

- apps/condo/domains/common/components/Comments/CommentForm.tsx
Fixes bad InputWIthCounter markup:
> HOTFIX Fix bad counter markup

- apps/condo/domains/common/utils/addressApi.ts
> DOMA-2646 Expanded address suggestions amount

- apps/condo/domains/common/hooks/useSearch.ts
state = null -> fromQuery != null -> state != null
> DOMA-1972 Removed return from query which was causing cyclic value update

- apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
Fix case when autoclassifier stops to work on clearing category and place
> DOMA-2629 fix auto classifier after QA tests

- .gitmodules
- packages/@core.codegen/templates/app00/babel.config.js
- packages/@core.codegen/templates/app00/next.config.js
- packages/@core.codegen/templates/app00/package.json
- packages/@core.codegen/templates/app00/pages/_app.jsx
During developing of "insurance" mini-app (DOMA-2523), a core app template has improved.
> Changes in @core.codegen app template

- .github/workflows/remove_review.yaml
Add github actions for auto remove review namespace
> INFRA Add github actions for auto remove review

- .github/workflows/deploy_development.yaml
- .github/workflows/deploy_production.yaml
- .github/workflows/deploy_review.yaml
https://run.flant.com/issues/345180
https://flant.slack.com/archives/C027RC3K4H5/p1647961409712299
Add env WERF_BRANCH_NAME to deployments
> INFRA Add branch name to annotations

- .gitmodules
> DOMA-2797 insurance mini-app as condo submodule

- apps/condo/domains/organization/integrations/sbbol/common.js
- apps/condo/domains/organization/integrations/sbbol/sync/index.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
SBBOL user can be without email. In this case, Ajv validation is blocking the sign in
> DOMA-2453 remove required email from sbbol user

- apps/condo/domains/property/components/panels/Builder/BuildingEditTopMenu.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> DOMA-1523 property map add floor

- apps/condo/domains/user/components/auth/RegisterContextProvider.tsx
- apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
https://doma.atlassian.net/browse/DOMA-2726
> DOMA-2726 disappearing of number on register layout

- apps/condo/domains/organization/integrations/sbbol/utils/getOrganizationAccessToken.js
To support multiple employees from our organization
> DOMA-2813 fix getClientSecret 

- apps/condo/domains/user/oidc/configuration.js
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/next.config.js
- apps/condo/pages/insurance/index.tsx
- apps/miniapp/index.js
- apps/miniapp/pages/index.jsx
- packages/@core.codegen/templates/app00/next.config.js
- yarn.lock
Based on Miniapp example PR #1289.
Only latest commit is to be reviewed.
"insurance" mini-app is in [condo_insurance_app / PR #1](https://github.com/open-condo-software/condo_insurance_app/pull/1)
> Feature/condo/doma 2523/embed insurance miniapp

- apps/condo/domains/common/components/LayoutContext.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/meter/index.tsx
- apps/condo/pages/ticket/index.tsx
> DOMA-2503 Fix tables scrolling in low descktop resolution

- apps/condo/domains/common/utils/serverSchema/changeTrackable.js
- apps/condo/domains/contact/components/ContactsEditor/ContactSyncedAutocompleteFields.tsx
- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/contact/components/ContactsEditor/useContactsEditorHook.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/schema/Ticket.js
- apps/condo/domains/ticket/utils/clientSchema/Ticket.ts
Added tab "not from resident" to ContactsEditor
> DOMA-2565 ticket not from resident

- apps/condo/domains/ticket/schema/Ticket.js
> HOTFIX remove console log

- apps/condo/domains/common/components/HeaderActions.tsx
- apps/condo/domains/common/constants/style.js
- apps/condo/domains/user/components/auth/RegisterForm.tsx
- apps/condo/domains/user/components/containers/styles.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/pages/auth/change-password.tsx
https://doma.atlassian.net/browse/DOMA-2786
https://doma.atlassian.net/browse/DOMA-2791
https://doma.atlassian.net/browse/DOMA-2785
> DOMA-2785, DOMA-2791, DOMA-2786 fix required field flag, input align, error text

- apps/condo/lang/ru/ru.json
> DOMA-2831 russian spelling fix

- apps/condo/domains/ticket/schema/Ticket.test.js
- apps/condo/domains/ticket/utils/handlers.js
Push notifications should be sent if next status change:
> 1. null -> OPEN
> 2. COMPLITED -> OPEN
Otherwise never if new status OPEN
> DOMA-2434 fix extra push cases

- apps/condo/domains/common/components/IFrame/IFrameWrapper.tsx
- package.json
- yarn.lock
Main part is here: https://github.com/open-condo-software/condo-registry-import-billing/pull/2
> [DOMA-2758] Registry schema stich, and IFrameWrapper patch

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/ticket/index.tsx
Added clear button to search inputs in employee, ticket and property.
> DOMA-2054 Fixed clear button in search input on all pages

- .gitmodules
Reverts open-condo-software/condo#1521
> Revert "DOMA-2910 remove `apps/amocrm` service"

- apps/condo/pages/ticket/[id]/index.tsx
Fix link route for assignee on ticket view page
> DOMA-2695 fix assignee link

- apps/condo/pages/ticket/[id]/pdf.tsx
add assignee and executor phone to ticket pdf view
> Doma-2864 print phones on ticket pdf

- apps/condo/domains/common/utils/fileAdapter.js
Add directory check and create for local file adapter on build stage
> DOMA-2976 fix build

- apps/condo/domains/common/utils/tables.utils.ts
> DOMA-2852 Add trim to string filters

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/pages/contact/index.tsx
- apps/condo/pages/meter/index.tsx
Remove EmptyListView display on loading stage
> DOMA-2867 fix empty list view shown on loading stage

- apps/condo/admin-ui/index.js
- apps/condo/index.js
Register all schema in build phase (if not - they will not appear in admin ui)
> DOMA-2987 fix admin ui on build phaze

- apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
> DOMA-2503 Fix classifier shortening

- apps/condo/domains/common/utils/serverSchema/index.js
Fixes a bug when deleted contacts continue to export to excel
> DOMA-2989 remove deleted objects from exports with GqlWithKnexLoadList

- apps/condo/pages/ticket/[id]/pdf.tsx
preview page didn't wait for executor and assignee to load before creating pdf file
> DOMA-2864 Add assignee and executor phone to pdf file

- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
https://user-images.githubusercontent.com/25844927/169030726-10a594ce-1a05-437b-b102-1a3cfc619c26.mp4
> DOMA-3029 add unitType to ContactEditor search expression

- apps/condo/lang/ru/ru.json
> DOMA-2799 Fix button title

- apps/condo/domains/ticket/schema/Ticket.test.js
- apps/condo/domains/ticket/utils/handlers.js
- Push notifications will not be sent to resident on ticket status change/ticket comments on hidden tickets
- Test added for that
> DOMA-3062 fixed sending push notifications to resident on hidden tickets fixed, test added

- apps/condo/domains/ticket/schema/Ticket.test.js
- apps/condo/domains/ticket/schema/TicketComment.test.js
- apps/condo/domains/ticket/utils/handlers.js
- fixed condition
- added test on this case
> DOMA-3087 stop sending push on comment editing

- apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
- apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
> DOMA-2988 add unitName column to `ReceiptsTable`

- apps/condo/domains/common/components/JIRAServiceDeskWidget.tsx
- apps/condo/next.config.js
- apps/condo/pages/_app.tsx
Added a widget to submit an incident to Jira. Located at the bottom right of all pages.
> DOMA-2155 Added JIRA Service Desk Widget

- apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
> DOMA-3138 fixed ticket number overlapping by indicator on small screens

- apps/condo/domains/billing/gql.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
- apps/condo/schema.ts
Add `isPayable` field, which indicates if this billing receipt is `latest`
> DOMA-2479 -- Add isPayable field to AllResidentBillingReceipts

- apps/condo/jest.setup.js
- packages/@core.keystone/tasks.js
- packages/@core.keystone/tasks.spec.js
```
!OLD VERSION (TESTS_FAKE_WORKER_MODE = true)
Test Suites: 1 failed, 14 passed, 15 total
Tests:       1 failed, 2 skipped, 200 passed, 203 total
Snapshots:   0 total
Time:        289.204 s
!NEW VERSION (TESTS_FAKE_WORKER_MODE = true)
Test Suites: 15 passed, 15 total
Tests:       2 skipped, 201 passed, 203 total
Snapshots:   0 total
Time:        233.364 s
!REAL WORKER (TESTS_FAKE_WORKER_MODE = false)
Test Suites: 15 passed, 15 total
Tests:       2 skipped, 201 passed, 203 total
Snapshots:   0 total
Time:        215.413 s
```
> Speed up TESTS_FAKE_WORKER_MODE = true

- apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx
> DOMA-2113 fix element layout

- apps/condo/index.js
- packages/@core.keystone/cache.js
This PR debugs and fixes why `X-Request-ID not working!`
> HOTFIX debug why x-request-cache was not working!

- apps/condo/domains/common/constants/requisites.js
- apps/condo/domains/notification/schema/SendMessageService.js
- apps/condo/domains/notification/transports/email.js
- apps/condo/domains/user/schema/SendMessageToSupportService.js
- apps/condo/schema.ts
> DOMA-3259 use `emailFrom` field as value for `Reply-To` header

- apps/condo/domains/common/components/EmptyListView.tsx
Extend types for EmptyListView
> DOMA-1651 fix empty list view

- werf.yaml
1. Remove schema creation on build phase
2. Force add schema to registry app
> DOMA-1651 fix registry app build

- apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> DOMA-3237 property map user control unit renaming

- apps/condo/domains/common/utils/serverSchema/changeTrackable.js
- apps/condo/domains/common/utils/serverSchema/changeTrackable.test.js
- apps/condo/domains/ticket/schema/TicketChange.js
Keep "common" domain apart of other domains
> DOMA-3265 moved domain-specific localized keys map out from changeTrackable module

- apps/condo/domains/common/utils/GraphQLLoggerApp.js
- apps/condo/domains/common/utils/apolloErrorFormatter.js
- apps/condo/domains/common/utils/apolloErrorFormatter.spec.js
- apps/condo/index.js
Move all logging logic in GraphQLLoggerPlugin!
Remove useless toGraphQLFormat!
> DOMA-3365 remove GraphQLLoggerApp and init GraphQLLoggerPlugin

- apps/condo/pages/ticket/[id]/index.tsx
> DOMA-3163  fix downloading files in ticket view

- apps/condo/domains/common/components/containers/FormList.tsx
- apps/condo/domains/common/utils/mutations.utils.js
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> DOMA-3121 new notification when ticket is created

- apps/condo/domains/acquiring/schema/Payment.js
- apps/condo/schema.ts
Add description for payment order and rebuild schema
> DOMA-3282 add description for payment order

- apps/condo/pages/ticket/[id]/index.tsx
This reverts commit 32b0ec56e90abf69fb8090e6d628644aa51aaa99.
> DOMA-3163 fixed opening files in ticket view

- apps/condo/domains/common/utils/codegeneration/generate.server.utils.js
- apps/condo/domains/user/oidc/adapter/OidcModelClientAdapter.js
- apps/condo/domains/user/oidc/createOidcClient.js
- apps/condo/domains/user/schema/OidcClient.js
- apps/condo/domains/user/schema/OidcClient.test.js
- apps/condo/schema.ts
A number of fixes after code review of https://github.com/open-condo-software/condo/pull/1835
> Fix/condo/doma 3188/OIDC clients code review fix

- apps/condo/domains/common/components/IFrame/IFrame.tsx
- apps/condo/domains/common/utils/codegeneration/generate.hooks.ts
- apps/condo/domains/common/utils/url.utils.js
- apps/condo/domains/common/utils/url.utils.spec.js
- apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
- apps/condo/domains/miniapp/components/GlobalApps/GlobalIframe.tsx
- apps/condo/pages/_app.tsx
- packages/@core.next/_useEmitterMutation.ts
- packages/@core.next/apollo.jsx
- packages/@core.next/package.json
- packages/@core.next/useEmitterMutation.ts
- yarn.lock
> [DOMA-3527] 🦖🦖 Global apps front-end 🦖🦖

- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
Correcting input props and pointer on callcenter
> DOMA-3222 input props edited

- apps/condo/domains/common/components/IFrame/IFrame.tsx
- apps/condo/domains/common/utils/iframe.utils.spec.ts
- apps/condo/domains/common/utils/iframe.utils.ts
- apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
- apps/condo/domains/miniapp/components/GlobalApps/GlobalIframe.tsx
- apps/condo/domains/miniapp/components/IFrameModal.tsx
- apps/miniapp/lang/en.json
- apps/miniapp/lang/ru.json
- apps/miniapp/pages/demo/frames/global.tsx
- apps/miniapp/pages/demo/frames/modal.tsx
Added global IFrames for global B2BApps.
Possibilities:
- Scan for user-launched actions
- Open web-pages inside modal
- Send notifications
> [DOMA-3526] 🖼️🖼️🖼️  More Iframes?) 🖼️🖼️🖼️

- apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js
- apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.spec.js
Updated messageType detection logic, now it works as following:
1. toPay <= 0 - { messageType: BILLING_RECEIPT_ADDED_WITH_NO_DEBT_TYPE, debt: 0 }
2. toPay > 0 && toPayDetails.charge > 0 - { messageType: BILLING_RECEIPT_ADDED_WITH_DEBT_TYPE, debt: toPayCharge }
3. toPay > 0 && (no toPayDetails || toPayDetails.charge <= 0 ) - { messageType: BILLING_RECEIPT_ADDED_TYPE, debt: null }
updated tests for these cases
> DOMA-3556 updated message type detection logic, added tests

- apps/condo/domains/common/components/BaseSearchInput/index.tsx
- apps/condo/domains/division/components/DivisionsTable.tsx
- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/pages/contact/index.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/meter/index.tsx
- apps/condo/pages/property/index.tsx
**Before:**
https://user-images.githubusercontent.com/52532264/179986536-ee4e7d32-ff2b-4a4f-a687-6328a4e3d01a.mov
**After:**
https://user-images.githubusercontent.com/52532264/179986495-0ca9faa3-9a13-4312-a295-bdaf84d89993.mov
> DOMA-3605 fixed property search loading in callcenter

- apps/condo/domains/common/components/tasks/index.tsx
- apps/condo/domains/common/utils/iframe.utils.spec.ts
- apps/condo/domains/common/utils/iframe.utils.ts
- apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
- apps/condo/domains/miniapp/components/GlobalApps/GlobalIframe.tsx
- apps/condo/pages/_app.tsx
This PR added mechanism to manage condo ui tasks for global miniapps
> [DOMA-3547] add global miniapp task progress handler

- apps/condo/bin/README.md
- apps/condo/bin/delete-meter-readings-by-property-ids.js
- apps/condo/bin/delete-meters-by-property-ids.js
Deleting meters and meter readings by IDs of properties from db script.
> Fix/condo/doma 3536/deleting meter readings by property id script

- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
- apps/condo/domains/meter/hooks/useCreateMeterModal.tsx
- apps/condo/domains/meter/hooks/useMeterValidations.ts
Now meter validation is also available in cc
> Fix/condo/doma 3548/fix use meter validations for use in cc organization

- .github/workflows/nodejs.apps.build.yml
- .gitmodules
- yarn.lock
1.  Organization created at condo
2. Condo tell miniapp to search houses by provided tin
3. Miniapp start background task and after complete ask condo to show modal with result addresses
4. If user accept form -> run another task with search for each property unit info
5. Update progress while task is in process
6. After complete -> add property map to condo
https://user-images.githubusercontent.com/25844927/180394287-d09f08eb-9d2b-4f9b-b22d-0494e49f9ead.mov
> [DOMA-3324] property importer submodule init

- apps/condo/pages/ticket/index.tsx
accidentally deleted opening tickets (https://github.com/open-condo-software/condo/pull/2002). returned back
> DOMA-2218 returned opening tickets from table in tickets view

- apps/condo/domains/common/components/Table/Index.tsx
- apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
- apps/condo/domains/meter/hooks/useMeterTableColumns.tsx
> DOMA-3739 fix last column in table in create meter page

- apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx
organizationId is requested in the top component.
> DOMA-3548 remove unnecessary useOrganizations

- apps/condo/domains/common/components/tasks/TasksContextProvider.tsx
- apps/condo/pages/_app.tsx
- apps/miniapp/pages/index.tsx
> Fix/doma 3099/duplicated tasks after update task while using localstorage

- apps/condo/bin/README.md
- apps/condo/bin/change-organization-inn.js
Script that changes inn for certain organization
> Change organization inn by organization id script added

- apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
Remove feature flag for auto classifier
Change ML url to https://ml.d.doma.ai/api/classifiers/0/
> DOMA-3801 remove auto classifier feature flag

- apps/condo/domains/common/components/containers/FormList.tsx
- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/domains/common/utils/filters.utils.ts
- apps/condo/domains/ticket/gql.js
- apps/condo/domains/ticket/hooks/useModalFilterClassifiers.tsx
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
- apps/condo/domains/ticket/schema/fields/TicketFilter.js
- apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
- apps/condo/domains/ticket/utils/clientSchema/classifierSearch.ts
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/pages/ticket/index.tsx
- apps/condo/schema.ts
> DOMA-3402 add problem classifier filter && DOMA-3399 update filter controls positions

- apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
added `dv` and `sender` to `runMutation` `completeConfirmPhoneMutation` & `resendSmsMutation`
> HOTFIX fix registration

- apps/condo/domains/common/components/icons/CloseCircleIcon.tsx
- apps/condo/domains/common/components/tasks/TaskProgress.tsx
> DOMA-3810 add error state for `<TaskProgress />`

- apps/condo/domains/billing/schema/BillingAccount.js
- apps/condo/domains/billing/schema/BillingReceipt.js
- apps/condo/domains/common/constants/utils.js
- apps/condo/domains/common/schema/fields.js
- apps/condo/domains/common/schema/plugins/dvAndSender.js
- apps/condo/domains/common/utils/validation.utils.js
- apps/condo/domains/notification/schema/RemoteClient.js
- apps/condo/domains/property/schema/Property.js
- apps/condo/domains/ticket/schema/Ticket.js
- apps/condo/domains/user/schema/ForgotPasswordService.js
- apps/condo/domains/user/schema/ForgotPasswordService.test.js
- apps/condo/domains/user/schema/User.test.js
- apps/condo/index.js
- apps/condo/pages/auth/change-password.tsx
- apps/condo/schema.ts
Adding to the `dvAndSender` plugin the logic of setting `dv` and `sender` values ​​from cookies for `create` or `update` operations.
> HOTFIX fix admin panel

- apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> DOMA-3372 Placeholder for role name field

- apps/condo/domains/onboarding/components/OnBoardingContext.tsx
Script inside useEffect hook didn`t track the onBoardingSteps changes
> Onboarding didn`t update after adding organization

- apps/condo/domains/common/components/icons/MobileIcon.tsx
- apps/condo/domains/resident/gql.js
- apps/condo/domains/resident/schema/Resident.js
- apps/condo/domains/resident/schema/fields.js
- apps/condo/domains/ticket/components/TicketId/TicketPropertyField.tsx
- apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
- apps/condo/pages/ticket/[id]/index.tsx
Also refactored resident view in admin ui and `manageResidentToTicketClientConnections` arguments.
> DOMA-3887 displayed is contact has mobile app on ticket page

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/pages/ticket/[id]/pdf.tsx
- apps/condo/pages/ticket/create.tsx
Just a quick rearrangement of imports in ticket domain
> Refactor some ticket imports

- apps/condo/domains/common/components/TrackingContext.tsx
- apps/condo/domains/common/components/trackers/TrackerInstance.spec.ts
- apps/condo/domains/common/components/trackers/TrackerInstance.ts
- apps/condo/domains/user/components/containers/AuthLayout.tsx
> [DOMA-3481] update tracking access rights check and eventName creation

- apps/condo/domains/user/schema/User.test.js
- packages/keystone/cache.js
This is a work in progress try to catch a wandering bug with `cache.js` module. Bug is caused (well, we think it caused) by race-condition.
> Hotfix request level cache

- apps/condo/domains/notification/adapters/firebaseAdapter.js
We need to detect which pushToken caused sending notification to which physical device, so added pushToken to push payload data and to processing meta to corresponding firebase response records.
Also removed redundant invalid non-string values logging
> DOMA-3939 added pushToken logging

- apps/condo/domains/meter/components/CreateMeterReadingsActionBar.tsx
- apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx
- apps/condo/domains/meter/components/ErrorsContainer.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
Meter readings could be send without contacts.
> Adding meter readings without contacts

- packages/keystone/KSv5v6/v5/registerSchema.js
https://github.com/open-condo-software/condo/pull/2040 -- losted pr
> DOMA-3791 add custom default adminConfig and labelResolver

- apps/condo/domains/organization/utils/helpers.ts
- apps/condo/pages/employee/index.tsx
Fixed helper to work with search by `OrganizationEmployeeRole` -> `name` field with `localizedText` type
> DOMA-3591 Fix search with employee role name

- apps/condo/domains/common/components/GraphQlSearchInput.tsx
- apps/condo/domains/common/components/Pickers/DateRangePicker.tsx
- apps/condo/domains/common/components/TrackingContext.tsx
- apps/condo/domains/common/components/antd/Checkbox.tsx
- apps/condo/domains/common/components/antd/Input.tsx
- apps/condo/domains/common/components/antd/Radio.tsx
- apps/condo/domains/common/components/antd/Select.tsx
- apps/condo/domains/onboarding/components/OnBoardingContext.tsx
- apps/condo/domains/ticket/components/ShareTicketModal.tsx
- apps/condo/domains/ticket/hooks/useModalFilterClassifiers.tsx
> DOMA-3480 extend tracking components

- apps/condo/domains/contact/schema/ContactRole.js
- apps/condo/domains/organization/schema/fields.js
- apps/condo/schema.ts
> HOTFIX you don't need to update organization field! use COMMON_AND_ORGANIZATION_OWNED_FIELD every where

- apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
After canceling the changes made, there is a redirect to the page of the edited ticket.
> DOMA-3770 added redirect to ticket/{id} from ticket create page.

- apps/condo/domains/common/components/GraphQlSearchInput.tsx
Clear search string after select any option
> DOMA-3983 clear search sting after select any option

- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/domains/ticket/hooks/useModalFilterClassifiers.tsx
> HOTFIX added style to select and input components

- apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
- Clear global miniapps when logout
- Refetch miniapps when login
> DOMA-3924 watch for user authenticated state

- apps/condo/domains/ticket/hooks/useTicketDeferModal.tsx
> DOMA-4062 fixed format date in deferred date picker

- apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/TicketDeferredDateField.tsx
before: When entering a date from the keyboard, the date was not selected
after: fixed it
> DOMA-4061 fixed manual changing datepicker

- apps/condo/domains/ticket/schema/TicketExportTask.js
- apps/condo/domains/ticket/schema/TicketExportTask.test.js
> HOTFIX throw error if you trying to change status of already completed export

- apps/condo/domains/common/components/tasks/TaskProgress.tsx
- apps/condo/domains/common/components/tasks/index.tsx
- apps/condo/domains/common/hooks/useMiniappTaskUIInterface.tsx
- apps/condo/domains/ticket/hooks/useTicketExportTask.tsx
and implemented it in `useTicketExportTaskUIInterface`
> DOMA-3927 added `onCancel` handler to `ITrackableTask` interface 

- apps/condo/pages/ticket/[id]/pdf.tsx
added label "retuned" in ticket pdf printout
> DOMA-3291 added "returned" in ticket pdf printout

- apps/condo/bin/notification/send-custom-message-batch.js
- apps/condo/domains/notification/constants/constants.js
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/schema.ts
fixed email sending issues in custom message batch sending script
> DOMA-3874 fixed email sending issues

- packages/ui/.babelrc
- packages/ui/package.json
- packages/ui/src/colors/index.ts
- packages/ui/webpack.config.js
- yarn.lock
> build: added basic webpack config for ts files

- apps/condo/domains/billing/access/BillingReceipt.js
- apps/condo/domains/billing/utils/clientSchema/BillingReceipt.ts
- apps/condo/domains/common/components/icons/BankCardIcon.tsx
- apps/condo/domains/common/utils/codegeneration/generate.hooks.ts
- apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
1. Changed the periods of requested receipts
2. Added read rights to BillingReceipt for related organizations
3. Wrote and used the `useCount` hook to get the number of receipts
> DOMA-4122 fix display payments indicator

- apps/condo/pages/ticket/[id]/pdf.tsx
PS: this is an addition to /pull/2230
> DOMA-3291 added reopen counter

- apps/condo/domains/ticket/tasks/reopenDeferredTickets.js
Added try catch as a temporary solution for cron job of reopening deferred task
> DOMA-4156 added try catch to reopen deffered tickets

- apps/condo/domains/ticket/utils/unit.js
> DOMA-3964 fix unitType&sectionType in resident ticket

- apps/condo/domains/common/components/EmptyListView.tsx
- apps/condo/domains/division/components/DivisionsTable.tsx
- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/pages/contact/index.tsx
Added logic for checking access to create a property/contact on EmptyListPage.
> DOMA-3978 Add access check to empty list view

- apps/condo/domains/ticket/tasks/exportTickets.js
> fix(condo): DOMA-3809 fix ticketCommentFileCount in exportTickets

- apps/condo/domains/billing/schema/BillingProperty.js
> fix(condo): DOMA-4179 fixed BillingProperty display in admin-ui

- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/pages/ticket/index.tsx
Resident's new comment indicator was not updated when tickets were refetched.
Fixed
> fix(condo): DOMA-4109 refetch tickets with comment times

- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/resident/schema/ServiceConsumer.js
- apps/condo/schema.ts
> Make ServiceConsumer.billingIntegrationOragnizationContext a deprecated field

- apps/condo/domains/contact/hooks/useTableFilters.tsx
Made the same type of filter for the column as in the control room
> DOMA-4103 change filter type

- apps/condo/domains/common/components/icons/MobileIcon.tsx
> fix(condo): DOMA-3992 fixed mobile icon markup

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
Disable ability of create unit without label provided
> DOMA-3200 unit name validation at property map form

- apps/condo/pages/property/[id]/map/update.tsx
> DOMA-3162 change map edit page title

- apps/condo/lang/ru/ru.json
A typo in the unit error text has been fixed
> fix(condo): DOMA-2866 correct a typo in error message

- apps/condo/domains/notification/constants/constants.js
- apps/condo/domains/user/schema/SendMessageToSupportService.js
- apps/condo/domains/user/schema/SendMessageToSupportService.test.js
- apps/condo/lang/en/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
- apps/condo/lang/ru/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
- apps/condo/schema.ts
- yarn.lock
Added additional information about residents in a letter for technical support (address, accountNumbers of ServiceConsumers)
> feat(condo): DOMA-3094 add address and accountNumber in email to support

- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx
- apps/condo/domains/contact/hooks/useContactRoleValidationRules.tsx
- apps/condo/domains/contact/hooks/useExistingContactRoles.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
Ban on creating a duplicate of a role and a role with an empty name.
> fix(condo): DOMA-4014 fix duplicating roles

- apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
Now you cannot add an employee with an empty name.
> fix(condo): DOMA-4262 fix validation in full name field

- apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
Fixed an issue with email field validation when entering a value containing dots (exa.mple@gmail.com was different from example@gmail.com)
https://support.google.com/mail/answer/7436150?hl=en
> fix(condo): DOMA-4230 fix validation in email field

- apps/condo/domains/common/utils/mutations.utils.js
- apps/condo/domains/user/components/auth/InputPhoneForm.tsx
- apps/condo/domains/user/components/auth/RegisterForm.tsx
- apps/condo/domains/user/components/auth/SignInForm.tsx
- apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
- apps/condo/domains/user/components/containers/AuthLayoutContext.tsx
- apps/condo/pages/auth/register.tsx
Removed disturbing "OperationCompleted" message.
Leaved it for resend sms action to get user feedback.
> Fix/condo/doma 4132/remove operation completed message after auth

- apps/condo/domains/resident/gql.js
- apps/condo/domains/user/schema/SendMessageToSupportService.js
the code used to crash if there was a deleted resident in the sample
> fix(condo): DOMA-3094 fix bug with deleted residents

- apps/condo/domains/notification/access/MessageBatch.js
- apps/condo/domains/notification/schema/MessageBatch.test.js
Async task handles all changes on server side, so actually there is no need for update access rights for anybody.
> fix(condo): DOMA-4306 refactor tests, fix random failing tests issue on MessageBatch

- apps/condo/domains/user/schema/SendMessageToSupportService.js
- apps/condo/domains/user/schema/SendMessageToSupportService.test.js
- apps/condo/lang/en/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
- apps/condo/lang/ru/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
Deleted residents are now not in the letter
> fix(condo): DOMA-3094 fix with deleted residents

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Now you can't add not unique unit label to property map
> DOMA-3170 check unit label uniqueness before add

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
> DOMA-2810 restrict adding existing floor to the section

- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
If period month is 10 then everything breks =(
> fix(condo): Fix bug with RegisterBillingReceiptsService with period

- apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
executor should not reset after ticket reopen
> fix(condo): DOMA-4309 fixed executor reset after ticket reopen

- packages/keystone/cache.js
> refactor(condo): fix race-condition

- apps/condo/domains/common/components/UseDeskWidget.tsx
added 2 more fields, role name and organization name
> DOMA-4288 added organization and role name to user info for UseDeskWidget

- apps/condo/pages/ticket/index.tsx
`callcenter` should not be able to import tickets
> fix(condo): DOMA-4389 removed ticket import from callcenter

- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Problem: if create new filter template, then was select tab "new filter"
Solution: after saving filter template need select tab with created template
> fix(condo): DOMA-4222 fixed selected filter template after saving

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/domains/property/gql.js
- apps/condo/domains/property/schema/fields/AddressMetaField.js
- apps/condo/domains/property/utils/clientSchema/PropertyTable.ts
- apps/condo/domains/property/utils/clientSchema/index.ts
This may reduce request execution time and data size sending to the client
> DOMA-4236 change gql of BuildingsTable to smaller amount of subfields

- apps/condo/domains/common/constants/regexps.js
- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/domains/contact/components/CreateContactForm.tsx
- apps/condo/domains/contact/components/EditContactForm.tsx
- apps/condo/domains/contact/components/ErrorsContainer.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
specCharValidator:
trimValidator:
> Added special char validation. Used it and trimValidator to name field on create contact page

- apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
- apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.spec.js
- apps/condo/domains/resident/tasks/helpers/spec.helpers.js
Same user gets only one billing receipt notification at a time within each execution session of the script
> feat(condo): DOMA-4351 added billing receipt notification deduplication logic

- apps/condo/domains/common/components/Table/Renders.tsx
> DOMA-3363 fix getIntegerPartOfReading fn

- apps/condo/bin/delete-contacts-by-organization-id.js
case: organization uploaded a large number of incorrect contacts and it may take several lives of organization employees to delete them manually
> DOMA-4437 Aded script for deleting all contacts from organization

- apps/condo/domains/acquiring/schema/ExportPaymentsService.js
- apps/condo/domains/billing/utils/serverSchema/index.js
Learn how to load more than 100 payments
Example of Excel loaded with fix:
> fix(condo): DOMA-4439 Learn how to load more than 100 payments

- apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
- apps/condo/pages/employee/index.tsx
- apps/condo/pages/meter/create.tsx
- apps/condo/pages/property/index.tsx
Added a special character validator for the employee name on the create page. Some refactoring and fix for a potential crash with `TypeError: Cannot read property of undefined` due to using `link: { role }`
> DOMA-2656 Use spec char validator for employee name

- apps/condo/pages/_error.tsx
removed `_error` and set `ssr = false` in `useIntl` in callcenter
added logging in condo `_error` page
> chore(condo): DOMA-4242 removed callcenter error pages

- .env.example
- .github/workflows/nodejs.apps.build.yml
- .github/workflows/nodejs.condo.cypress.yml
- apps/condo/domains/common/components/UseDeskWidget.tsx
- apps/condo/domains/miniapp/components/AppDescription/Alerts/AlreadyConnectedBilling.tsx
- apps/condo/domains/subscription/components/SubscriptionContext.tsx
- apps/condo/domains/user/components/containers/AuthLayout.tsx
- apps/condo/domains/user/components/containers/PosterLayout.tsx
- apps/condo/domains/user/components/containers/styles.tsx
- apps/condo/domains/user/schema/SendMessageToSupportService.js
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/next.config.js
- apps/condo/package.json
- yarn.lock
After discussion with the design, we decided to remove the reCAPTCHA widget. Google allows not displaying a widget if the usage page contains the message "This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply." with links to documents.
> DOMA-4392 remove displaying reCAPTCHA widget

- apps/condo/bin/fix-tickets-client-name-client-phone.js
added script for fix tickets from resident with contact, but without clientName and clientPhone
Problem:  can't reopen bad tickets from a resident with a contact but without clientName and clientPhone
> fix(condo): DOMA-4154 added script for fix tickets

- apps/condo/cypress/objects/Ticket.js
- apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx
Problem 1: GraphQlSearchInput show id while not loaded data.
Solution 1: show loading label while not loaded data.
Problem 2: not loading initial options because initialValue is empty.
Solution 2: if initialValue is empty get values from props.value.
Also:
- was fixed infinity loading stopping if all data loaded.
- the number of sent requests has been optimized. (previously, every time the search string changed, a request was sent. now the request is sent only after the user has stopped typing)
Before:
After:
> fix(condo): DOMA-4059 fixed GraphQlSearchInput

- .github/workflows/nodejs.apps.build.yml
- .github/workflows/nodejs.condo.cypress.yml
- apps/condo/domains/user/schema/SendMessageToSupportService.js
- werf.yaml
At the build stage, there are no necessary variables in env and the operation of this service should not depend on this - I skip the exception
> hotfix(condo): DOMA-4392 fix deploy to development

- apps/condo/domains/common/components/Import/Index.tsx
- apps/condo/domains/user/schema/SendMessageToSupportService.js
replace throw error on console.error
> hotfix(condo): DOMA-4392 Heal condo apps

- apps/condo/domains/acquiring/gql.js
- apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
- apps/condo/domains/acquiring/schema/fields/json/FeeDistribution.js
- apps/condo/domains/acquiring/utils/serverSchema/feeDistribution.js
- apps/condo/domains/acquiring/utils/serverSchema/feeDistribution.spec.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/resident/constants.js
- apps/condo/schema.graphql
- apps/condo/schema.ts
1. Added ability to set max and min commission 
2. Added ability to set commission for certain billing category
3. Renamed payment category for trash service and turned it on
> Doma-3858 commission calculation

- apps/condo/domains/user/components/containers/PosterLayout.tsx
before: 
after: <img width="697" alt="Screenshot 2022-10-31 at 14 25 22" src="https://user-images.githubusercontent.com/64303474/198976764-a33db4c5-558e-4f9c-b33f-45e94cc6653d.png">
> DOMA-4392 change help req style on auth page

- apps/condo/domains/ticket/components/TicketId/TicketClassifierField.tsx
> fix(condo): DOMA-4237 fixed classifier display

- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/hooks/useTicketExportTask.tsx
- apps/condo/pages/ticket/index.tsx
show action bar only after all tickets data loading
> DOMA-1753 fix blink action bar on tickets page

- apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js
- apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.spec.js
- apps/condo/domains/organization/tasks/refreshSbbolClientSecret.js
a promise was returned instead of the clientSecret value
> hotfix(condo): HOTFIX added await to return value in getClientSecret

- apps/condo/domains/common/components/Comments/index.tsx
> fix(condo): DOMA-4579 fixed ticket comments width

- apps/condo/domains/ticket/gql.js
- apps/condo/domains/ticket/schema/fields/TicketFilter.js
- apps/condo/schema.graphql
- apps/condo/schema.ts
Problems: Ticket has no field `author`, only `createdBy`. The `reviewValue` field was not requested in the request to the server.
> fix(condo): DOMA-4603 fixed ticket filter by "createdBy" and "reviewValue"

- apps/condo/bin/generate-tickets.js
- apps/condo/domains/property/schema/Property.test.js
- apps/condo/domains/property/utils/serverSchema/helpers.js
Fixed outdated usage of changed schemas
👀 → fix in `normalizePropertyMap`
> Fix/condo/doma 3915/bugs in `generate-tickets.js` script

- apps/condo/domains/common/components/ExportToExcelActionBar.tsx
- apps/condo/pages/meter/index.tsx
- apps/condo/pages/ticket/index.tsx
Timezone should not be hardcoded in СС
> fix(condo): DOMA-4662 remove hardcoded timezone

- apps/condo/bin/fix-tickets-client-name-client-phone.js
- apps/condo/bin/fix-tickets-status-updated-at.js
FixTicketsClientNameClientPhone - changed chunk size and added logging
FixTicketsStatusUpdatedAt - changed chunk size and fixed class name
> fix(condo): DOMA-4552 fixed scripts for broken tickets

- apps/condo/cypress/objects/Property.ts
- apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
When you have unsaved changes the submit button will be disabled
> DOMA-4632 ignore preview sections on save

- apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
Trying to find receipts at the address from the application that were created no earlier than 60 days ago.
If we find, then payments are available, if not, then the old logic is used
> fix(condo): DOMA-4517 Fix display payments indicator logic

- apps/condo/domains/organization/integrations/sbbol/routes.js
After successful authorization through SBBOL, there will be a redirect to the tab page of our site passed in the parameters from SBBOL
> DOMA-4665 feat custom redirect after SBBOL authComplete

- apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
Remove duplicated check for label uniqueness inside antd form and replaced it with unsaved changes validation
> DOMA-4632 check preview prop at property-map form validation

- apps/condo/pages/meter/index.tsx
Fixed empty meter readings display after meter was deleted
> fix(condo): DOMA-4698 fixed meter readings displayed for deleted meters

- apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Automatically set deadline must be calculated from date ticket was created
> fix(condo): DOMA-4679 fixed ticket deadline autoset. Removed unused code

- apps/condo/domains/ticket/tasks/closeCompletedTickets.js
Problem: some completed tickets are not closed automatically
Solution: add `try/catch` construction and add error logging
> fix(condo): DOMA-4703 Added error handling when auto-closing tickets

- apps/condo/domains/ticket/schema/Ticket.js
- apps/condo/domains/ticket/schema/Ticket.test.js
- apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
- apps/condo/index.js
Problem: tickets from resident app dont have deadline
> fix(condo): DOMA-3718 added ticket deadline from resident mobile app

- apps/condo/domains/ticket/components/TicketId/TicketResidentFeatures.tsx
Finally we decided to remove old display logic
> fix(condo): DOMA-4517 update payment indicator display logic

- apps/condo/domains/common/components/PopupSmart.tsx
- apps/condo/next.config.js
- apps/condo/pages/_app.tsx
I will add configs at another PR
> DOMA-4668 add popupsmart script to main app

- apps/condo/domains/common/components/TrackingContext.tsx
- apps/condo/domains/common/components/trackers/TrackerInstance.ts
- packages/ui/package.json
- packages/ui/src/components/Button/button.tsx
- packages/ui/src/components/Markdown/markdown.tsx
- packages/ui/src/components/_utils/analytics.ts
- yarn.lock
<details>
<summary> <h3>Analytic event from main application</h3> </summary>
</details>
<details>
<summary> <h3>Analytic event from child application</h3> </summary>
</details>
> DOMA-4762 PostMessage analytics

- packages/ui/src/components/Modal/cross.tsx
- packages/ui/src/components/Modal/index.ts
- packages/ui/src/components/Modal/modal.tsx
- packages/ui/src/components/Modal/style.less
- packages/ui/src/index.ts
- packages/ui/src/stories/Modal.stories.tsx
> feat(ui): DOMA-4692 Added Modal

- apps/condo/domains/property/components/panels/Builder/forms/FloorForm.tsx
- apps/condo/domains/property/components/panels/Builder/forms/ParkingForm.tsx
- apps/condo/domains/property/components/panels/Builder/forms/ParkingUnitForm.tsx
- apps/condo/domains/property/components/panels/Builder/forms/SectionForm.tsx
- apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
> DOMA-4814 make property map submit button primary

- apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
- apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
- apps/condo/domains/billing/hooks/useReceiptTableFilters.tsx
- apps/condo/domains/billing/utils/helpers.ts
- apps/condo/domains/common/hooks/useQueryMappers.ts
- apps/condo/domains/common/utils/tables.utils.ts
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
note: filters and search are not available for this column due to the nature of its field type (LocalizedText).
docs: https://github.com/open-condo-software/condo/blob/master/packages/keystone/fields/LocalizedText/Implementation.js
edit: filters and search now work
> feat(condo): DOMA-4616 added category column to billing receipts table

- apps/address-service/domains/common/constants/contexts.js
> Fix/address service/doma 4796/fix registry import

- packages/ui/src/components/Card/card.tsx
- packages/ui/src/components/Card/index.ts
- packages/ui/src/components/Card/style.less
- packages/ui/src/components/Tag/index.ts
- packages/ui/src/components/Tag/style.less
- packages/ui/src/components/Tag/tag.tsx
- packages/ui/src/index.ts
- packages/ui/src/stories/Card.stories.tsx
- packages/ui/src/stories/Tag.stories.tsx
<details>
<summary><h2>Simple card</h2></summary>
</details>
<details>
<summary><h2>Card with header</h2></summary>
</details>
<details>
<summary><h2>Tag</h2></summary>
</details>
> feat(ui): DOMA-4637 Card and tag components

- apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
- apps/address-service/domains/common/utils/services/suggest/providers/AbstractSuggestionProvider.js
- apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
- apps/address-service/domains/common/utils/services/suggest/providers/GoogleSuggestionProvider.js
- packages/keystone/plugins/addressService.js
Ability to pass organization tin to improve suggestions
> Feature/condo/doma 4845/address service locations boost

- apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/migrations/20221207141744-0197_manual_fix_duplicate_contacts_without_unit.js
Also fix contacts without unitName duplicates in migration (It same as 0196, but for unitName, unitType = null case)
> fix(condo): DOMA-4839 fix contact form in meter readings form

- packages/keystone/plugins/addressService.js
- packages/keystone/plugins/utils/address-service-client/AddressServiceClient.js
- packages/keystone/plugins/utils/address-service-client/index.js
Address service client was simplified
Call POST method for suggests
tin (inn) was added to jsdoc
> fix(address-service): DOMA-4880 Address service client + POST = ❤️

- packages/ui/src/components/Alert/alert.tsx
- packages/ui/src/components/Alert/index.ts
- packages/ui/src/components/Alert/mixins.less
- packages/ui/src/components/Alert/style.less
- packages/ui/src/index.ts
- packages/ui/src/stories/Alert.stories.tsx
> feat(condo): DOMA-4708 Added alerts to ui kit

- apps/condo/domains/scope/schema/AssigneeScope.test.js
- apps/condo/domains/scope/utils/serverSchema/index.js
fix AssigneeScope creation error after update ticket assignee field to user, who is already assigned in other assignee field
> fix(condo): DOMA-4901 fix AssigneeScope creation error

- bin/kmigrator.py
This allow you to create empty migration file with corresponding number and format. 
So now you can easier generate manual migrations if there is a need
> feat(global): add empty option to kmigrator

- apps/condo/domains/ticket/hooks/useTicketExportToPdfTask.tsx
- apps/condo/pages/ticket/[id]/index.tsx
- apps/condo/pages/ticket/index.tsx
this pr for https://github.com/open-condo-software/condo/pull/2672
> feat(condo): DOMA-4917 add analytics for ticket blank export

- apps/condo/pages/ticket/index.tsx
- change click area of checkbox in table
- added saving of selected tickets. Selected tickets are saved until you change the section or click on the side menu item
for https://github.com/open-condo-software/condo/pull/2672
> fix(condo): DOMA-4405 fix print ticket blank

- apps/condo/domains/common/components/Tabs.tsx
> fix(condo): DOMA-4643 Fixed icon behaviour in tabs

- packages/ui/src/components/Checkbox/checkbox.tsx
- packages/ui/src/components/Checkbox/index.ts
- packages/ui/src/components/Checkbox/mixins.less
- packages/ui/src/components/Checkbox/style.less
- packages/ui/src/index.ts
- packages/ui/src/stories/Checkbox.stories.tsx
> feat(condo): DOMA-4711 Added checkboxes to ui kit

- packages/ui/src/components/style/mixins/table.less
> fix(ui): DOMA-4653 fix borders style of markdown table

- apps/condo/domains/ticket/components/BaseTicketForm/TicketDeadlineField.tsx
- apps/condo/domains/ticket/components/TicketForm/TicketFormContext.tsx
Problem: after clicking the "Save Changes" button, when editing the deadline, the previous deadline value appeared in the ticket. 
Solution: the logic of this functionality has been slightly reworked. It also allowed us to slightly simplify the logic in callcenter
> fix(condo): DOMA-4780 fix ticket autodeadline

- packages/ui/src/components/Modal/modal.tsx
- packages/ui/src/components/Modal/style.less
- packages/ui/src/stories/Modal.stories.tsx
<details>
<summary><h2>Before</h2></summary>
</details>
<details>
<summary><h2>After</h2></summary>
</details>
> fix(ui): DOMA-5029 fix modal animation

- apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js
- apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/billing/utils/serverSchema/index.js
Now we can support partial payments in RegisterMultiPayment mutation.
> DOMA-4476 -- Multipayment support for partial payments

- packages/ui/src/components/List/index.ts
- packages/ui/src/components/List/list.tsx
- packages/ui/src/components/List/style.less
- packages/ui/src/components/Typography/constants.ts
- packages/ui/src/components/Typography/style.less
- packages/ui/src/components/Typography/text.tsx
- packages/ui/src/index.ts
- packages/ui/src/stories/List.stories.tsx
> DOMA-5056 add List component to ui kit

- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/domains/property/components/panels/Builder/UnitButton.tsx
- apps/condo/domains/property/components/panels/Builder/forms/BaseUnitForm.tsx
- apps/condo/domains/property/components/panels/Builder/forms/ParkingUnitForm.tsx
- apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
During the creation of units, if there is a duplicate in a large chessboard, it is difficult to find where this unit is already represented. 
**How it highlights:**
> DOMA-4526 feat map constructor validation

- .github/workflows/nodejs.address-service.test.yml
- apps/address-service/domains/common/utils/services/providerDetectors.js
- apps/address-service/domains/common/utils/services/search/plugins/AbstractSearchPlugin.js
- apps/address-service/domains/common/utils/services/search/plugins/SearchByGooglePlaceId.js
- apps/address-service/domains/common/utils/services/search/plugins/SearchByInjectionId.js
- apps/address-service/domains/common/utils/services/search/plugins/SearchByProvider.js
- apps/address-service/domains/common/utils/services/search/plugins/index.js
- apps/address-service/domains/common/utils/services/search/providers/GoogleSearchProvider.js
- apps/address-service/domains/common/utils/services/search/providers/index.js
- apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
- apps/address-service/domains/common/utils/services/suggest/providers/AbstractSuggestionProvider.js
- apps/address-service/domains/common/utils/services/suggest/providers/GoogleSuggestionProvider.js
- apps/address-service/index.js
Google search provider was added. For now, the `geo=google` is required to use this provider.
Also, a new search plugin was added. Use `googlePlaceId:<place_id>` as the address to search with google API.
> Feat/address service/doma-3567/google suggestions provider

- apps/condo/domains/billing/schema/BillingReceipt.js
- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
Situation:
1. Uplload billing receipt
2. Change recipient
3. Try to reupload billing receipt
--
It is not changed! 
This PR is not intended to be merged right now, because it requires a product review. Code review is appreciated :-)
> DOMA-5082 Fix bug with not updating billing recipient / receiver thorough Unified Mutation

- apps/condo/domains/notification/constants/constants.js
settings to MESSAGE_DELIVERY_OPTIONS
> feat(condo): DOMA-5169 added SMS_VERIFY_CODE_MESSAGE_TYPE 

- apps/condo/domains/ticket/access/Ticket.js
- apps/condo/domains/ticket/schema/Ticket.test.js
For the task https://jira.in.doma.ai/browse/DOMA-5141
Gave the access rights to the resident to change ticket status to `cancelled` status
> feat(condo): DOMA-5141 added resident access to manage ticket status

- apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
- apps/condo/domains/miniapp/components/IFrame.tsx
https://user-images.githubusercontent.com/50069872/214250345-b9f85571-cd08-411f-9a3f-8e8f1a09678e.mov
> feat(condo): DOMA-5178 Notify global miniapp on organization change

- apps/condo/domains/property/components/BuildingsTable.tsx
- apps/condo/pages/property/index.tsx
https://github.com/open-condo-software/condo_call_center/pull/131
> DOMA-4697 callcenter property export

- apps/condo/package.json
- package.json
- packages/next/package.json
- yarn.lock
> refactor(global): DOMA-5204 removed legacy resolution

- apps/condo/domains/common/components/GraphQlSearchInput/Renders.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> fix(condo): DOMA-3364 fixed removed employee in ticket edit page

- apps/condo/domains/organization/integrations/sbbol/routes.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js
- apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
> DOMA-5263 fixed unhandled exception in SBBOL completeAuth

- apps/condo/domains/acquiring/schema/MultiPayment.test.js
- apps/condo/domains/acquiring/schema/Payment.test.js
- apps/condo/domains/acquiring/utils/testSchema/index.js
- apps/condo/domains/organization/utils/testSchema/index.js
- apps/condo/domains/property/schema/Property.test.js
- apps/condo/domains/ticket/schema/Ticket.test.js
- packages/codegen/generate.test.utils.js
- packages/keystone/plugins/softDeleted.js
- packages/keystone/test.utils.js
🤞 Tests to refactor:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Refactor/condo/doma 5208/tests improving concept

- packages/ui/src/components/Button/style.less
- packages/ui/src/stories/Button.stories.tsx
> fix(ui): DOMA-5278 fixed button with icon

- apps/condo/domains/acquiring/schema/MultiPayment.test.js
- apps/condo/domains/acquiring/schema/Payment.test.js
- apps/condo/domains/acquiring/utils/testSchema/index.js
- apps/condo/domains/organization/utils/testSchema/index.js
- apps/condo/domains/property/schema/Property.test.js
- apps/condo/domains/ticket/schema/Ticket.test.js
- packages/codegen/generate.test.utils.js
- packages/keystone/plugins/softDeleted.js
- packages/keystone/test.utils.js
Revert changes from doma-5208 due to they do not make sense
> Refactor/condo/doma 5282/refactor deleting after tests

- packages/ui/package.json
- packages/ui/src/components/Radio/radio.tsx
- packages/ui/src/components/Select/constants.ts
- packages/ui/src/components/Select/index.ts
- packages/ui/src/components/Select/mixins.less
- packages/ui/src/components/Select/select.tsx
- packages/ui/src/components/Select/style.less
- packages/ui/src/components/_utils/analytics.ts
- packages/ui/src/index.ts
- packages/ui/src/stories/Select.stories.tsx
- yarn.lock
This PR also fixes missing `source-map-loader` dependency that cause errors at production build stage
> DOMA-5264 add Select component to the UI-KIT

- apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
- apps/condo/domains/contact/components/ContactsEditor/index.tsx
> fix(condo): DOMA-4846 added allowClear to contact phone input

- apps/condo/pages/phone/[number]/index.tsx
> fix(condo): DOMA-4870 cut address postfix if address street has 2 rows

- apps/condo/domains/common/components/containers/LoadingOrErrorPage.tsx
- apps/condo/pages/ticket/index.tsx
**Before:**
https://user-images.githubusercontent.com/52532264/218782371-070808e4-ed5e-4081-86e2-e9dbca3cb843.mov
**After:**
https://user-images.githubusercontent.com/52532264/218782084-3a555b40-4c0a-4a8b-b0d4-790f3a123d73.mov
> fix(condo): DOMA-4689 fix loading on ticket page

- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/pages/ticket/[id]/index.tsx
When ticket has deleted property, then should disable edit button and show hint
> fix(condo): DOMA-2606 fixed ticket editing when property deleted

- apps/condo/pages/ticket/[id]/index.tsx
> fix(condo): DOMA-4773 show access denied page if employee does not have access to the ticket

- apps/condo/domains/common/components/Comments/CommentForm.tsx
- apps/condo/domains/common/components/Comments/index.tsx
> fix(condo): DOMA-3720 fixed comment editing

- apps/condo/domains/ticket/contexts/TicketVisibilityContext.tsx
- apps/condo/pages/ticket/[id]/index.tsx
- packages/codegen/generate.hooks.ts
Also fixed flickering after ticket changed in `ticket/[id]` page (bug appeared after this [pull request](https://github.com/open-condo-software/condo/pull/2902))
> fix(condo): DOMA-5341 refactored useAllObjects hook

- apps/condo/domains/common/components/TrackingContext.tsx
**Problem**: Analytics event might be sent before parent context execute `init()`
**Solution**: Move `init()` call right before first paint with `useLayoutEffect` hook
> DOMA-5418 init analytics instances before first render

- apps/address-service/bin/regenerate-keys.js
- apps/address-service/domains/common/utils/addressKeyUtils.js
> Fix/address service/doma 5443/wrong same addresses

- apps/condo/domains/common/hooks/useSearchByPhoneModal.tsx
https://user-images.githubusercontent.com/56914444/221897880-aae6f60b-34f3-4646-b88c-23d9f9503987.mov
https://user-images.githubusercontent.com/56914444/221898158-40178ac3-0eaa-49cf-9633-21db974bc9ef.mov
> fix(condo): DOMA-4930 fixed search input by phone modal

- apps/address-service/bin/regenerate-keys.js
- apps/address-service/bin/update-address.js
> Feat/address service/doma 5458/script for update address model

- apps/condo/cypress/fixtures/featureFlags.json
- apps/condo/domains/common/constants/featureflags.js
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
Since we decided to remove the feature flag to update the tickets page, removed it from the code
> refactor(condo): DOMA-5486 removed refetch-tickets-in-control-room feature flag

- packages/ui/src/components/Select/select.tsx
- packages/ui/src/components/Select/style.less
- packages/ui/src/stories/Select.stories.tsx
- Updated styles
- Added empty dropdown content
- Added new props
- Added multiple mode
- Fixed a situation where the selected long value went beyond the width of the component
---
- When `displayMode` is set to `fit-content` and selected multiple mode then component to collapse. This is due to the implementation of the component in `antd`.
> fix(condo): DOMA-5473 updated Select component

- packages/ui/src/components/Tabs/index.ts
- packages/ui/src/components/Tabs/style.less
- packages/ui/src/components/Tabs/tabs.tsx
- packages/ui/src/index.ts
- packages/ui/src/stories/Tabs.stories.tsx
> feat(ui): DOMA-5527 Added basic tabs

- apps/condo/domains/organization/tasks/syncSbbolBankAccounts.js
- apps/condo/domains/organization/tasks/syncSbbolTransactions.js
> DOMA-5534 fix GQLError in syncSbbolBankAccounts task

- apps/condo/domains/billing/hooks/useReceiptTableColumns.ts
- apps/condo/domains/common/components/Pickers/DateRangePicker.tsx
- apps/condo/domains/common/components/Table/Filters.tsx
- apps/condo/domains/common/components/antd/Select.tsx
- apps/condo/domains/common/utils/filters.utils.ts
- apps/condo/domains/common/utils/tables.utils.ts
- apps/condo/domains/organization/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
plus refactored and typing has been added
> feat(condo): DOMA-5456 added analytics for dropdown filters

- apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
- apps/condo/domains/miniapp/components/IFrame.tsx
https://user-images.githubusercontent.com/50069872/224696434-cb11a9d5-8697-4d74-bc53-844b76fb1ebd.mov
> feat(condo): DOMA-5542 Replace origins with windows

- .stylelintrc.json
- apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
- apps/condo/domains/common/components/PostMessageProvider/globalHandlers.tsx
- apps/condo/domains/common/components/PostMessageProvider/validators.ts
- apps/miniapp/package.json
- packages/bridge/src/bridge.ts
- packages/bridge/src/types/methods/ShowModalWindow.ts
- packages/bridge/src/types/methods/index.ts
- packages/ui/src/components/Modal/index.ts
- packages/ui/src/components/Modal/modal.tsx
- packages/ui/src/components/Modal/style.less
- packages/ui/src/components/Modal/useModal.tsx
- packages/ui/src/components/_utils/hooks/usePatchElement.ts
- packages/ui/src/stories/Button.stories.tsx
- yarn.lock
https://user-images.githubusercontent.com/50069872/225277910-dd7177b3-2839-4a12-9be7-b83e2bb9c076.mov
> feat(global): DOMA-5542 bridge modals

- apps/condo/pages/user/index.tsx
> Fix/condo/doma 5604/profile language control position

- .env.example
- apps/condo/domains/notification/utils/serverSchema/index.js
- apps/condo/domains/organization/schema/Organization.js
- apps/condo/domains/user/schema/SendMessageToSupportService.js
- apps/condo/index.js
- bin/keystone-dev.js
- packages/featureflags/README.md
- packages/featureflags/featureToggleManager.js
- packages/keystone/logging/GraphQLLoggerApp.js
- packages/keystone/logging/getKeystonePinoOptions.js
- packages/keystone/logging/getReqLoggerContext.js
- packages/keystone/logging/index.js
- packages/keystone/tasks.js
I've ported commits from https://github.com/open-condo-software/condo/pull/2462
> Fix logging and improve DX

- apps/condo/domains/billing/utils/serverSchema/index.js
- apps/condo/domains/notification/utils/serverSchema/index.js
- apps/condo/domains/property/utils/serverSchema/index.js
- packages/codegen/generate.server.utils.js
As you can see we have some dead code.
---
**Q**: Why do you need to add a code guard? 
**A**: Look inside file changes
> Add `generateServerUtils` code guard

- packages/keystone/adapterCache.js
We need to debug why hitrate on condo.d is 30%
Add cache drops counter to adapter cache statistics loggier
> refactor(condo) HOTFIX: add drop statistics to adapter cache

- packages/keystone/adapterCache.js
- packages/keystone/requestCache.js
Too match logs for local development!
> HOTFIX wrong cache logging

- packages/apollo-server-client/Readme.md
- packages/apollo-server-client/examples/Todo.txt
- packages/apollo-server-client/examples/ticket.js
- packages/apollo-server-client/index.js
- packages/apollo-server-client/package.json
Modify basic integration client to support file upload
> feature(condo): DOMA-5395 added upload file support

- apps/condo/domains/banking/hooks/useCategoryModal.tsx
- apps/condo/domains/banking/tasks/importBankTransactions.js
- apps/condo/pages/property/[id]/report.tsx
> DOMA-5678 add transaction classifier to the importBankTransactions task

- apps/condo/domains/billing/gql.js
- apps/condo/domains/billing/schema/BillingReceipt.test.js
* raw is large, there is no use for it on the client
> fix(condo): DOMA-5699 removed raw from billingReceipt on client

- apps/condo/pages/incident/index.tsx
Problem in callcenter: when search by address you can get incidents from organization who don't have this address
> fix(condo): DOMA-5700 fixed search for incidents by address

- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
- apps/condo/domains/common/components/containers/EmptyLayout/EmptyLayout.tsx
- apps/condo/pages/ticket/index.tsx
Component layout was broken when the side menu was open and if there was a button to import tickets
Before:
After:
> fix(condo): DOMA-5723 fix responsive filters container

- apps/condo/next.config.js
- apps/condo/pages/_app.tsx
- apps/condo/pages/service-provider-profile.tsx
https://user-images.githubusercontent.com/50069872/229489264-09b9a2ec-3e52-408f-8047-1e0f60d0da4e.mov
> feat(condo): DOMA-5738 Separate page for service-provider

- apps/condo/migrations/20230403114510-0246_auto_20230403_0645.js
problem: can't reapply migration
> hotfix(condo): fixed migration 246 - comment about not reversible migration

- apps/condo/domains/banking/components/BankAccountReport.tsx
- apps/condo/domains/common/components/icons/TotalBalance.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/pages/property/[id]/report.tsx
Web part of bank account report
> DOMA-5140 bank account report

- apps/condo/domains/organization/schema/Organization.js
As we break some requests from the mobile app, revert this commit
> Revert "hotfix(condo): Disable reading of some relations (#3145)"

- apps/address-service/domains/common/utils/services/providerDetectors.js
- apps/address-service/domains/common/utils/services/providerDetectors.spec.js
- apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
- apps/address-service/domains/common/utils/services/search/plugins/AbstractSearchPlugin.js
- apps/address-service/domains/common/utils/services/search/plugins/SearchByFiasId.js
- apps/address-service/domains/common/utils/services/search/plugins/SearchByGooglePlaceId.js
- apps/address-service/domains/common/utils/services/search/plugins/SearchByProvider.js
- apps/address-service/domains/common/utils/services/search/providers/AbstractSearchProvider.js
- apps/address-service/domains/common/utils/services/search/providers/DadataSearchProvider.js
- apps/address-service/domains/common/utils/services/search/providers/GoogleSearchProvider.js
- apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
- apps/address-service/domains/common/utils/services/suggest/providers/AbstractSuggestionProvider.js
- apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
- apps/address-service/domains/common/utils/services/suggest/providers/GoogleSuggestionProvider.js
- apps/address-service/index.js
Some logs were added to detect error point. To reach this goal the request object passed to providers and plugins to check reqId at logs.
> Fix/condo/doma 5570/server side api bug

- apps/condo/domains/common/components/PageFieldRow.tsx
> hotfix(condo): fixed PageFieldRow

- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
Billing Receipts single mutation now works if receipient's IEC is null
> fix(condo): DOMA-5728 fixed single mutation if iec is null

- apps/address-service/domains/common/utils/services/suggest/SuggestionKeystoneApp.js
this.logger.warn(...) causes an error
No errors while logging
> fix(address-service): DOMA-5946 fix logging

- apps/condo/domains/ticket/hooks/useImporterFunctions.ts
When importing tickets, a contact was created with an incorrect `unitName`
Now `сontact` binding occurs on server side
> fix(condo): DOMA-5938 fixed tickets import

- apps/condo/domains/ticket/utils/helpers.ts
When ticket has status "completed", then the label in the deadline field is displayed as for an no "completed" ticket
fixed it
> fix(condo): DOMA-5872 fixed ticket deadline field

- apps/condo/domains/common/constants/regexps.js
- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
added validator of a string that can contain multiple email addresses separated by commas
> feat(condo): DOMA-5742 add emails validation

- packages/ui/src/components/Card/card.tsx
- packages/ui/src/components/Card/style.less
- packages/ui/src/stories/Card.stories.tsx
- packages/ui/src/tokens/tokens.json
> feat(condo): DOMA-5955 added active state for card

- apps/condo/domains/notification/adapters/apple/AppleMessaging.js
- apps/condo/domains/notification/adapters/apple/AppleSession.js
This update lets changing apns url on the fly in order to be able to test push notifications by mobile team locally
> fix(condo): DOMA-6047 moved apns url to .helm

- apps/condo/domains/miniapp/schema/SendAppPushMessageService.js
- apps/condo/domains/miniapp/schema/SendAppPushMessageService.test.js
- apps/condo/domains/notification/adapters/apple/AppleMessaging.js
- apps/condo/domains/notification/transports/push.js
Made VoIP pushes for miniapps work properly.
> fix(condo): DOMA-6050 fixed apple adapter issues & sendAppPushMessage mutation errors

- apps/condo/domains/billing/components/ServicesModal.tsx
- apps/condo/domains/common/components/containers/GlobalStyle.tsx
fixed borders for details table
> fix(condo): DOMA-5735 fixed details table

- apps/condo/domains/billing/schema/BillingReceipt.test.js
- apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.js
- apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js
- apps/condo/domains/billing/utils/validation.utils.js
- apps/condo/domains/billing/utils/validation.utils.spec.js
- apps/condo/domains/common/utils/date.js
- apps/condo/domains/resident/tasks/sendMessageToResidentScopes.task.js
- fixed some issues by adding more details to where conditions
- fixed period issues
- added test
> fix(condo): DOMA-5400 fixed where conditions

- apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
When searching for a duplicate transaction, the same fields are now taken into account as in the constraint of BankTransaction.
> fix(condo): DOMA-6064 fix where condition in found duplicate transaction

- apps/condo/domains/banking/components/BankAccountReport.tsx
- apps/condo/domains/banking/components/BankAccountVisibilitySelect.tsx
- apps/condo/domains/banking/components/BankCostItemContext.tsx
- apps/condo/domains/banking/components/SbbolImportModal.tsx
- apps/condo/domains/banking/hooks/useCategoryModal.tsx
- apps/dev-portal/docs/ui/adaptivity.en.mdx
- apps/dev-portal/docs/ui/adaptivity.ru.mdx
- packages/ui/src/components/Radio/index.ts
- packages/ui/src/components/Radio/radiogroup.tsx
- packages/ui/src/components/Radio/style.less
- packages/ui/src/components/Select/hooks/useItems.tsx
- packages/ui/src/components/Select/index.ts
- packages/ui/src/components/Select/select.tsx
- packages/ui/src/components/Select/style.less
- packages/ui/src/components/Steps/steps.tsx
- packages/ui/src/components/_utils/analytics.ts
- packages/ui/src/components/_utils/hooks/useBreakpoints.tsx
- packages/ui/src/components/_utils/responsiveObserve.ts
- packages/ui/src/components/_utils/types.ts
- packages/ui/src/hooks.ts
- packages/ui/src/index.ts
- packages/ui/src/stories/Radio/RadioGroup.stories.tsx
- packages/ui/src/stories/Select.stories.tsx
- packages/ui/src/stories/Steps.stories.tsx
> feat(ui): 💄💄💄 Condo UI 2.0. Corrected all errors omitted in the design

- apps/condo/domains/common/components/Comments/index.tsx
Before:
https://github.com/open-condo-software/condo/assets/52532264/64fd984f-df6c-4465-a9c2-a588379cb141
After:
https://github.com/open-condo-software/condo/assets/52532264/4860618b-18c7-4111-9035-32542a8228b5
> fix(condo): DOMA-6117 fix ticket comments scroll

- packages/featureflags/featureToggleManager.js
The error was not caught because promises chaining was used instead of using syntax with `await`.
Also wrap the `FeatureToggleManager config error!` error in `try/catch`
> fix(condo): DOMA-6116 catch features response parsing error

- apps/condo/domains/banking/schema/BankAccountReportTask.test.js
Sometimes the test crashes due to the fact that afterChange a worker task is launched, which can change the fields, so the tests crash. Wrapped in waitFor, should help
https://github.com/open-condo-software/condo/actions/runs/4945958567/jobs/8843403980
> hotfix(condo): HOTFIX random tests in BankAccountReportTask

- packages/keystone/metrics.js
Adds hostname tag to every sent metric
> Add hostname to metrics.js

- apps/condo/domains/common/components/DeleteButtonWithConfirmModal.tsx
- apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/pages/ticket/index.tsx
- packages/ui/src/components/Button/style.less
fix(ui): DOMA-5914 added minimum width for Button component
fix(condo): DOMA-5914 added label for ticket import button
https://github.com/open-condo-software/condo/assets/56914444/91ab4c4b-3bb3-45e2-b7bc-b9390281d417
https://github.com/open-condo-software/condo/assets/56914444/20901620-5bce-4de8-bd16-a04bbba9c748
> fix(condo): DOMA-5914 fixed multiple filter modal footer

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/components/TicketClassifierSelect.tsx
- apps/condo/domains/ticket/components/TicketId/TicketQualityControlFields.tsx
- apps/condo/domains/ticket/components/TicketPropertyHint/BaseTicketPropertyHintForm.tsx
- apps/condo/domains/ticket/components/TicketStatusSelect.tsx
- apps/condo/domains/ticket/hooks/useClientCardTicketTableColumns.tsx
- apps/condo/domains/ticket/hooks/useTicketChangedFieldMessagesOf.tsx
- apps/condo/domains/ticket/hooks/useTicketPropertyHintTableColumns.tsx
- apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Sometimes data is null/undefined and querying nested fields is impossible, so UI throws. Fixed such potentially dangerous places.
> fix(condo): DOMA-6157 fixed potentially dangerous data queries

- .github/workflows/nodejs.apps.build.yml
- bin/publish-packages.js
- package.json
> hotfix(condo): DOMA-5862 move turbo to yarn

- yarn.lock
Added recurrent payments fix
Removed dependancy from condo/user domain
Added OIDC auth
Added setup page
Fixed translates
> feature(condorb): DOMA-6058 setup page for self service billing

- apps/condo/domains/organization/components/EmployeeForm/CreateEmployeeForm.tsx
- apps/condo/domains/organization/components/EmployeeForm/UpdateEmployeeForm.tsx
- apps/condo/domains/organization/hooks/useEmployeeValidations.ts
Problem: form validation does not display errors if the user with the specified phone or email is already a employee of the organization
> fix(condo): DOMA-5245 fixed validator on employee creating and updating pages

- apps/condo/domains/common/components/Poster.tsx
- apps/condo/domains/user/components/auth/RegisterForm.tsx
- apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
- apps/condo/domains/user/components/containers/AuthHeader.tsx
- apps/condo/domains/user/components/containers/AuthLayout.tsx
- apps/condo/domains/user/components/containers/PosterLayout.tsx
- apps/condo/domains/user/components/containers/styles.tsx
- apps/condo/pages/404.tsx
- apps/condo/pages/500.tsx
- apps/condo/pages/_error.tsx
Made adaptive pages according to [layouts](https://www.figma.com/file/uyYAPR012LK5vFO2L6BFn9/00-%D0%A4%D0%B8%D1%87%D0%B8?type=design&node-id=3691-19430&t=oJqSe91b5CwYBe8N-0)
> refactor(condo): DOMA-6150 refactor auth layouts

- apps/condo/domains/organization/components/OrganizationSelect.tsx
Problem: if user have more than 100 organizations then will be load only first 100
> fix(condo): DOMA-6166 fixed loading in organization select

- yarn.lock
Added SPP Flow (under feature flag) 
Added pages for self-service billing (has no influence on old registry flow)
[DOMA-5758] [DOMA-6140]
SETUP Page for  self-service billing:
SPP Flow:
> feature(registry): DOMA-6140 update registry submodule

- apps/condo/domains/billing/components/ServicesModal.tsx
> fix(condo): DOMA-6054 add disabled state to pdf button

- packages/keystone/adapterCache.js
We want to remove dependency from:
1. UpdatedAt field
2. TimeSync between pods
And in general we want cache to be more simple.
=>
Rewrite cache to increment based algo
> Rewrite cache to increment based algorithm

- apps/condo/domains/user/components/auth/ValidatePhoneForm.tsx
- apps/condo/pages/auth/change-password.tsx
- apps/condo/pages/auth/forgot.tsx
- added show error on change password page
- also some refactored with component from `@open-condo`
> fix(condo): DOMA-4696 added show error on change password page

- apps/condo/domains/contact/hooks/useTableColumns.tsx
- apps/condo/domains/contact/hooks/useTableFilters.tsx
- apps/condo/pages/contact/index.tsx
Problem: sorting and filtering by `role` for contact no work
PS there is no `role` column in the callcenter
> fix(condo): DOMA-5073 fixed filter and sort by role for contacts

- apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
- apps/condo/domains/common/constants/style.js
- apps/condo/domains/user/components/containers/PosterLayout.tsx
> DOMA-6218 increase max content width to 1600

- apps/condo/domains/news/schema/NewsItem.js
- apps/condo/domains/news/schema/NewsItem.test.js
- packages/keystone/test.utils.js
> chore(condo): DOMA-6244 allow admin&support to read scopes

- apps/condo/domains/common/components/MenuItem.tsx
- apps/condo/domains/common/components/ResidentActions/ResidentActions.tsx
- apps/condo/pages/_app.tsx
> chore(condo) DOMA-6257 add side menu id

- apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
There are two types of accounts: active and passive. Passive means borrowed funds; active - placed funds of a company, enterprise or bank. For active accounts: debit - income, credit - expenditure. For passive: credit - income, debit - expense.
> hotfix(condo): HOTFIX invert transaction direction in SBBOL transaction request

- apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
- apps/condo/domains/common/components/PostMessageProvider/types.ts
- apps/condo/domains/common/components/PostMessageProvider/validators.ts
- apps/condo/domains/miniapp/components/IFrame.tsx
- apps/miniapp/domains/common/utils/oidcAuth.tsx
- apps/miniapp/index.js
- apps/miniapp/pages/index.tsx
- packages/bridge/src/bridge.ts
- packages/bridge/src/types/methods/RequestAuth.ts
- packages/bridge/src/types/methods/index.ts
Miniapp codebase is a mess btw, so don't copy from it :)
> feat: DOMA-6240 OIDC bridge auth

- yarn.lock
> feature(condorb): Doma-6326 send accept to email

- apps/condo/domains/billing/components/BillingPageContent/index.tsx
- apps/condo/domains/common/components/PostMessageProvider/Provider.tsx
- apps/condo/domains/common/components/PostMessageProvider/globalHandlers.tsx
- apps/condo/domains/common/components/PostMessageProvider/validators.ts
- apps/miniapp/domains/common/utils/oidcAuth.tsx
- apps/miniapp/pages/_app.tsx
- packages/bridge/src/bridge.ts
- packages/bridge/src/types/methods/UpdateModalWindow.ts
- packages/bridge/src/types/methods/index.ts
https://github.com/open-condo-software/condo/assets/50069872/7f19491a-34cb-46d0-88be-1c6c705a018e
> feat(global): DOMA-6439 bridge modal updates

- apps/condo/domains/common/components/Logo.tsx
- apps/condo/domains/common/components/MenuItem.tsx
- apps/condo/domains/common/components/ResidentActions/ResidentActions.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/SideNav/DesktopSideNav.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/SideNav/MobileSideNav.tsx
- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
- apps/condo/domains/common/components/containers/global-styles.css
- apps/condo/pages/_app.tsx
https://github.com/open-condo-software/condo/assets/50069872/a027251e-9f19-4d08-b049-d81029430438
> feat(global): new side-menu 💄💄💄

- yarn.lock
1. Text fixes for accept email and button on setup page
2. Added error on organisation not found event
3. Added reconciliation model by @AntonAL 
4. Added distribution fixes by @ekabardinsky 
5. Added jest tests to rb submodule by @AntonAL
> fix(rb): DOMA-6490, DOMA-6476, DOMA-6213, DOMA-6381 update rb submodule

- apps/condo/domains/ticket/components/TicketId/TicketUserInfoField.tsx
used next link for /contact and /employee links
> fix(condo): DOMA-6536 fix name links on ticket page

- apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Also 2nd sections selector was removed
> fix(condo): DOMA-6532 promises awaiting is fixed

- packages/ui/src/components/Radio/radio.tsx
- packages/ui/src/components/Radio/style.less
- packages/ui/src/stories/Radio/RadioGroup.stories.tsx
> feat(ui): DOMA-6580 added radio button only with icon

- apps/condo/index.js
- packages/keystone/healthCheck.js
{"redis":"pass","postgres":"pass"}
Check Reids and Postgres in any time
> Add basic custom healthcheck service

- apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
- apps/condo/domains/news/components/RecipientCounter.tsx
- apps/condo/domains/news/components/types.ts
- apps/condo/domains/news/utils/clientSchema/NewsRenders.tsx
- apps/condo/domains/user/components/UnitNameInput.tsx
Also, added `disabled` prop to UnitNameInput
> fix(condo): DOMA-6531 Fix sections detection (+parkings)

- apps/condo/domains/common/components/AudioPlayer.tsx
**Bug:** if you press pause and change the speed, the audio was played.
Fixed it
> fix(condo): DOMA-6564 fix audio playing on change speed

- apps/condo/domains/common/components/Table/Renders.tsx
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
> fix(condo): DOMA-6654 fix ticket table columns ellipsis

- apps/condo/domains/common/components/containers/global-styles.css
- apps/condo/domains/property/components/PropertyReportCard.tsx
- packages/ui/src/components/Modal/style.less
> feat(condo): DOMA-6669 organization select minor improvements

- apps/condo/domains/banking/components/BankAccountReport.tsx
- apps/condo/pages/property/[id]/report.tsx
> DOMA-6672 mobile layouts for bank account report page

- apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
- apps/condo/domains/news/components/TemplatesTabs.tsx
https://github.com/open-condo-software/condo/assets/93817911/080c2c58-793b-4c9d-b25d-557d65b189cb
> fix(condo): DOMA-6607 add arrow for templates switch

- apps/condo/domains/common/components/AudioPlayer.tsx
The cors error returns the code 200, but throws the js error.
Changed the processing of the second request
> fix(condo): DOMA-6694 fix audio file request

- apps/condo/pages/ticket/index.tsx
> fix(condo): DOMA-6704 fixed display call records link on small screens

- apps/condo/domains/contact/hooks/useTableColumns.tsx
- apps/condo/domains/organization/hooks/useTableColumns.tsx
- apps/condo/domains/ticket/components/TicketId/TicketAssigneeField.tsx
- apps/condo/domains/ticket/components/TicketId/TicketClientField.tsx
- apps/condo/domains/ticket/components/TicketId/TicketExecutorField.tsx
- apps/condo/domains/ticket/components/TicketId/TicketUserInfoField.tsx
- apps/condo/domains/ticket/hooks/useCallRecordTableColumns.tsx
- apps/condo/pages/contact/[id]/index.tsx
- apps/condo/pages/employee/[id]/index.tsx
- apps/condo/pages/phone/[number]/index.tsx
> fix(condo): DOMA-6718 remove phoneNumberPrefix for phone links from condo

- apps/condo/domains/analytics/components/Dashboard.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> DOMA-6728 change month title from fixed to current month

- apps/condo/domains/organization/schema/Organization.test.js
- packages/keystone/schema.js
A follow up to the previous task with the same key. 
We need a way to get all relations which depend on certain list.
Like:
BillingIntegrationOrgamnizationContext -> BillingProperty, BillingReceipt, BillingAccount
> DOMA-6615 Add ability to get list dependent relations

- packages/keystone/adapterCache.js
// If debug mode is turned on, then an additional request would be made to database on cached queries.
// If cached data differs from response, then an error is logged
// SHOULD NOT BE USED IN PRODUCTION MODE
> refactor(condo): DOMA-6787 add cache debug mode

- apps/condo/domains/ticket/components/BaseTicketForm/AutoAssigner.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
No need to set employees with deleted users as executor or assignee in ticket
> fix(condo): DOMA-6716 filter deleted users in query for ticket assigments

- apps/condo/pages/phone/[number]/index.tsx
> fix(condo): DOMA-6735 change location of organization name message in phone page

- apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
update helm and added tracking to not ui-kit component of news templates
> feat(condo): DOMA-6433 added amplitude to news

- apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
- apps/condo/domains/news/components/TemplatesTabs.tsx
> feat(condo): DOMA-6613 changed indents to match layouts

- apps/condo/domains/ticket/schema/TicketComment.test.js
- apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js
- apps/condo/domains/ticket/utils/handlers.js
- apps/condo/domains/ticket/utils/handlers.spec.js
Added push notification to assignee and executor of ticket when resident leaves comment in this ticket
> feat(condo): DOMA-6834 added ticket resident comment create notification

- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
- apps/condo/pages/meter/index.tsx
> feat(condo): DOMA-6582 added button of meter reading creating

- apps/condo/domains/notification/constants/constants.js
- apps/condo/domains/ticket/schema/TicketComment.test.js
- apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js
- apps/condo/domains/ticket/utils/handlers.js
- apps/condo/domains/ticket/utils/handlers.spec.js
- apps/condo/schema.graphql
- apps/condo/schema.ts
Since the mobile app has made improvements to [this task](https://github.com/open-condo-software/condo/pull/3695), it can be returned to master
> DOMA-6834 Return 6834 task into master

- packages/apollo-server-client/index.js
1. Added auth to miniApp method ( using OIDC )
2. Added support for different env's authRequisites field names
3. Added log entries on network errors 
What for: 
Client wants to upload RegistryFile (integration with 1C)
Before this changes he was not able to authorise to registry-miniApp directly as it is using OIDC auth
> feat(condo): DOMA-6561 added oidc auth to server apollo client

- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
- apps/condo/domains/billing/utils/testSchema/index.js
It's a part of another PR needed for hotfix
> bug with seververConsumer in output of allResidentBillingReceipts

- packages/keystone/tracing.js
- Add postfix indicating the service
- Add taskId reqId or execId to the attributes
> Improve tracing

- .yarn/patches/@keystonejs-patches.md
- .yarn/patches/README.md
Add documentation to the `patches` folder
> fix(condo): DOMA-3959 Add documentation!

- apps/condo/bin/billing/chargeRecurrentPayments.js
- apps/condo/bin/billing/createRecurrentPaymentForNewBillingReceipt.js
- apps/condo/bin/billing/createRecurrentPaymentForReadyToPayRecurrentPaymentContexts.js
- apps/condo/bin/billing/discoverServiceConsumers.js
- apps/condo/bin/billing/notifyBeforeRecurrentPaymentDate.js
- apps/condo/domains/common/utils/serverSchema/index.js
- apps/condo/package.json
- yarn.lock
The new script's aim is to create `ServiceConsumer` models for a given organization.
Usage:
```bash
yarn workspace @app/condo node bin/billing/discoverServiceConsumers -h
```
> Feat/condo/doma 6963/discover service consumers script

- yarn.lock
Added 2 API handlers to integrate with EPS for SPP
Handlers are protected with Basic Auth and IP filter
> feat(registry): DOMA-7075 new SPP flow to work with EPS

- apps/condo/domains/acquiring/gql.js
- apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.js
- apps/condo/domains/acquiring/schema/CreatePaymentByLinkService.test.js
- apps/condo/schema.graphql
- apps/condo/schema.ts
Some additional fields were added according to the design.
> Chore/condo/doma 7111/qr codes additionals

- apps/condo/domains/resident/constants/constants.js
enable new payment category for mobile app
> fix(eps): enabled payment category

- apps/condo/domains/resident/tasks/notifyResidentsOnPayday.js
Real clients usually have no more than 5 receipts. However, there are test users who have more than 100 receipts, in which case `getAll` gives an error: exceeded server limits. Along the way, I added a counter of unsuccessfully processed consumers
> fix(condo): DOMA-6697 use loadListByChunks to get receipts. Some test consumers have more than 100 receipts

- packages/clients/finance-info-client/FinanceInfoClient.js
- packages/clients/finance-info-client/README.md
- packages/clients/finance-info-client/index.js
added dadata wrapper to get information about bank and organization
> feature(condo): DOMA-7107 getBankInfo and getOrganizationInfo

- apps/condo/domains/common/utils/helpers.ts
> fix(condo): DOMA-4856 fixed render of address

- apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
> hotfix(condo): added chunkSize to get serviceConsumers

- apps/condo/domains/organization/components/OrganizationSelect.tsx
- apps/condo/domains/user/components/UserOrganizationsList.tsx
> fix(condo): DOMA-7308 fix org duplication in select and user profile page

- apps/condo/domains/common/components/ChangeHistory/ChangeHistoryDiff.tsx
- apps/condo/domains/common/components/ChangeHistory/HistoricalChange/index.tsx
- apps/condo/domains/common/components/ChangeHistory/HistoricalChange/types.ts
- apps/condo/domains/common/components/ChangeHistory/index.tsx
- apps/condo/pages/incident/[id]/index.tsx
- apps/condo/pages/ticket/[id]/index.tsx
<details>
<summary><h3>Some screenshots</h3></summary>
</details>
> feat(condo): DOMA-7032 added change history for pass miniapp

- apps/condo/lang/en/en.json
https://github.com/open-condo-software/condo/assets/56914444/516367d0-1374-4c3f-8734-68cbc05e3cf0
--------
[fix(pass): DOMA-7384 fixed breadcrumbs](https://github.com/open-condo-software/condo-pass/commit/dfa4aafa7f8680ae3cd4c70abf90e6ec7aa6481a)
> feat(condo): DOMA-7030 export of passes

- apps/condo/domains/resident/tasks/helpers/sendBillingReceiptsAddedNotifications.js
The `serviceConsumer` connection to the `BillingIntegrationOrganizationContext` is a deprecated field and is not kept up to date. Therefore, there is a certain number of consumers who have a connection to the deleted `BillingIntegrationOrganizationContext`. This happens when an `organization` is transferred from one `BillingIntegration` to another. This does not happen when searching for consumers using a `accountNumber`.
> fix(condo): DOMA-7435 find consumers by accountNumber instead of billing context

- apps/condo/domains/common/components/containers/BaseLayout/Header.tsx
- apps/condo/domains/common/components/containers/GlobalStyle.tsx
- apps/condo/domains/common/components/tasks/TaskProgress.tsx
- apps/condo/domains/common/components/tasks/TasksContextProvider.tsx
- apps/condo/domains/common/components/tasks/index.tsx
- apps/condo/domains/common/hooks/useExportTaskUIInterface.tsx
- apps/condo/pages/_app.tsx
New mobile layout for task notification
- Minimised by default
- Add "close all tasks" button
- Close task control link
> DOMA-7458 mobile layout for task control panel

- packages/keystone/KSv5v6/v5/prepareKeystone.js
- packages/keystone/tracing.js
I have added the root middleware to tracer, which will capture all requests
I decided to ditch (at leatst for now) HTTP instrumentation, because it created too much noise!
I added user.id and operation.name to this middleware
> INFRA-114 Add user.id to tracing

- apps/condo/pages/property/[id]/report.tsx
Show an error, that could be occurred when user change organization at property report page
> fix(condo): DOMA-5889 show property not found error at report page

- apps/condo/domains/contact/hooks/useTableFilters.tsx
- apps/condo/domains/property/utils/tables.utils.ts
- apps/condo/lang/ru/ru.json
https://github.com/open-condo-software/condo/assets/56914444/7119dd7a-bbab-4d16-8521-16835161f00d
https://github.com/open-condo-software/condo/assets/56914444/85580cd0-1f3f-4b12-b1bd-ac1355f2aec2
> feat(condo): DOMA-7680 added filter by units (type + name)

- .husky/pre-commit
- apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
Also, husky pre-commit script was fixed
> fix(condo): DOMA-7890 Make 'no vat' as default option

- apps/condo/domains/news/tasks/publishSharedNewsItemsByNewsItem.js
Just a fix, that was meant to be in original PR >__<
> fix(condo) DOMA-7581: Fix circular import warning during `yarn dev`

- .github/workflows/nodejs.address-service.test.yml
- apps/address-service/domains/common/utils/healthchecks.js
- apps/address-service/domains/common/utils/services/DadataHealthChecker.js
- apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
- apps/address-service/index.js
> feat(address-service): INFRA-141 add balance & daily limits healthchecks

- apps/condo/domains/common/components/containers/YandexMetrika.tsx
This reverts commit c6cffdd8bb554f6d205b927fc887cb3a590052d6.
> Revert "feat(condo): DOMA-7939 yandex metrika v2 (#4164)"

- apps/condo/domains/common/utils/importer.spec.ts
> chore(condo): DOMA-8001 fixed typing for importer tests

- apps/condo/domains/marketplace/components/MarketplaceOnboarding/RequisitesSetup.tsx
- apps/condo/domains/marketplace/schema/Invoice.js
- apps/condo/domains/marketplace/schema/fields/invoiceRows.js
> Fix/condo/doma 8032/various bugs

- apps/condo/domains/billing/constants/registerBillingReceiptService.js
1. Decreased limits for bulk search in address service
2. Fixed period compare
> fix(condo): adderess service limits decrease and period fix

- apps/condo/migrations/20231215145832-0353_remove_invoicecontext_createdby_and_more.js
Now on review stand is an error for adding not null organization field to Invoice table
> fix(condo): marketplace migration

- apps/condo/domains/common/utils/exportToExcel.js
- apps/condo/domains/common/utils/serverSchema/export.js
- apps/condo/domains/common/utils/serverSchema/export.spec.js
- apps/condo/domains/contact/tasks/exportContacts.js
- apps/condo/domains/ticket/tasks/exportIncidents.js
- apps/condo/domains/ticket/tasks/exportTickets.js
> fix(condo): DOMA-8197 fixed export to csv

- .github/workflows/deploy_development.yaml
- .github/workflows/deploy_production.yaml
- werf.yaml
- yarn.lock
- Added configs for deploy `telegram-employee-bot`
- Removed unused code and deps in `telegram-employee-bot`
> feat(telegram-employee-bot): DOMA-8193 added deploy configs for telegram-employee-bot

- apps/condo/bin/delete-meter-readings-by-properties.js
changed MeterReading date filter to createdAt interval, added import type in filter
> fix(condo): DOMA-8255 update delete meter reading script

- apps/condo/domains/acquiring/components/AcquiringReceipt.tsx
Fix for DOMA-7922 and DOMA-7923
> Fix/condo/doma 7923/fix currency position within receipt

- apps/condo/domains/marketplace/hooks/useMarketplacePaymentTableColumns.tsx
> fix(condo): DOMA-8096 fix transactionId render in marketplace payments tab

- apps/condo/domains/banking/components/BankAccountInfo.tsx
- apps/condo/domains/organization/components/Recipient/SettingsContent.tsx
> fix(condo): DOMA-7828 fixes after design review

- apps/condo/domains/banking/components/BankAccountInfo.tsx
- apps/condo/domains/marketplace/hooks/useMarketplacePaymentTableColumns.tsx
> fix(condo): DOMA-7828 fix layout of BankAccountInfo on settings page

- apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
- apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
- apps/condo/domains/marketplace/components/MarketItemContent.tsx
- apps/condo/domains/marketplace/gql.js
Used the `order` field to sort `MarketCategory` in different lists
> fix(condo): DOMA-8284 fix categories sort order

- apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
- apps/condo/domains/marketplace/components/MarketItem/BaseMarketItemForm.tsx
- apps/condo/domains/marketplace/components/MarketItemContent.tsx
`/marketplace`:
`/marketplace/marketItem/create`:
`/marketplace/invoice/create`:
> fix(condo): DOMA-8284 sorted categories in alphabetical order

- apps/condo/domains/common/components/Table/Renders.tsx
- apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
- apps/condo/domains/marketplace/hooks/useMarketplacePaymentTableColumns.tsx
- apps/condo/domains/marketplace/hooks/useMarketplacePaymentsFilters.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> feat(condo): DOMA-8276 add filters on payments tab on Marketplace page

- apps/condo/domains/marketplace/components/MarketplacePaymentsContent.tsx
> fix(condo): DOMA-8276 fix layout of filters

- apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
> feat(condo): DOMA-8272 Use Promise.all for requests to dadata

- apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
> fix(condo): DOMA-8284 fix sort options by order field

- apps/condo/domains/ticket/components/IncidentHints.tsx
Problem: actual hints with incidents are not displayed for houses that have had many incidents (100+)
> hotfix(condo): fixed IncidentHints

- .gitmodules
- yarn.lock
A small application to make life easier for CC employees
The application retrieves new claims from EDS and sends a telegram message about it
> feat(condo): DOMA-8405 added app eds-mosreg-integration

- apps/condo/domains/ticket/utils/helpers.ts
Problem: func return `NaN` if change status to `canceled`
> fix(condo): DOMA-8434 fixed label of ticket deadline

- apps/condo/domains/acquiring/schema/fields/Recipient.js
- apps/condo/domains/billing/components/OnBoarding/BillingDescriptionModalContent.tsx
- apps/condo/domains/billing/components/OnBoarding/SetupAcquiring.tsx
- apps/condo/domains/billing/components/OnBoarding/SetupBilling.tsx
- apps/condo/schema.graphql
- apps/condo/schema.ts
WIP
CONDO domain: 
remove setting status "Finished" to `BillingIntegrationOrganizationContext` on step 1 of self-service setup. Now it is set to Finished at the last step, with the offer accept
CONDO RB domain (waits merging):
move setting status "Finished" to `AcquiringIntegrationContext` to afterChange hook on `Accept` creation
> Feat/condo/doma 8437/change billing setup flow

- apps/condo/package.json
- yarn.lock
Fixed datepicker keyboard input
https://github.com/open-condo-software/condo/assets/56914444/44f7a1b0-aaa3-471a-9c6f-6a3b545f3f6c
_______
https://github.com/open-condo-software/condo/assets/56914444/194e862b-e6da-4993-bd23-78fa4a63d815
> chore(deps): DOMA-6771 bump rc-picker from 2.6.10 to 4.2.0

- apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
- apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx
- apps/condo/pages/settings/index.tsx
> fix(condo): DOMA-8538 hidden unnecessary sections in role settings in callcenter

- apps/condo/pages/ticket/index.tsx
> fix(condo): DOMA-8648 fix TicketTypeFilterSwitch spacing on small screens

- apps/condo/lang/en/en.json
Hi, this PR is just an umbrella for all english translation fixes I want to work on
> HOTIFX: Update english translations

- apps/address-service/bin/update-address.js
- apps/address-service/domains/common/utils/services/search/searchServiceUtils.js
- apps/address-service/index.js
Also, some missed lower-casing was added
> fix(address-service): DOMA-8640 change plugins order

- packages/keystone/KSv5v6/v5/prepareKeystone.js
This is a temporary change until the cause is determined
> fix(condo): INFRA-229 disable sentry at production

- .gitmodules
- yarn.lock
Here is swagger doc for the service:
You can check it in https://editor.swagger.io
```(json)
{
"openapi": "3.0.0",
"info": {
"title": "Doma.ai REST API}",
"version": "1"
},
"servers": [
{
"url": "https://restapi.d.doma.ai"
}
],
"paths": {
"/api/bank-analytics/v1/ticket/all": {
"get": {
"parameters": [
{
"name": "first",
"in": "query",
"description": "Number of items to be shown (useful for pagination)",
"required": true,
"schema": {
"type": "integer",
"minimum": 0
}
},
{
"name": "skip",
"in": "query",
"description": "Number of items to skip (from the last item by sortby query - useful for pagination)",
"required": true,
"schema": {
"type": "integer",
"minimum": 0
}
},
{
"name": "createdAt_lte",
"in": "query",
"description": "CreatedAt less then / equal. Should be ISO string",
"required": …
```
> REST API service for Bank Analytics

- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js
- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
- apps/condo/domains/billing/schema/resolvers/utils.js
- packages/clients/finance-info-client/index.js
Now report only shows the last receipts import result. But we need to show the last period result and actual receipts count (not from the last report)
Moving report calculation to the unified mutation will help to improve all  integration's code
> feature(condo): Doma-8682 create last report in unified mutation

- apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
- apps/condo/domains/ticket/utils/clientSchema/Ticket.ts
Problem: It is impossible to delete the assignee through UI
> fix(condo): DOMA-8641 fixed deleting of assignee

- apps/condo/domains/news/gql.js
- apps/condo/domains/news/schema/NewsItem.js
Problem: I can not open news item page in admin panel
> fix(condo): DOMA-8781 fixed news item page in admin panel

- apps/condo/domains/billing/schema/RegisterBillingReceiptsService.test.js
To check the mixed output with errors and correct receipts
> fix(condo): Added  test for unified mutation 

- apps/condo/domains/banking/utils/validate/countrySpecificValidators/ru.validator.js
- apps/condo/domains/banking/utils/validate/routingNumber.utils.spec.js
Allow BICs that start with "00" for state funded organizations
> feat(condo): DOMA-8850 allow bics that start with "00"

- apps/condo/domains/common/components/Table/Renders.tsx
- apps/condo/domains/onboarding/hooks/useNoOrganizationToolTip.tsx
- apps/condo/domains/ticket/hooks/useTableColumns.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> fix(condo): DOMA-7284 fixed a deleted property in tickets

- apps/condo/migrations/20240418134550-0387_alter_message_type_alter_messageappblacklist_type_and_more.js
comment converting type to Text due to timeout of the operation (it is already of type Text)
> hotfix(condo): comment MessageType alteration on Message table

- apps/condo/domains/ticket/hooks/useImporterFunctions.ts
Problem: if unit name from file will be " ", then result unitName will be "" instead null
> fix(condo): DOMA-8937 fix ticket import unitName trim

- apps/condo/domains/common/hooks/useValidations.ts
- apps/condo/domains/contact/components/ContactsEditor/NewContactFields.tsx
- apps/condo/domains/contact/components/ContactsEditor/NotResidentFields.tsx
- apps/condo/domains/contact/components/ContactsEditor/index.tsx
- apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx
- apps/condo/domains/marketplace/utils/clientSchema/Invoice.ts
- apps/condo/domains/organization/hooks/useCreateOrganizationModalForm.tsx
- apps/condo/domains/property/components/BasePropertyForm/usePropertyValidations.tsx
- apps/condo/domains/ticket/components/BaseTicketForm/useTicketValidations.tsx
https://github.com/open-condo-software/condo/assets/56914444/022821d5-df68-44cd-93e1-041ec0589eb5
https://github.com/open-condo-software/condo/assets/56914444/65ccde3b-e54b-4323-9077-64342187f2df
> fix(condo): DOMA-8684 fixed contact editor validator for name

- yarn.lock
1. Added tabs to organization settings 
2. On the first tab one can validate accountNumber
3. On the second tab you can see the information about condo integration. Statuses of the contexts, number of receipts for the last period and information about payments. All links are pointed to the admin-ui of condo
4. On the Properties tab you can see current Properties registered in Condo for the current organization. You can add new Properties with address search input
> feature(eps): DOMA-8980 add ui for adding property to eps organizations

- apps/condo/domains/meter/components/MetersDataImporter.tsx
To be sure that cell with error will be added in the end of each row.
> fix(condo): DOMA-9037 normalize row length

- .yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch
- package.json
- packages/keystone/KSv5v6/v5/prepareKeystone.js
- yarn.lock
Original PR -> https://github.com/keystonejs/keystone-5/pull/421
> fix(global): INFRA-320 add ability to ignore dashboard counts

- apps/condo/domains/organization/components/EmployeeRoleForm/BaseEmployeeRoleForm.tsx
- apps/condo/domains/organization/components/EmployeeRolesSettingsContent.tsx
- apps/condo/domains/organization/hooks/useEmployeeRolesTableColumns.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
https://github.com/open-condo-software/condo/assets/56914444/c9ee777b-fdf2-48ba-b2c1-675639f959be
https://github.com/open-condo-software/condo/assets/56914444/eed076d2-bb49-4a05-88de-6a972c0622e7
> fix(condo): DOMA-9118 fixed custom roles after design-review

- apps/condo/domains/billing/schema/resolvers/accountResolver.js
- apps/condo/domains/billing/schema/resolvers/propertyResolver.js
- apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
In case Organization has a big number of accounts or properties
> fix(condo): DOMA-9137 do not load all billing accounts and billing properties

- apps/condo/domains/common/components/Comments/Comment.tsx
- apps/condo/domains/ticket/schema/TicketChange.js
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
Added a "Service" label to ticket changes:
And to ticket comment:
> fix(condo): DOMA-9289 fix service user display in ticket changes and comments

- apps/condo/domains/common/constants/featureflags.js
This should fix feature flags on `dev` for `news-sharing` feature
> fix(condo) DOMA-7888 Restore changes lost on rebase :')

- .github/workflows/_nodejs.condo.cypress.yml
- .github/workflows/nodejs.condo.ci.yml
- yarn.lock
> ci(global): INFRA-361 allow CI to run from forks 🍴

- yarn.lock
and fixed personal account validation
> feat(spp): DOMA-9392 added route for spp online reconciliation

- packages/keystone/tasks.js
Also make extra logs adjustments and fixes)
> fix(condo): INFRA-338 split workers priorities

- apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
> fix(address-service): remove abort signal

- apps/condo/pages/ticket/index.tsx
> fix(condo): DOMA-9624 added ticket export button with selected tickets

- apps/condo/domains/user/components/UserOrganizationsList.tsx
- apps/condo/lang/en/en.json
- apps/condo/lang/ru/ru.json
> feat(condo): DOMA-9628 add field Inn to user component

- apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js
Previously we loaded objects via `Schema.getAll` - it loads objects with nested objects
Now it has been rewritten with use `itemsQuery` which loads only flat object without nesting
> hotfix(condo): DOMA-9645 fixed sending of news items

- apps/condo/domains/property/components/BasePropertyMapForm/index.tsx
- apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
- apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
- apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
- apps/condo/domains/property/utils/helpers.ts
https://github.com/open-condo-software/condo/assets/52532264/5f98bfea-f11c-4572-92c1-251635d1394d
> fix(condo): DOMA-9293 allow to create map with same unitName and different unitType

- apps/condo/domains/banking/schema/BankAccountReportTask.test.js
- apps/condo/domains/banking/tasks/generateReports.js
- apps/condo/domains/banking/utils/testSchema/bankAccount.js
- apps/condo/domains/banking/utils/testSchema/index.js
Problem: generating a report for bank account `A` changes the report for bank account `B`
> fix(condo): DOMA-9619 fixed generation of bank account reports

- apps/condo/domains/organization/integrations/sbbol/sync/MockSbbolResponses.js
- apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
> fix(condo): DOMA-9806 fixed importing of transactions

- packages/keystone/KSv5v6/v5/prepareKeystone.js
1. detect process id with
```bash
ps -ef|grep keystone
```
2. send signal
```bash
kill -SIGPIPE <pid>
```
3. go to pod's console
4. search for "Snapshot file URL:"
5. download file
> feat(condo): DOMA-9868 temporary ability to create heap snapshots

- yarn.lock
Added cache to routes:
- `payment/sum/period` and `billingReceipt/sum/period` – cache on 2 hours in redis and cache old (3-th period ago and older) payments and billingReceipts in s3. These routes will be called most often, therefore it was decided to cache them for longer
- `/ticket/count` - cache on 1 hour in redis
> feat(condo-restapi): DOMA-9821 added cache to routes in condo-restapi

- apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.spec.js
Test for the latest prodaction bug sending messages to wrong users
> fix(condo): DOMA-9882 test for sending news to the right resident

- apps/condo/domains/common/utils/serverSchema/index.js
> fix(condo): HOTFIX mark loadListByChunks as deprecated

- yarn.lock
Fix registry submodule to point to main branch
> feat(spp): DOMA-9793 added unzipper to packages

- apps/condo/index.js
- apps/condo/package.json
- bin/run-keystone-app.js
- package.json
- yarn.lock
We need to initialie it as early as possible
> fix(condo): DOMA-10096 move dd-trace to run-keystone-app.js

- apps/condo/domains/meter/components/Meters/ChangeMeterStatusModal.tsx
allow any date to be set to archiveDate field (on the client)
> feat(condo): DOMA-10194 remove disableDate for out of order meter

- packages/keystone/test.utils.js
> refactor(condo): remove useless __x_forwarder_for_header variable

- apps/condo/domains/billing/gql.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
- apps/condo/schema.graphql
- apps/condo/schema.ts
Will be needed to show users that information is current as of a specific date
> feat(condo): DOMA-10258 added "updatedAt" in ResidentBillingReceiptOutput

- apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
- apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
- apps/condo/k6/src/registerMetersReadings.test.ts
- apps/condo/k6/webpack.config.js
- moved meter and meter readings selects from for loop to top -> select it 1 time instead n
- wrote tests for case with duplicates in one input data
> feat(condo): INFRA-524 optimise register meters

- apps/miniapp/domains/condo/utils/serverSchema/index.js
Update `generateServerUtils` and server utils calls in submodules according to https://github.com/open-condo-software/condo/commit/9304f2205406280d0a8b19be81b670721a18d840
> feat(global): INFRA-587 update server side utils in miniapps

- .github/workflows/deploy_development.yaml
- .github/workflows/deploy_production.yaml
- .github/workflows/deploy_review.yaml
- .github/workflows/deploy_stage.yaml
- werf.yaml
> feat(meters-billing-integration): DOMA-10402 add infra configs

- yarn.lock
add cross-env for starting worker
> fix(meters-billing-integration): DOMA-10402 add default values for envs

- apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
https://github.com/user-attachments/assets/67f42db7-0fe7-47d5-ae14-cfce8f56346c
https://github.com/user-attachments/assets/fff86aa2-cce5-456f-ba87-79c776c3e898
> fix(condo): DOMA-5381 fixed layout rendering

- .gitignore
- apps/miniapp/condoSchema.graphql
- apps/miniapp/condoSchema.ts
- apps/miniapp/schema.graphql
Removed miniapp `schema.graphql` from .gitignore and run maketypes
> hotfix(miniapp): fix miniapp app error

- .github/workflows/nodejs.condo.k6.yml
- apps/condo/k6/src/news.test.ts
- apps/condo/k6/src/registerBillingReceipt.test.ts
- apps/condo/k6/src/registerBillingReceiptFile.test.ts
- apps/condo/k6/src/ticket.test.ts
- apps/condo/package.json
- yarn.lock
According to this article https://grafana.com/docs/k6/latest/using-k6-browser/migrating-to-k6-v0-52/
> fix(condo): INFRA-613 migrate to new k6 browser API

- apps/condo/domains/notification/adapters/hcm/messaging.js
- apps/condo/domains/notification/adapters/hcmAdapter.js
> DOMA-10501 Add more logs to debug huawei push problem

- apps/miniapp/bin/prepare.js
- packages/codegen/templates/app00/bin/prepare.js
- packages/codegen/templates/app01/bin/prepare.js
Use same logic as in others apps
> fix(condo): DOMA-10616 prepare should only create .env files

- bin/prepare.js
- packages/cli/index.js
It's a common practice to use highly random secrets, even during local development.
> refactor(condo): DOMA-10511 secrets should be randomly generated and ready for prod

- apps/condo/pages/service-provider-profile.tsx
> fix(condo): DOMA-10475 removed double page wrappers

- apps/condo/domains/user/access/User.js
- apps/condo/domains/user/schema/User.js
- apps/condo/domains/user/schema/User.test.js
- packages/keystone/KSv5v6/utils/graphqlCtx.js
- packages/keystone/KSv5v6/utils/resolvers.js
- packages/keystone/access.js
- packages/keystone/databaseAdapters/BalancingReplicaKnexAdapter/adapter.js
- packages/keystone/package.json
- yarn.lock
> feat(global): INFRA-650 restrict public access to User.name

- apps/dev-api/domains/user/access/User.js
- apps/dev-api/domains/user/schema/User.js
- apps/dev-api/domains/user/schema/User.test.js
- apps/miniapp/domains/user/access/User.js
- packages/codegen/templates/app00/domains/user/access/User.js
- packages/codegen/templates/app01/domains/user/access/User.js
> fix(global): INFRA-650 restrict access to User.name in miniapps

- packages/clients/address-service-client/AddressServiceClient.js
- packages/clients/package.json
- yarn.lock
to get more logs about who is going to address-service / and dadata or other system
> feat(clients): DOMA-10717 use open-condo fetch in addressServiceClient

- packages/ui/src/components/ActionBar/actionBar.tsx
- packages/ui/src/components/ActionBar/style.less
Hi, this should fix bottom affix **jumping** effect
https://github.com/user-attachments/assets/2467d7bf-dc11-4969-98d1-acdae256da87
https://github.com/user-attachments/assets/6910f9b4-48e0-40ff-8e36-edc4886d76fc
> chore(ui): fix ActionBar `jumping` when scrolling

- apps/condo/domains/miniapp/components/AppIndex/BillingAppPage.tsx
- apps/condo/pages/service-provider-profile.tsx
> fix(condo): Doma-10475 spp banners fix

- apps/condo/domains/common/utils/next/apollo.ts
> feat(condo): INFRA-717 added a request tracing

- apps/condo/package.json
- bin/prepare.js
- packages/keystone/crypto/EncryptionManager.js
- packages/keystone/package.json
- yarn.lock
Generate config in prepare.js for app
Add config in helm for condo
Fix secret key length checking
Fix dumb-passwords package location
> feat(global): DOMA-10642 encryption config

- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js
- apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
- apps/condo/domains/billing/utils/serverSchema/index.js
- apps/condo/domains/billing/utils/testSchema/mixins/acquiring.js
This reverts commit 7b9ab593650a1a57c207722ee168882baa93ff20.
> Revert "fix(condo): Duplicated payments temporary fix (#5523)"

- packages/keystone/crypto/keyDerivers/pbkdf2.js
> chore(keystone): DOMA-10642 remove console log 🤡

- apps/condo/domains/organization/components/OrganizationSelect.tsx
> fix(condo): DOMA-10768 fixed refething of OrganizationSelect

- apps/condo/domains/user/components/auth/AgreementText.tsx
- apps/condo/domains/user/components/auth/InputPhoneForm.tsx
- apps/condo/domains/user/components/auth/SignInForm.tsx
- apps/condo/lang/ru/ru.json
> chore(condo): DOMA-10785 add component with the text of the agreement + corrected ru translation

- packages/apollo/src/index.ts
**NOTE**: This is not breaking change, since a changes from https://github.com/open-condo-software/condo/pull/5566 was not delivered to NPM yet
> fix(apollo): remove unused export

- apps/condo/domains/meter/schema/RegisterMetersReadingsService.js
- apps/condo/domains/meter/schema/RegisterMetersReadingsService.test.js
> fix(condo): DOMA-9623 not set controlReadingsDate to current date

- apps/condo/domains/common/constants/featureflags.js
- apps/condo/domains/ticket/hooks/usePollTicketComments.tsx
- apps/condo/domains/ticket/queries/TicketComment.graphql
- apps/condo/domains/ticket/queries/TicketCommentFile.graphql
- apps/condo/gql/index.ts
- apps/condo/gql/operation.types.ts
return polling logic, add `first` to ticketComments and files queries
> fix(condo): DOMA-10792 fix ticket comments polling

- apps/condo/domains/property/utils/tables.utils.ts
fix removed the default value("flat")
> fix(condo): DOMA-10568 fix removed the default value("flat")

- apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
> fix(condo): DOMA add search by number

- apps/condo/domains/common/components/Snowfall/Snowfall.css
- apps/condo/domains/common/components/Snowfall/index.tsx
- apps/condo/domains/common/constants/featureflags.js
- apps/condo/next.config.js
- apps/condo/pages/_app.tsx
https://github.com/user-attachments/assets/2c7376a2-780c-40d0-adc5-54a692584931
> feat(condo): DOMA-10910 a touch of winter magic ❄️✨

- apps/condo/domains/common/utils/mutations.utils.ts
> fix(condo): DOMA-10960 show notification for errors with type equals TOO_MANY_REQUESTS

- .env.example
- apps/condo/lang/en/en.json
- apps/condo/lang/es/es.json
- apps/condo/lang/ru/ru.json
- packages/keystone/KSv5v6/v5/prepareKeystone.js
- packages/keystone/rateLimiting/constants.js
- packages/keystone/rateLimiting/plugin.js
> feat(global): INFRA-760 time to ban 🚷👮🏻‍♂️🛡️ 

- apps/condo/domains/ticket/components/TicketId/TicketUserInfoField.tsx
That's fix for issue - https://github.com/open-condo-software/condo/issues/5697
> fix(condo): INFRA-837 hide link from resident ticket[id] page if there is no resident

- apps/condo/domains/organization/components/DeleteEmployeeButtonWithReassignmentModel.tsx
This pr should allow you to delete employees
> hotfix(condo): add dv and sender for reassignment tickets

- packages/ui/src/components/Switch/index.ts
- packages/ui/src/components/Switch/style.less
- packages/ui/src/components/Switch/switch.tsx
- packages/ui/src/components/_utils/analytics.ts
- packages/ui/src/index.ts
- packages/ui/src/stories/Switch.stories.tsx
https://github.com/user-attachments/assets/0005279c-6995-467e-9ac3-539149c63500
[layouts](https://www.figma.com/design/Nbkug4IRM33sEyDuN0yO1C/UI-Kit-(web)?node-id=3356-6457&m=dev)
> feat(ui): DOMA-11097 added switch component

- apps/condo/domains/ticket/constants.js
- apps/condo/domains/ticket/schema/Ticket.test.js
> fix(condo): do not track deletedAt for ticketChange

- apps/condo/domains/resident/schema/RegisterResidentService.test.js
- apps/condo/domains/resident/tasks/residentTicket.task.js
- apps/condo/domains/resident/utils/helpers.js
`getAll` only retrieves the first 100 items, so I rewrote it using `find` and added a test.
> fix(condo): DOMA-10800 fix resident to property connections when there are more than 100 residents at the address

- apps/condo/domains/meter/schema/_internalDeleteMeterAndMeterReadingsService.test.js
- yarn.lock
The authentication process of the insurance service's external API was changed. This PR brings improvements to support the new authorization flow. Also, there are some common improvements for the oldest mini-app.
> chore(condo): DOMA-11152 make insurance mini-app working again

- apps/condo/domains/common/constants/featureflags.js
- apps/condo/domains/notification/components/UserMessagesList/MessageCard/MessageCard.css
- apps/condo/domains/notification/components/UserMessagesList/MessageCard/index.tsx
- apps/condo/domains/notification/components/UserMessagesList/UserMessagesList.css
- apps/condo/domains/notification/hooks/useNewMessageTitleNotification.ts
- apps/condo/lang/en/messages/PASS_TICKET_CREATED/default.njk
- apps/condo/lang/en/messages/PASS_TICKET_CREATED/telegram.html.njk
- apps/condo/lang/es/messages/PASS_TICKET_CREATED/default.njk
- apps/condo/lang/es/messages/PASS_TICKET_CREATED/telegram.html.njk
- apps/condo/lang/ru/messages/PASS_TICKET_CREATED/default.njk
- apps/condo/lang/ru/messages/PASS_TICKET_CREATED/telegram.html.njk
- apps/condo/pages/ticket/index.tsx
1) Disabled notification sound by default and use featureflag to manage it
2) Fixed message templates
3) Fixed notification card size in mobile screen
4) Fixed inline button text in pass ticket created message
> fix(condo): DOMA-11169 platform notifications fixes after testing

- apps/condo/domains/meter/tasks/importMeters.js
- apps/condo/domains/meter/tasks/importMeters.spec.js
- packages/keystone/file/ConvertFileToTable.js
- packages/keystone/file/constants.js
- packages/keystone/file/file-types/excel.js
- packages/keystone/file/utils.js
> fix(condo): DOMA-11189 added rows count limit exceeded error in meter readings import

- packages/keystone/fileAdapter/awsFileAdapter.js
Added comment same as in sberCloudFileAdapter to fix semgrep issue
> chore(keystone): added nosemgrep to aws files middleware

- apps/condo/domains/ticket/schema/PredictTicketClassificationService.js
> refactor(condo): log errors and return null instead of throwing exceptions

- apps/condo/domains/property/components/PropertyReportCard.tsx
- apps/condo/pages/property/[id]/index.tsx
This fixes the markup of Property Report Card component when Property report is active
> chore(condo): refactor PropertyReportCard.tsx

- apps/condo/domains/billing/schema/BillingReceipt.js
- apps/condo/domains/billing/schema/fields/AmountDistribution.js
- apps/condo/domains/marketplace/schema/Invoice.js
- apps/condo/domains/marketplace/schema/Invoice.test.js
- apps/condo/schema.graphql
Tests for creating invoice from service user
> chore(condo): DOMA-11283 improve bank requisites checking

- docs/contributing.md
Add Contributor License Agreement
> docs(contributing.md): Add Contributor License Agreement
