open-condo-software/condo

apps/condo/domains/billing/schema/BillingAccount.js
[JIRA TASK LINK](https://doma.atlassian.net/browse/SBERDOMA-296)
When creating BillingAccount on [test site](https://test3.dev.doma.ai/admin/graphiql) with mutation:
```
mutation {
createBillingAccount(data: {
dv: 1
sender: {
dv: 1
fingerprint: "test"
}
property:{
connect:{
id: "5d32c010-6c54-4029-84ff-c3eb8f142a58"
}
}
raw: {
foo: "bar"
}
globalId: "test"
number: "12345"
unitName: "flat_22"
meta: {
dv:1
foo: "bar"
}
context: {
connect: {
id: "e1d6753a-b7cc-456e-af48-1c06b343ca8c"
}
}
importId: "12345"
})
{
id
}
}
```
But instead of creating BillingAccount I get an errror:
```
"message": "You attempted to perform an invalid mutation",
"name": "ValidationFailureError",
"time_thrown": "2021-05-03T21:50:42.852Z",
"data": {
"messages": [
"[required:noValue:organization] Value is not set", …
```
=> fix/condo/SBERDOMA-296/fix billingAccount creation

apps/condo/domains/ticket/hooks/useTableColumns.tsx
Remove ellipses in the address column in the tickets list table. Maybe, we can change widths for other columns to display address more compact
=> SBERDOMA-353 Show full address text in tasks list table

apps/condo/domains/property/components/panels/Builder/MapConstructor.spec.ts, apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
1. When a unit is deleted from the building map - the next units will recalculate their labels
2. When no units remain on the floor - this floor will be deleted
=> Chessboard editor for building

apps/condo/domains/ticket/components/BaseTicketForm/ErrorsContainer.tsx, apps/condo/domains/ticket/components/BaseTicketForm/index.tsx, apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx, apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
On create/update ticket form, previously, `unitName` field was required.
Now, when "Address" field is filled in, next field set of a form will get unlocked.
=> Feature/condo/sberdoma 305/make unit name field not required in ticket

apps/condo/domains/common/utils/codegeneration/generate.test.utils.js
You can use `TESTS_LOG_FAKE_CLIENT_RESPONSE_ERRORS=true` env variable to display the errors!
=> remove useless console.log

apps/condo/domains/common/components/FocusContainer.ts, apps/condo/pages/ticket/[id]/index.tsx, apps/condo/pages/ticket/[id]/pdf.tsx
Changed unit check in ticketAddress computation in ticket view, so now null is not casted to string
Added word-wrap to ticket details and fixed max-width of its container to make it work with long-word type input
=> SBERDOMA-481 Fix ticket view

apps/condo/domains/common/components/PhoneInput.tsx, apps/condo/domains/contact/components/ContactsEditor/ContactSyncedAutocompleteFields.tsx
Now we have a masked `PhoneInput` in ContactsEditor.
Solved compatibility problem of `react-phone-input-2` with `AutoComplete` component from Ant.
Implemented interface which `AutoComplete` expects.
Detailed explanation is in https://doma.atlassian.net/browse/SBERDOMA-464
To see it in action, try to create a ticket.
=> SBERDOMA-464 used PhoneInput as a custom input for AutoComplete in ContactsEditor

apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Should be deployed ASAP, because contacts are not saved now.
=> Hotfix — SBERDOMA-566 fixed usage of `canCreateContact` return value of a `useContactsEditorHook`

apps/condo/pages/contact/index.tsx
For now contact profile page is not implemented, but we can redirect there from by clicking on rows from '/contact' page.
We need to disable this until future implementation, so:
1. Table rows were wrapped with tooltip as @dkoviazin asked
2. Disabled ability to be forwarded by clicking on table row
=> SBERDOMA-620 Removed ability to redirect to contact page

apps/condo/domains/common/components/DataImporter.tsx
We were displaying extra success message, when file "uploaded to process physically", even if data incorrect.
It was unclear for user to see "success" and "error" message at the same time, so
I removed "success on load" message and left only "success on proccessed"
=> SBERDOMA-529 Removed redundant message.success

apps/condo/lang/ru.json
Full name in russian usually have format  "Фамилия Имя Отчество", but was "Имя Отчество Фамилия"
=> SBERDOMA-557 Fix full name russian translation

apps/condo/domains/common/constants/errors.js, apps/condo/domains/contact/schema/Contact.js
Before we just moved email to lower case and this was it.
For now we accept only emptiness or emails that can be normalized.
And we are also changing their domains that can be duplicated (ya.ru -> yandex.ru, hotmail.co.uk -> outlook.com)
=> SBERDOMA-685 Added contact email normalization + validation

apps/condo/domains/common/components/BaseSearchInput/index.tsx, apps/condo/domains/ticket/components/BaseTicketForm/index.tsx, apps/condo/lang/en.json, apps/condo/lang/ru.json
When you try to set the address inside ticket (using Autocomplete from daData) you get strange flickering. More inside [JIRA ticket](https://doma.atlassian.net/browse/SBERDOMA-591)
Fixed a bug when you had strange 'flickering' when you tried to create or edit the ticket form:
I just used the default ant `notFoundContent` attribute, and enabled its support inside BaseSearchForm component
=> SBERDOMA-591 - Fix a bug when you got no results in Address search form

apps/condo/domains/common/components/Comments/Comment.tsx, apps/condo/domains/common/components/Comments/CommentForm.tsx
Disabling multiline (pressing enter now sends message), since Typography.Text (comment wrap) is not multiline anyway.
Max size and length of editable form are equal to comment input form to prevent big size of form
=> SBERDOMA-707 Comments input minor fixes

apps/condo/docs/migrations.md
Anyone, having following error by running `makemigrations`:
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
Do the following steps, described in docs.
=> SBERDOMA-776 documented solution of error by running makemigrations

apps/condo/domains/common/components/TicketCard/TicketCard.tsx, apps/condo/domains/common/components/TicketCard/TicketOverview.tsx, apps/condo/domains/contact/utils/clientSchema/Contact.ts, apps/condo/domains/organization/permissions.ts, apps/condo/lang/en.json, apps/condo/lang/ru.json, apps/condo/pages/contact/[id]/index.tsx, apps/condo/pages/contact/index.tsx
Added contact overview page.
Done: 
1. basic contact information (organisations can only see their own contacts)
2. contact's tickets board (only tickets to current organization, clicking on ticket causing opening ticket page, clicking on more opens /ticket page with correct filters)
Not done for now:
1. Ability to delete contact (softDelete is not ready yet as @toplenboren said)
2. Ability to edit contact (will do it later)
3. No "owner" label, since we cannot acquire this information yet
=> Sberdoma-592 Contact overview pages with all details

apps/condo/domains/common/components/BaseSearchInput/index.tsx, apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
It seems, like `autoFocus` does't not work property in Ant, when we reloading (or first loading) the page.
Created task SBERDOMA-832 for further research.
When we get into this page by redirecting on the client (clicking a next-link), — it works and it was fixed in this pull request for ticket form.
=> SBERDOMA-577 fixed focus on wrong field in ticket form

apps/condo/domains/common/components/BaseSearchInput/index.tsx, apps/condo/lang/en.json, apps/condo/lang/ru.json
We have a small problem with flashing dropdown on select. This problem was fixed in https://github.com/open-condo-software/condo/pull/298 but only for one single case. This PR provides a generic solution
Now if there are no entries the select wont blink, but instead show **Not Found** 
https://user-images.githubusercontent.com/33755274/126785992-8ef20af3-488c-4323-a940-13734ab82bae.mov
=> SBERDOMA-821 Add generic not found message

docker-compose.yml
> TypeError: getCookieSecret() call without cookieSecret (check the COOKIE_SECRET environment)
=> SBERDOMA-839 Fixed error with undefined `COOKIE_SECRET` in Docker `worker` service

apps/condo/index.js
When chessboard is too large - the system fails to process it. Keystone.js does not offer a trivial and reliable way to customize it
Create a custom middleware in which we explicitly set maximum body size to 100Mb
=> SBERDOMA-666 Create custom middleware for large JSON bodysizes

apps/condo/domains/common/components/containers/AuthRequired.tsx, apps/condo/domains/organization/components/OrganizationRequired.tsx, apps/condo/pages/_app.tsx, apps/condo/pages/analytics/index.tsx, apps/condo/pages/analytics/pdf.tsx, apps/condo/pages/contact/[id]/index.tsx, apps/condo/pages/contact/[id]/update.tsx, apps/condo/pages/contact/create.tsx, apps/condo/pages/contact/index.tsx, apps/condo/pages/employee/[id]/index.tsx, apps/condo/pages/employee/[id]/update.tsx, apps/condo/pages/employee/create.tsx, apps/condo/pages/employee/index.tsx, apps/condo/pages/index.tsx, apps/condo/pages/property/[id]/index.tsx, apps/condo/pages/property/[id]/update.tsx, apps/condo/pages/property/create.tsx, apps/condo/pages/property/index.tsx, apps/condo/pages/ticket/[id]/index.tsx, apps/condo/pages/ticket/[id]/pdf.tsx, apps/condo/pages/ticket/[id]/update.tsx, apps/condo/pages/ticket/create.tsx, apps/condo/pages/ticket/index.tsx, apps/condo/pages/user/index.tsx, apps/condo/pages/user/update.tsx
Before we used components such as `OrganizationRequired` (I call them access boundary components) right inside the page components.
This is bad for several reasons:
- Firstly, we make an extra render of the page and only after rendering show that access is denied.
- Secondly, this did not allow us to reuse our page components well, since they were dependent on the context of a particular access boundary component
Now we can use component field - `requiredAccess` instead.
=> SBERDOMA-925 add requiredAccess as Page Components prop

apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
Since adding "Comments" block, width of ticket content area was shrunk.
Added more space for datetime.
=> SBERDOMA-895 fixed wrapping of datetime in ticket changes

apps/condo/domains/common/components/Import/ModalConfigs.tsx
Before: buttons with long Russian translation didn't fit into default Antd modal
Now: fixed
=> SBERDOMA-759 Added custom width to partly success modal window

apps/condo/domains/common/utils/sberCloudFileAdapter.js
Display error if current .env OBS credentials do not have access to the bucket
=> SBERDOMA-653 Check access to bucket on file upload

apps/condo/domains/notification/schema/SendMessageService.test.js
Some times worker changed the status of the message immediately to "processing" so this test was failing ~ 1/10 times
=> SBERDOMA-818 Fix Resend message test

apps/condo/domains/resident/access/Resident.js, apps/condo/domains/resident/schema/Resident.test.js, packages/@core.keystone/access.js
Only soft-delete update-operation is allowed for resident.
Resident can now be updated from current user in session, which is equal to Resident's user.
=> Fix/condo/sberdoma 721/resident api fixes soft delete

apps/condo/domains/common/components/BaseSearchInput/index.tsx
if we did not pass onClear in BaseSearchInput, then an error occurred and the input field was not cleared
=> SBERDOMA-909 add onClear check in BaseSearchInput

apps/condo/pages/analytics/detail/report_by_tickets/index.tsx
=> SBERDOMA-999 - fix analytics page tabs default margin

apps/condo/domains/common/utils/sberCloudFileAdapter.js
Added fields to the context in ObsMiddleware. Without these fields, access didn't work for resident users, as we only have an id in access files
=> SBERDOMA-1038 Fix access to files for resident users

apps/condo/domains/resident/schema/RegisterResidentService.js, apps/condo/domains/resident/schema/RegisterResidentService.test.js
If resident gets soft-deleted and registered on the same address and unitName, `deletedAt` gets cleared.
=> SBERDOMA-1021 restore soft-deleted resident on subsequent register

apps/condo/domains/property/components/BasePropertyForm/index.tsx, apps/condo/domains/property/constants/property.ts, apps/condo/lang/en.json, apps/condo/lang/ru.json
1. add `'домовладение', 'сооружение', 'владение'` house types in validation. We do not have separate types for `гараж` and `паркинг`, they are of the `'дом'` type
2. remove settlement validation because we can have a house type from `1.` anywhere
**Data on which I tested:**
- поселок - Свердловская обл, Белоярский р-н, поселок Прохладный, ул Карла Маркса, д 2
- городской поселок - Ленинградская обл, Всеволожский р-н, гп Рахья, ул Гладкинская, д 15
- деревня - Орловская обл, Ливенский р-н, деревня Калинец, ул Фабричная, д 23
- село - г Екатеринбург, село Горный Щит, ул Бастионная, д 23
- поселок городского типа - Свердловская обл, пгт Рефтинский, ул Вишнёвая, д 12
- рабочий поселок - Новосибирская обл, рп Кольцово, ул Березовая, д 21
- квартал - Свердловская обл, г Карпинск, кв-л 13, д 12 …
=> Fix/condo/sberdoma 1032&sberdoma 1033/validate settlement and house types

apps/condo/migrations/20210823172647-0047_auto_20210823_1226.js
knex does not migrate as there is one logic error in migration:
I tell that `BillingReceipt.ImportId` should not be null and do not give any default value to it, but then tell that it should be not null!
Fix the migration file Itself. Truncate all rows first, and tell that `importId` should not be null later
=> SBERDOMA-1039 Fix migrations script (delpoy demo fail)

apps/condo/domains/property/components/BasePropertyForm/index.tsx, apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
**Reason for the bug:** Base Property Form did not have the specified width and was parted to the width of the content
**Before:** (we cannot scroll map on edit on create forms)
**After:** (we can scroll map on edit on create forms)
Also display `mapValidationError` only if it exist
=> SBERDOMA-902 fix scroll in property map

apps/condo/domains/common/utils/codegeneration/generate.hooks.ts
If on a form we set initial values and initializing create action in a following way:
```
const initialValues = {
// some fields
}
const handleComplete = () => {/* ... */}
const action = SomeSchema.useCreate(initialValues, handleComplete)
```
Then on executing this action, initial values will override actual form values.
Merging should be in opposite direction.
=> Fix/condo/sberdoma 1046/wrong data merging in use create client util

apps/condo/domains/common/utils/codegeneration/generate.hooks.ts, apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Reverted attrs merge order (changed in PR #478) back to strictly-set values instead of initial values
Added comment about intent of using `attrs` in `useCreate` client schema hook, since it's not clear as described in [710c7422](https://github.com/open-condo-software/condo/commit/710c74222c286576a36e75bcb448c7be75582b1a):
> The `source` attribute is being passed into `useCreate` hook as an attribute, that should pass unchanged into mutation input.
More of that, a value of `source` input hidden field is **missing** in form values ;)
Since we have `attrs` in `useCreate`, such hidden fields are redundant in forms.
=> Fix/condo/sberdoma 1046/revert wrong data merging in use create client util

apps/condo/domains/billing/utils/validation.utils.js
Our toPayDetails validators were wrong – we could not specify the total volume of the consumed service 
Fix validator!
=> SBERDOMA-1113 Add volume to validators

apps/condo/migrations/20210831103000-0050_manual_set_can_manage_divisions_to_administrator_organization_employee_roles.js
All administrator roles need this ability to be able to CRUD Divisions.
=> SBERDOMA-1116 migration to set `canManageDivisions` to administrator roles

apps/condo/domains/common/components/containers/GlobalStyle.tsx, apps/condo/domains/common/constants/style.js
Colors from Figma didn't match with antd Colors, that's why we were used to hard-code values / invent a bicycle
Fix colors in antd theme / global styles
=> SBERDOMA-1157 Added colors for antd typography.text + alert

apps/condo/domains/resident/schema/Resident.js, apps/condo/domains/resident/schema/Resident.test.js
When address is the same, but in upper case, resident record will be registered, but should not.
=> Fix/condo/sberdoma 1159/case insensitive check of address in register resident

apps/condo/domains/common/components/Table/Index.tsx
**Problem:** when we make a filter with checkboxes dropdown, then arrays are stored in `oldFilterValue` and `tableFilterValue` and comparison by `! ==` always gives true
=> DOMA-1165 fix common table filters bug

apps/condo/domains/organization/schema/OrganizationEmployeeRole.js, apps/condo/domains/ticket/components/BaseTicketForm/index.tsx, apps/condo/domains/ticket/hooks/useTicketAssignmentHook.tsx, apps/condo/domains/ticket/utils/clientSchema/search.ts
For `executor` field only those user are presented in options list, who has `canBeAssignedAsExecutor` ability.
For `assignee` field only those user are presented in options list, who has `canBeAssignedAsResponsible` ability.
=> Feature/condo/sberdoma 1134/ticket assignment logic changes

apps/condo/domains/division/components/BaseDivisionForm/index.tsx, apps/condo/domains/organization/constants/common.js, apps/condo/domains/organization/schema/RegisterNewOrganizationService.test.js, apps/condo/domains/ticket/utils/clientSchema/search.ts
As we discussed today on product case, `canBeAssignedAs…` abilities should have all newly created roles.
=> Feature/condo/doma 1222/set default role abilities can be assigned as

apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx, apps/condo/lang/en.json, apps/condo/lang/ru.json
When no divisions are set or no employees are assigned to classifier categories - Assign  select will contains all employees
=> DOMA-1239 Assign field behavior extend

apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx
Also, executor selection list is displayed in grouped mode only, when `techniciansOnDivisionOptions` and `techniciansOnOtherDivisionsOptions` are not empty.
Otherwise executor selection list is plain.
=> DOMA-1241 fixed unable to assign executors when no division exist

apps/condo/domains/resident/schema/RegisterServiceConsumerService.js, apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
Sometimes we get strange programmatic errors from `registerServiceConsumer` mutation
- `cannot read id of null` 
- `cannot read id of undefined`
Refactor the code a bit
=> DOMA-586 Make error handling more obvious

.github/workflows/deploy_develop.yaml, .github/workflows/deploy_production.yaml
Implementing new logic of deployment procedure:
You are still able to manually deploy to development environment from any branch, but an automatic deploy will trigger as well.
Manual deploy to production environment is banned. From here and so on one should tag a commit in order to automatically deploy it to production.
=> INFRA new logic of deploy actions

apps/condo/domains/organization/tasks/index.js, apps/condo/domains/organization/tasks/syncSbbolSubscriptions.js, apps/condo/index.js
Syncs new and cancelled subscriptions
In the future it will be migrated to Apache AirFlow to be able to track and collect logs separately for each scheduled job execution.
=> DOMA-1398 scheduled hourly sync of SBBOL subscriptions

apps/condo/pages/_app.tsx
Apollo Client caching wasn't working properly because of typo in GQL type name in it's config
=> DOMA-1396 GQL type name typo fix

apps/condo/domains/ticket/components/BaseTicketForm/index.tsx, apps/condo/lang/ru.json
Our `ticket/create` page had a typo in russian locale.
=> DOMA-1454 typo

apps/condo/pages/_app.tsx
We have a bug related to apollo cache and buldings sections/floors/untis.
I tried to update the ticket, which incorrectly displayed section and floor, and noticed that when updating unit section and floor take the wrong value.
Property map:
There is also a warning in the console
Disabled the cache for BuildingSection, BuildingFloor and BuildingUnit and the bug is gone
=> DOMA-1271 remove caching buildings fields

apps/condo/pages/reports/detail/report-by-tickets/index.tsx, apps/condo/pages/reports/detail/report-by-tickets/pdf.tsx
=> DOMA-1476 fix typo in line table data mapper

apps/condo/domains/contact/components/ContactsEditor/index.tsx
When we have >1000 contacts in the property, an error occurs about exceeding the server limit (1000 objects)
=> DOMA-1526 fetch contacts only for unit

apps/condo/domains/subscription/access/ServiceSubscription.js, apps/condo/domains/subscription/schema/ServiceSubscription.test.js
For an old organization, without trial subscriptions, we want to set it.
now, we add access for supports to create subscriptions in admin UI
Later we will make a script in /bin to set all subscriptions for old organizations
=> DOMA-1512 Support can create subscriptions

apps/condo/domains/common/components/GraphQlSearchInput.tsx, apps/condo/domains/common/components/ResidentActions/ResidentActions.tsx, apps/condo/domains/division/components/BaseDivisionForm/index.tsx, apps/condo/domains/user/components/UserMenu/MobileUserMenu.tsx, apps/condo/pages/division/create.tsx
By default, dropdown is triggered only on `hover`, on mobile devices it did not always work, added `click` trigger
=> DOMA-1634 add click trigger to dropdowns

apps/condo/domains/common/components/BaseSearchInput/index.tsx, apps/condo/domains/common/components/GraphQlSearchInput.tsx, apps/condo/domains/common/components/Table/Filters.tsx, apps/condo/domains/common/utils/select.utils.ts, apps/condo/domains/division/components/BaseDivisionForm/index.tsx, apps/condo/domains/meter/hooks/useFilters.tsx, apps/condo/domains/property/components/PropertyAddressSearchInput.tsx, apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx, apps/condo/domains/ticket/schema/Ticket.js, apps/condo/domains/ticket/utils/clientSchema/search.ts, apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js, apps/condo/pages/reports/detail/report-by-tickets/index.tsx
**Added infinity scrolling to property Select on:**
- Division form
- Ticket filters modal
- Meter filters modal
- Reports page
---
**Why is the scrolling logic in `GraphQLSearchInput` and `BaseSearchInput` repeated?**
Currently, `PropertyAddressSearchInput` and, in some places, `GraphqlSearchInput` are used to find `properties` in the organization. `PropertyAddressSearchInput` is based on `BaseSearchInput` and `GraphQLSearchInput` is based on antd `Select` component. Converting `GraphQLSearchInput` to `BaseSearchInput` is not a quick task and affects many of the components that use `GraphQLSearchInput`.
---
**Why is there no scroll on the `property/create` or `property/update` pages?**
Because the Dadata service can return a maximum 20 addresses per search and does not support …
=> DOMA-1517 infinity address select scrolling

apps/condo/domains/acquiring/constants/errors.js, apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.js, apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js, apps/condo/domains/organization/access/Organization.js
Problem: acquiring integration cannot create context for organization, which was created before (not by integration)
MVP Solution: give access to all organisations for read, which allows integration to create contexts, but it cannot create context, if another one is already created
=> DOMA-1653 Added ability for acquiring integration to create context for existing organizations

apps/condo/domains/common/components/BaseSearchInput/index.tsx, apps/condo/domains/common/components/GraphQlSearchInput.tsx, apps/condo/domains/common/components/Table/Filters.tsx, apps/condo/domains/common/components/Table/Index.tsx, apps/condo/domains/ticket/hooks/useTableColumns.tsx
1) Fixed the width of the columns in the control room on screens smaller than XXL
2) Fixed GQLSearchInput and inputs from columns dropdown that ate letters
3) Returned Typography.Title to children Select.Option GQLSearchInput, which disappeared after rebase (repaired here #866)
=> DOMA-1704 fixes after release

apps/condo/package.json, bin/prolong-subscription.js
A following script has been implemented, which sets "finishAt" to specified value for ServiceSubscription records,
which belonging to organizations with ids from specified file,
and which satisfies filtering conditions
Usage:
yarn workspace @app/condo subscription:prolong <type> <isTrial> <date> <finishAt> <filePathWithOrganizationIds>
<type>
Value for `ServiceSubscription.type` for filtering condition of records, that will be affected with this script
<isTrial>
Value for `ServiceSubscription.isTrial` for filtering condition of records, that will be affected with this scrip
<date>
New value of `ServiceSubscription.finishAt` for records, that will be affected with this script
<filePathWithOrganizationIds>
Path to file, that contains a list of organization ids, whose subscriptions should be …
=> Feature/condo/doma 1289/prolong subscriptions till 20211201 for some organizations

apps/condo/domains/billing/constants/errors.js, apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.js, apps/condo/domains/billing/schema/BillingIntegrationOrganizationContext.test.js
**Problem**: Integration option in case of no-option billing in test environment expected to be undefined, but front-end send it's as null, which is correct value too in this case, but it did not pass validations
**Solution**: Fix validation and add coverage test
=> DOMA-1727 Fix null integration option

apps/condo/domains/meter/schema/MeterReading.js, apps/condo/domains/meter/schema/MeterReading.test.js, apps/condo/domains/meter/utils/serverSchema/resolveHelpers.js, apps/condo/package.json, bin/fix-meter-readings-contacts.js
When `resident` sending a reading from a mobile application, no `contact` was attached and the `clientXXX` fields were not filled
=> DOMA-1729 create contact and fill client info in resident MeterReading

apps/condo/domains/common/constants/style.js, apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx, apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx, apps/condo/pages/property/[id]/index.tsx
=> Fix/condo/doma 1767/sticky floor axis

apps/condo/domains/organization/components/OrganizationSelect.tsx
if the employee belongs to a deleted organization, then the object will not contain organization and an error occurs during destructuring `{ value, label }`
=> DOMA-1781 fix organization select null option

apps/condo/domains/resident/constants.js
Payment categories for production returns an array with multiple items, while it should return an array with single item
Fix this!
=> DOMA-1876 Fix payment categories

apps/condo/domains/resident/schema/Resident.js, apps/condo/domains/resident/schema/Resident.test.js
It was a real case, when a user of mobile app was trying to register with given address and database had property with this address with last letter of building in upper case.
It was causing an error:
> Cannot connect property, because its address differs from address of resident
=> DOMA-1886 case insensitive address comparsion in `Resident.property.validateInput`

apps/condo/domains/organization/access/Organization.js, apps/condo/domains/organization/access/OrganizationEmployee.js, apps/condo/domains/organization/schema/Organization.test.js, apps/condo/domains/organization/schema/OrganizationEmployee.test.js, apps/condo/domains/user/access/User.js, packages/@core.keystone/access.js
In the mobile application, the user needs to understand that he has been deleted from the `organization`. To do this, i gave him the ability to read deleted `Employee` objects in which the user's `userId` matches the user's `userId`
=> DOMA-1739 add deleted employee access to read his Employee object

apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js, apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
We have an unhandled corner case
One receipt goes for Housing Payment, other one goes for Housing Maintenance fund (Фонд Капремонта)
You pay for housing receipt, then you pay for the housing maintenance receipt 
When getting AllResidentBillingReceipts you see that the field `paid` contains the sum of payments and equal for both receipts 
> So, in summary: You have two receipts with only difference being `toPay` and `recipient`, and Payments summed for these receipts!
Now, payments for two receipts are properly separated
AllResidentBillingReceipt might be slow
Use find, instead of getAll
=> DOMA-1790 & DOMA-1793 AllResidentBillingReceipts updates

apps/condo/domains/meter/schema/Meter.js, apps/condo/domains/meter/schema/Meter.test.js, apps/condo/domains/meter/schema/MeterReading.test.js, apps/condo/domains/meter/utils/serverSchema/index.js, apps/condo/domains/meter/utils/serverSchema/resolveHelpers.js
In the mobile application, requests for `meters` and `meter readings` take a very long time.
**Solution**
Use find, instead of getAll
=> DOMA-1882 replaced getAll for find in meter and meter reading acesses

apps/condo/lang/en.json, apps/condo/lang/ru.json
Changed translation of i18n key `pages.condo.property.index.TableField.UnitsCount` **affects `callcenter` app**.
=> DOMA-987 fixed wrong column name in properties table

apps/condo/admin-ui/index.js, apps/condo/index.js
AdminUi allows to override actions for list or single item. So we can extend actions for user and add SignInAs mutation call
I placed hooks to the root of condo app as different domains can extend admin UI
=> DOMA-2009 add signinas button to user item view in admin ui

apps/condo/domains/ticket/hooks/useTableColumns.tsx
=> DOMA-2013 adjust ticket table column size for small screens

apps/condo/domains/contact/components/ContactsEditor/index.tsx
The problem was that when searching for `contacts` in a `property` with `unitName: undefined`, all the `contacts` that are in that `property` are returned. If there are more than 1000 `contacts`, then the server limit per request is reached
=> DOMA-2108 used null instead undefined in unitName search

apps/condo/pages/auth/forgot.tsx
Changes the lock timeout on password restore to 60 seconds
Fixes DOMA-2021
=> DOMA-2021 change LOCK_TIMEOUT to SMS_CODE_TTL timeout

apps/condo/domains/common/components/Table/Index.tsx, apps/condo/pages/division/[id]/index.tsx
**BONUS**:
Added prop `shouldHidePaginationOnSinglePage` to Table component, to hide nav-bar....if result rows amount <= single page rows
=> [BUG 🐞] DOMA-1667 Pagination on division page was fixed

apps/condo/domains/organization/integrations/sbbol/sync/syncSubscriptions.spec.js, apps/condo/domains/resident/utils/helpers.js
A series of test cases was failing sometimes because of dates difference inspection was implemented in a way of comparing datetime representation of timestamps, cropped up to minute.
Replaced to inspecting a difference between timestamps in specified units.
In current cases we expect a difference in minutes to be zero, that means, that it not exceeds one minute.
=> Fix/condo/doma 2041/failed text sync subscription

apps/condo/domains/common/utils/serverSchema/changeTrackable.js
When we are trying to add a new field of type `Select` to Keystone `Ticket` schema (true for any schema), an util `makemigrations` will crash.
It crashes because we are picking not enough attributes from original field from `Ticket` to be able to programmatically create a corresponding field for `TicketChange` model (true for any model, that will hold trackable changes).
To verify correctness of this fix
1. Add a `unitType` field to `Ticket
```
unitType: {
schemaDoc: '',
type: Select,
options: ['flat', 'building', 'parking'],
dataType: 'string',
isRequired: true,
defaultValue: 'flat',
},
```
2. Run `yarn workspace @app/condo makemigrations`
3. Set default values in questions of util to `flat` (type `1` and `'flat'`)
A new migration should be created.
=> DOMA-2236 fixed crash of Keystone while `changeTrackable` module processed fields of type `Select`

apps/condo/domains/acquiring/schema/MultiPayment.js
1. Add Atol receipt integration
2. Fix Multipayment fee calculation check
3. Add success and fail urls to update payment status
4. Fix GetPaySplit to set attribute crb to Doma service and add bik for Doma recepient
=> DOMA-2240 Add Atol receipt service integration

apps/condo/domains/meter/utils/clientSchema/MeterReadingFilterTemplate.ts
Due to the fact that the `filters` field was specified in the clientSchema instead of `fields`, no meter reading filter fields were sent to the client
=> DOMA-2302 fixed FIELDS const in clientSchema

apps/condo/domains/common/components/HeaderActions.tsx, apps/condo/domains/user/components/auth/SignInForm.tsx, apps/condo/pages/auth/change-password.tsx, apps/condo/pages/auth/forgot.tsx, apps/condo/pages/auth/register.tsx, apps/condo/pages/auth/signin.tsx
Since a commit `6e88dab0` adds "LoginBySbbol" button to `ButtonHeaderActions` component, that is used in all pages from `auth`, it solves following tasks:
- DOMA-2016
- DOMA-2272
- DOMA-2273
=> Fix/condo/doma 2273/move sbbol button on auth layout to top

apps/condo/domains/contact/components/ContactsEditor/index.tsx
Problem:
When open ticket editor, it some times selects first contact in contacts list (often wrong contact)
Solution:
It is happens because of no contact data connected to ticket. So, we just disable first contact selection if no contact data provided
=> DOMA-2354 Remove default selection on first element if no contact

apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js, apps/condo/domains/organization/integrations/sbbol/utils/getOrganizationAccessToken.js
First store `clientSecret` in TokenSet for our partner organization of SBBOL
A record of `TokenSet` was created before automatic client secret refresh was implemented.
So, its field `cilentSecret` is blank yet and we need to store it first.
There is an error "wrong context argument: no executeGraphQL", belonging to `context`, returned from `const { keystone } = await getSchemaCtx('Organization')`.
The reason is to be found.
=> DOMA-1722 Fixes for refreshSbbolClientSecret

apps/condo/domains/common/utils/expressErrorHandler.js
`serialize-error` will pick only following properties: `message`, `locations`, `path`, `name`, `stack`
It's not enough, because critical information from GraphQL mutations is provided in `originalError` property
Before an error was looking like following:
```json
{
"level": 50,
"time": 1647447215062,
"pid": 28708,
"hostname": "MacBook-Pro-AntonAL.local",
"name": "graphql",
"reason": "expressErrorHandler",
"error":
{
"message": "You attempted to perform an invalid mutation",
"locations":
[],
"path":
[
"createUser"
],
"name": "GraphQLError",
"stack": "ValidationFailureError: You attempted to perform an invalid mutation\n    at HookManager._throwValidationFailure (…condo/node_modules/@keystonejs/keystone/lib/ListTypes/hooks.js:20:11)\n    at HookManager._validateHook …
```
=> DOMA-2425 added `originalError` to `expressErrorHandler`

apps/condo/domains/user/components/auth/InputPhoneForm.tsx
Before
After
Because of placing button inside checkbox label - antd styles affected on span inside a button
```css
.ant-checkbox-wrapper span {
position: relative;
bottom: 4px;
}
```
=> DOMA-2458 fix buttons position on registration screen

apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Since "details" field does not have a label to place star symbol into, a placeholder attribute is used for that
=> DOMA-2337 market details field as required with "*" symbol

apps/condo/domains/user/components/containers/PosterLayout.tsx
with a large width, the footer is not centered relative to the form
add textAlign: 'center'
=> HOTFIX fix text align for footer

.github/workflows/deploy_production.yaml
Having all tag names, that triggers deploy to production is dangerous, because it can trigger deploy of code from a branch, that was not intended to be deployed.
Tags can be used to mark some milestones, so it's important to distinguish kind of tags, that trigger deploy.
=> DOMA-2529 changed tag name pattern that triggers deploy to production

apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
When a resident returns an ticket to work, 3 fields are added to ticketChange (`statusReoependCounter`, `statusDisplayName`, `reviewValue`).
in this case, we need to display a record only about the change in `statusReopenedCounter`.
=> DOMA-2594 fixed display statusReopenedCounter and reviewValue in ticket changes

packages/@core.codegen/index.js
Before, it was crashing when using one-letter field names:
```shell
yarn workspace @app/condo createschema test.Test "v:Integer;"
```
```
Unknown filed signature "v:Integer"
```
=> DOMA-2595 error in util `createschema` with handling one-letter field names

apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
=> DOMA-2616 Extended filters popup

apps/condo/domains/organization/components/OrganizationRequired.tsx
- fixed sorting by organization and source
- fixed search by organization and date
- made meter reading columns wider
- fixed "select organization" message on refresh page
=> DOMA-2624 callcenter meter pages fixes

apps/condo/domains/subscription/schema/ServiceSubscription.test.js
Checking attributes fails because of race conditions.
Actually, this checking does not make sense, because we are testing reading ability only.
=> DOMA-2682 fix failed test of ServiceSubscription reading by admin

apps/condo/lang/en/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk, apps/condo/lang/ru/messages/MESSAGE_FORWARDED_TO_SUPPORT/email.njk
`default.njk` has been renamed to `email.njk` to ensure that this template will only be used for text emails. This allows us to use unescaped `text` inside templates.
=> DOMA-2710 disabled escaping for text emails

apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
=> DOMA-2532 remove unnecessary save button at edit parking form

apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx, apps/condo/domains/property/components/panels/Builder/BuildingPanelEdit.tsx
=> DOMA-2115 add responsive styles to unitType select control

apps/condo/domains/ticket/access/Ticket.js, apps/condo/domains/ticket/schema/Ticket.js, apps/condo/domains/ticket/utils/accessSchema.js, apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Older versions of the resident mobile app do not pass `unitType` to createTicket
=> DOMA-2743 setted flat unitType in resolvedData for resident ticket

apps/condo/pages/division/[id]/index.tsx
Problem: In division card we have links to executors, but doesn't have link to responsible employee
Solution: Add link
=> DOMA-2430 Add link to responsible employee

apps/condo/domains/ticket/schema/TicketComment.js, apps/condo/domains/ticket/schema/TicketComment.test.js
Older versions of the tech mobile app do not pass type to createTicketComment
Fill with default value 'organization'
=> DOMA-2759 setted 'organization' type to comment without type

apps/condo/domains/common/components/Import/Index.tsx
Problem: After loading data from excel file the last record doesn't shown during the page manual reload. It happens because of data doesn't refetching after upload (only refetching during upload because of parent rerender)
Solution: Add refetch after upload complete
=> DOMA-2704 Add refetching query on finish

apps/condo/domains/common/constants/regexps.js, apps/condo/domains/property/components/PropertyAddressSearchInput.tsx
Problem: 
Due to property searching in ticket creation, spaces in the end of search breaks all search. It happens of search work. It found exact match, so search breaks
Solution:
Split search request by splitters (space, dot, comma) and update search to found by words containing
=> DOMA-2581 Update search to fix spaces

packages/@core.keystone/cache.js
Remove exported `initCache` function, bc it doesnt need to be exported :)
=> Hotfix/remove initCache

apps/condo/domains/common/schema/fields.js, apps/condo/domains/notification/utils/testSchema/index.js
Mobile devices send their `deviceId` as sender.fingerprint, which is much longer than allowed 42 symbols, so fixed this issue.
=> DOMA-2860 increased allowed sender.fingerprint max length up to 256 symbols

apps/condo/domains/notification/schema/SyncDeviceService.js, apps/condo/domains/notification/schema/SyncDeviceService.test.js
This is needed because of collisions on unique `Message.pushToken` field, that occur because mobile applications moved from simple `deviceId` to `deviceId+suffix` format, and there would be collisions.
=> DOMA-2877 added clearing of previous usage of pushToken

.gitmodules
It does't used anymore.
Instead, webhooks of sales CRM are called directly from `apps/condo`, for example `pushOrganizationToSalesCRM`.
=> DOMA-2910 remove `apps/amocrm` service

apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
filterCategoryClassifier is used when filtering with a selection in the column heading drop-down menu. With the search postfix, it is used in the search input.
=> DOMA-2521 Added search by classifier via search input

apps/condo/pages/division/[id]/index.tsx
if the responsible employee was deleted - the department page was displayed incorrectly
=> DOMA-2968 fix division page display on master delete

.github/workflows/nodejs.condo.test.yml
When the build, the error "Error: File adapter is not configured. You need to check FILE_FIELD_ADAPTER and their configs" fell, so the FILE_FIELD_ADAPTER indication was added to the test config.
Here is the build test log:
https://github.com/open-condo-software/condo/runs/6449598063?check_suite_focus=true
=> INFRA Specified adapter for front build test

apps/condo/domains/contact/hooks/useTableColumns.tsx
=> DOMA-3040 display unitType prefix at contact table cell

apps/condo/domains/ticket/utils/serverSchema/analytics.helper.js
The selection of dates for display on the chart was made by the `enumerateDaysBetweenDates` function. The function receives the interval between which it is necessary to make a selection. The `lastDate` in the function sets the selection to the last date given the step (`day`/`week`) . If `lastDate` is set to `isoWeek(1)`, then everything beyond Tuesday will not fall into the interval. Dates come from query parameters and conversions to `enumerateDaysBetweenDates` are out of sync with the `GqlToKnexBaseAdapter` which is querying the data from the database. Therefore, the data comes for the period specified in the query parameters. Because no synchronization with `enumerateDaysBetweenDates` the selection is incorrectly grouped and the graph is drawn incorrectly.
Chart before: 
Chart after: …
=> DOMA-2447 fix date selection for `TicketAnaliticsReportService`

apps/condo/pages/reports/detail/report-by-tickets/index.tsx
After discussing the problem with the designers, it was decided to remove the element. A group of buttons performed some of the functions that the date picker has. Now only the date picker is left:
=> DOMA-2443 Remove a group of radio buttons for selecting a period

apps/condo/domains/ticket/hooks/useTableColumns.tsx
=> DOMA-3086 Center alignment of numbers on ticket page

apps/condo/domains/common/components/Comments/CommentForm.tsx, apps/condo/domains/common/components/MultipleFileUpload.tsx, apps/condo/domains/ticket/access/UserTicketCommentReadTime.js, apps/condo/domains/ticket/schema/TicketComment.js
the line `setCommentLength(editableComment.content.length)` threw an error if `content` = `null`
=> DOMA-2977 & DOMA-3089 fixed empty comment edit errors

apps/condo/bin/fix-tickets-contacts.js, apps/condo/domains/ticket/schema/Ticket.js, apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Previously, when creating a ticket by a resident, the contact was only created (if there is none), but not set in the `contact` field of the `ticket`.
Made a `contact` binding to the `tickets` created by the resident and made a script that sets the `contact` field for old `tickets`.
=> DOMA-3123 set contact field for resident tickets

apps/condo/domains/common/components/IFrame/IFrame.tsx, packages/@core.next/auth.jsx
To be sure that userLoading value passed to the context in the same time with `userData` we pass this value through `useEffect` as `userData`.
Also the new command for CondoBridge was added.
=> Feature/condo/doma 2902/send current user to iframe

apps/condo/domains/resident/tasks.js, apps/condo/domains/ticket/schema/Ticket.test.js, apps/condo/domains/ticket/utils/handlers.js, apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Employees of the management company should not see changes to the name/phone/email of the user account in the mobile application. The `clientName`, `clientPhone`, `clientEmail` fields should not be updated when a resident connects in the `client` field
=> DOMA-3145 update only client field on tiket client resident connection

apps/condo/domains/ticket/utils/helpers.spec.ts, apps/condo/domains/ticket/utils/helpers.ts, apps/condo/pages/reports/detail/report-by-tickets/index.tsx
Now if the `analyticsData` is empty, the upload buttons to Excel and printouts are not active. Previously, the `isEmpty` function from LoDash was used for validation. But since the array is filled with mock objects without ticket data, `isEmpty` returns `false` because it considers it not empty.
Now:
=> DOMA-2716 validation function  isEmptyAnalyticsData

apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
returned missing filter.
before:
after:
=> DOMA-3375 fix missing filterUnit

apps/condo/domains/common/utils/codegeneration/generate.test.utils.js
Really, we already have a JSON stringified error message inside the TestClientResponseError
=> HOTFIX generate.test.utils.js: remove useless legacy

apps/condo/domains/ticket/utils/helpers.ts, apps/condo/pages/ticket/[id]/index.tsx
The issue was to make a string for ticket deadline of format `1 day` (`en`) or `1 день` (`ru`) instead of `a day` (`en`) or `день` (`ru`).
=> DOMA-2207 helper deadline function for one day diff corrected

apps/condo/domains/organization/hooks/useOrganizationInvites.tsx
The problem was as follows: the user is shown all the invitations in the organization (which are available to him), then he accepts them and the name and phone number of the corresponding employees are renamed to the name and phone number of this user.
Technically, the problem was that in the `useOrganizationInvites` hook, sometimes the `user` from `useAuth` did not have time to load and the condition `{where: user ? { user: { id: user.id }, isAccepted: false, isRejected: false, isBlocked: false } : {} }` to get an `OrganizationEmployee`, it turned out as follows: `{where: {} }` - the user received all the OrganizationEmployee objects (for which he passed access rights).
The solution is to change the conditions for getting `OrganizationEmployee` to `{ where: { user: { id: user Id }, …
=> DOMA-3141 fixed where condition in useOrganizationInvites hook

apps/condo/pages/ticket/index.tsx
Data coming into a function is not always an array. Therefore, the filter count function does not work with such cases.
In this case, the button for clearing filters will be unavailable and the counter of applied filters is empty.
=> DOMA-3375 fixed `reduceNonEmpty` function

apps/condo/domains/meter/components/CreateMeterReadingsActionBar.tsx, apps/condo/domains/meter/components/ErrorsContainer.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
It was necessary to make sure that it was impossible to send the form without completed contacts.
Submit form button and Adding new meter button are inactive when contacts fields are empty.
New strings added to ErrorsContainer - "Phone" and "Full name".
=> Contact fields validation added on meter create page

apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js, apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
In case of single account, single recipient and multiple categories on 2 receipts we only output one `BillingReceipt`. Now we output both `BillingReceipts`
=> HOTFIX Fix bug on AllResidentBillingReceiptsSerivce 

apps/condo/domains/common/utils/serverSchema/export.js, apps/condo/domains/ticket/schema/TicketExportTask.js, apps/condo/domains/ticket/tasks/exportTicketsTask.js
Utilized `getFileMetaAfterChange` factory, that produces `afterChange` handler to set meta `{ id, listKey }` to ACL of SberCloudFileAdapter.
=> DOMA-3704 added `meta` to `file` field value of `TicketExportTask` for `FileAdapter` in case of `SberCloudFileAdapter`

apps/condo/domains/ticket/schema/Ticket.js, apps/condo/domains/ticket/schema/Ticket.test.js
To create a ticket for a resident in the technic application, first a `contact` must connect in the `connectContactToTicket` function, and then a resident `client` must be found for this `contact`
=> DOMA-3793 connected contact before connect resident client

apps/condo/domains/common/components/tasks/index.tsx, apps/condo/domains/common/components/tasks/storage/TasksCondoStorage.tsx, apps/condo/domains/common/components/tasks/storage/TasksLocalStorage.tsx, apps/condo/domains/common/utils/iframe.utils.ts, apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx, apps/condo/pages/_app.tsx
Filtering on backend is not enough because for User with `isAdmin` flag we need to:
- return all tasks in Keystone admin section
- return only his own tasks in "public" section
First commit is a refactoring.
The objective of this PR is in d81d9c1be7044f3cea8a0e91f7a409d5c76be160 commit
=> Fix/condo/doma 3099/added filtering processing tasks on frontend

apps/condo/domains/common/components/tasks/TaskProgress.tsx
=> HOTFIX change task holder position

apps/condo/domains/common/components/containers/GlobalStyle.tsx
other elements will be changed later when the UI kit is ready
before
after (Became more readable)
=> DOMA-3530 changed disabled input elements (input/select/picker)

apps/condo/domains/common/components/tasks/index.tsx, apps/condo/domains/common/components/tasks/storage/TasksCondoStorage.tsx, apps/condo/domains/common/components/tasks/storage/TasksLocalStorage.tsx, apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx, apps/condo/pages/_app.tsx
Prevents stucking with tasks, not completed for some reason, created in previous days
Open question about pivot point today/tomorrow, that arises an answer — why not to display tasks only in 24 hours.
From working schedule point of view it's better to relate on calendar rather then durations, so, an employee opens a page on the beginning of the day and he dont see stuck tasks from yesterday.
@sitozzz, take a look please, I've added `createdAt` field to `TaskRecord` type
=> DOMA-3825 display only today tasks

apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
If you try to remove executor from the ticket, it wont change :-) 
Check out the function that converts form state to mutation state, add an instruction that if executor is undefined, then we should change it! 
---------
https://user-images.githubusercontent.com/33755274/184546708-dbe61381-6b00-4927-b282-374e2a6b4ab1.mov
=> DOMA-3821 Set executor to null if it is undefined

apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
Category classifiers did not show in filter, because data loaded after component mount.
=> DOMA-3745 categoryClassifiers dep added to useMemo

apps/condo/domains/common/utils/serverSchema/setLocaleForKeystoneContext.js, apps/condo/domains/common/utils/serverSchema/setLocaleForKeystoneContext.test.js, apps/condo/domains/ticket/tasks/exportTicketsTask.js
A problem was in different locales used to translate `TicketStatus.name`, becaues of different execution contexts.
A dictionary of statuses `statusNames` that was passed to `_buildExportFile` template rendering function has used locale from `TicketExportTask`, which is a proper way, because it is a request of a user. But values from `TicketStatus.name` field of type `LocalizedText` vere trying to use locale of `context.req` which was undefined, because a GraphQL query was executed in worker, not in scope of HTTP-request. Therefore a locale was undefined and a fallback to `DEFAULT_LOCALE` was used.
So, I've created a new utility `setLocaleForKeystoneContext` for this kind of use cases which sets specified locale to execute GraphQL queries server-side without having an HTTP-request scope.
=> DOMA-3778 fixed wrong translation in `exportTicketTask`

apps/condo/domains/common/components/Tooltip.tsx
The design asked to make the display of tooltips on hover 2 times faster
=> DOMA-3887 reduced the mouseEnterDelay of the tooltip by 2 times

apps/condo/migrations/20220809093641-0164_ticket_deferreduntil_ticketchange_deferreduntilfrom_and_more.js, apps/condo/migrations/20220811180832-0165_messageorganizationblacklisthistoryrecord_and_more.js
Some migrations that alter big tables, such as Ticket fail due to `STATEMENT_TIMEOUT` being set to 10 seconds. 
For this cases we unset the timeout and then set it back after migration completes
=> HOTFIX: Add statement timeouts to 164 and 165 migrations

apps/condo/domains/billing/gql.js, apps/condo/domains/resident/gql.js, apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.js, apps/condo/domains/resident/tasks/sendBillingReceiptsAddedNotifications.spec.js
Got rid of connecting `BillingReceipt` items to `ServiceConsumer` via `BillingAccount.id`
Instead made connections via `BillingAccount.number:unitType:UnitName` in script sending push notifications on new billing receipts added.
=> DOMA-3965 fixed billing-receipt-added script logic and tests

apps/condo/domains/resident/schema/RegisterServiceConsumerService.js, apps/condo/domains/resident/schema/RegisterServiceConsumerService.test.js
If a management company has >100 properties, then this code is wrong:
```
allBillingAccounts = await BillingAccount.getAll(where: { contextId: ctxId, unitName: unitName })
correctBillingAccount = allBillingAccounts.filter(condition)
```
Problem is that `BillingAccount.getAll` is going to return no more then 100 entities. So if you happen have a common unitName, like 1, 2, or 29, and your management company is large (>100 properties) then you are unable register a serviceConsumer for yourself 
Use `accountNumber` in search 
- I removed the ability to register a serviceConsumer if globalId matches. We do not support this logic anywhere in the system
- I also added a comment on deprecated fields
=> HOTFIX: Support organization with >100 properties

apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
Removed the `resetField` and now, after `route.push`, in the case when something is changed, a `Prompt` appears that allows you to either cancel everything and leave, or save the changes.
And fix `Prompt` message
=> Fix/condo/doma 4011/added alert canceling edit ticket

apps/condo/domains/common/utils/serverSchema/export.js, apps/condo/domains/common/utils/serverSchema/export.spec.js
Fixed calculation of `offset` in `loadRecordsAndConvertToFileRows` of `export` module
Tests for `loadRecordsAndConvertToFileRows` function from `export` module
Fixed missing interpolation in value of `extensions.message` field of `GQLError`
=> Fix/condo/doma 3800/fixes and tests for export

apps/condo/domains/common/utils/sberCloudFileAdapter.js, apps/condo/domains/ticket/components/TicketId/TicketFileList.tsx
Changes will occur in 2 iterations to avoid any unforeseen issues.
Step 1 - checking new functionality for unclaimed file types (.svg or .html).
Step 2 - Adding all required file types.
---
Problem: In the case of a redirect according to the scheme: A --request--> B --redirect--> C, it is impossible to read the response to the request.
Solution: when adding the "-no-redirect" header, the redirect link to the file comes in json format and a second request is made to get the file. Thus, the scheme now looks like this: A --request(1)--> B + A --request(2)--> C
=> DOMA-3163 fix downloading files in ticket view (step 1)

apps/condo/bin/lib/prompt.js, apps/condo/bin/notification/send-custom-message-batch.js, apps/condo/domains/notification/constants/constants.js, apps/condo/domains/notification/gql.js, apps/condo/domains/notification/schema/SendMessageService.js, apps/condo/lang/en/en.json, apps/condo/lang/en/messages/CUSTOM_CONTENT_MESSAGE/default.njk, apps/condo/lang/en/messages/CUSTOM_CONTENT_MESSAGE/push.njk, apps/condo/lang/en/messages/CUSTOM_CONTENT_MESSAGE/sms.njk, apps/condo/lang/ru/messages/CUSTOM_CONTENT_MESSAGE/default.njk, apps/condo/lang/ru/messages/CUSTOM_CONTENT_MESSAGE/push.njk, apps/condo/lang/ru/messages/CUSTOM_CONTENT_MESSAGE/sms.njk, apps/condo/lang/ru/ru.json, apps/condo/schema.ts
- Added new message type that allows to send arbitrary title/message
- Added function that allows to input text via keyboard within script execution, supports both single and multi line text input, including copy/pasting.
- Added script that allows to send custom message to arbitrary recipients list (user ids, phone numbers, emails - could be mixed)
- For each recipient detects transport type and handles it properly
=> DOMA-3874 added CUSTOM_CONTEXT_MESSAGE with templates, added script

apps/condo/pages/contact/index.tsx, apps/condo/pages/meter/index.tsx
=> DOMA-4026 fix flattened import buttons on contact and meter page

apps/condo/domains/ticket/utils/unit.js
In `property->map->parking` `sectionType` is stored as `'section'` . When creating a ticket, the `sectionType` field is filled in as `parking`. Therefore, when using `res.sectionType = section.type` , the value will always be `'section'` and will be displayed as a `section`. This logic is only called when creating a ticket as a resident
linked pr: https://github.com/open-condo-software/condo/pull/2133
before: 
After:
=> DOMA-3964 fix parking label for resident ticket

apps/condo/domains/common/components/BaseSearchInput/index.tsx, apps/condo/domains/common/hooks/useValidations.ts, apps/condo/domains/contact/components/CreateContactForm.tsx, apps/condo/domains/contact/components/ErrorsContainer.tsx, apps/condo/domains/meter/components/CreateMeterReadingsActionBar.tsx, apps/condo/domains/meter/components/CreateMeterReadingsForm.tsx, apps/condo/domains/meter/components/ErrorsContainer.tsx, apps/condo/domains/property/components/AddressSuggestionsSearchInput.tsx, apps/condo/domains/property/components/BasePropertyForm/index.tsx, apps/condo/domains/property/components/BasePropertyForm/usePropertyValidations.tsx, apps/condo/domains/property/components/PropertyAddressSearchInput.tsx, apps/condo/domains/ticket/components/BaseTicketForm/ErrorsContainer.tsx, apps/condo/domains/ticket/components/BaseTicketForm/index.tsx, apps/condo/domains/ticket/components/TicketForm/CreateTicketForm.tsx, apps/condo/domains/ticket/components/TicketForm/UpdateTicketForm.tsx
Added validation of the address selection field, which checks whether the selected property matches what is entered in the input. If different, the input returns false and the validation is processed. There is a check for an empty input, then the error is not displayed.
=> DOMA 4021 Add address field validation

apps/condo/pages/onboarding.tsx
In some cases user may not have a connected `OnBoarding` record, like after invite with creating new `User` in `InviteNewOrganizationEmployeeService`
So, when no `OnBoarding` record is connected, redirect from this page
=> DOMA-2883 added condition on missing `OnBoarding` for redirect

apps/condo/domains/common/components/Table/Filters.tsx
Now after clearing the filter in the dropdown it will close. The filter for the date, `getDateRangeFilterDropdown` will also close after the date is selected.
=> chore(condo): DOMA-4133 close dropdown after clear filter

apps/condo/domains/ticket/hooks/useTableColumns.tsx, apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Before: Sorting tickets by client name does not work. 
The column 'client name' did not have a sort key
After: The required key for sorting is set and sorting by client name works
=> fix(condo): DOMA-4135 fixed sort tickets by client name

apps/condo/domains/common/components/containers/BaseLayout/components/styles.ts
=> fix(condo): DOMA-4183 wrap words at PageHeader component

apps/condo/domains/billing/components/ServicesModal.tsx
Before - always FLAT
After - Depending on unitType
=> fix(condo): DOMA-3886 fix unitType display

apps/condo/domains/user/oidc/configuration.js, apps/condo/domains/user/schema/_oidc.test.js, packages/keystone/setup.utils.js
In order to make session cookie available we set sameSite='none' for keystone's session cookie. The same was performed for short-term oidc cookies.
=> fix(condo): DOMA-4253 Cookies settings were tuned

apps/condo/domains/property/hooks/useImporterFunctions.tsx
Do not import other houses instead of the non-existing one.
If a house with a non-existent address is found in the import file, the most similar address from dadata is returned to it. In this case, a check will be performed on what is entered in the imported file and what is returned from dadata, if it differs, null will be returned and the error 'The building with the given address was not found in the address database' will occur
=> DOMA-2628 added check suggested property with entered address

apps/condo/pages/employee/index.tsx
the permissions function can be used like `canManageEmployee(organizationLink, OrganizationEmployee)`
or extract access from a role. I chose the second option because it seems more readable in the code
=> DOMA-3579 fix displaying create employee btn. Wrong access use

apps/condo/domains/contact/hooks/useImporterFunctions.tsx, apps/condo/domains/meter/hooks/useImporterFunction.ts, apps/condo/domains/property/hooks/useImporterFunctions.tsx
When you change the organization, the import occurs in the previous one. This is because the organizationId is not being used from the function scope, causing the organizationId to not be updated. Solution: use useRef so that the function always has access to the current organization id
=> DOMA-3529 fix import after changing organization

apps/condo/domains/common/utils/serverSchema/changeTrackable.js, apps/condo/domains/ticket/tasks/index.js, apps/condo/domains/ticket/tasks/reopenDeferredTickets.js, apps/condo/domains/ticket/tasks/reopenDeferredTickets.spec.js, apps/condo/jest.setupSpec.js
If the employee from the ticket is not in the organization, then it will be reset
The asynchronous function call has also been fixed. Sometimes this issue prevented TicketChange from being created
=> fix(condo): DOMA-4113 fixed deleted assignee and executor if auto reopen ticket

apps/condo/pages/employee/index.tsx
`userOrganization` came undefined and because of this the request was sent without `where:{organization: id}`
therefore, all employees came from all organizations to which the user has access
=> fix(condo): DOMA-4307 fix get organization id

apps/condo/domains/common/components/Pickers/DateRangePicker.tsx
Problem: users can not clear dates in DateRangePicker components. 
Solution: added this option
=> fix(condo): DOMA-3734 fixed clearing fields for RangePicker

apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx
Problem: user can save ticket filter template with empty name or spaces on the sides. 
Solution: trim spaces in template name before saving
=> fix(condo): DOMA-2760 fixed filter template saving with empty name or spaces on the sides

apps/condo/domains/common/components/Table/Filters.tsx
Problem: if select filter in modal ticket filter for field "unitName" then in opened dropdown filter for column "unitName" field is empty. 
Also if select dropdown filters with field type "string" and reload page then this fields will be empty, but filters will apply.
Solution: dropdown filters with field type "string" was have own state for value, but it must take value from props
=> fix(condo): DOMA-4220 fixed dropdown filters with string field

apps/condo/domains/division/constants.js, apps/condo/domains/division/schema/Division.js
A client has appeared who needs to create divisions with 250 properties.
Previously, a maximum of 150 properties was set based on the maximum value of properties in division at that time
=> chore(condo): DOMA-4316 increased max properties in the division

apps/condo/domains/property/components/panels/Builder/BuildingPanelCommon.tsx
Fix description intl id generation of empty state at 'edit' mode
Before:
After:
=> DOMA-4317 added display mode to intl description of BuildingEmptyBlock

apps/condo/domains/common/components/TableFilter.tsx, apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx
Problems 1: users cannot save filter template if it have `unitName`. 
Solution 1: 'unitName' field should be string array, but was just string. 
Problem 2: if press `Enter` in dropdown filter, then will change sort by for this column. 
Solution 2: stop propagation `onKeyDown` for these dropdown filters containers
=> fix(condo): DOMA-4332 fixed template filter saving with unitName

apps/condo/domains/ticket/components/TicketId/TicketAssigneeField.tsx, apps/condo/domains/ticket/schema/Ticket.js, apps/condo/domains/ticket/schema/Ticket.test.js, apps/condo/domains/ticket/utils/serverSchema/resolveHelpers.js
Before: assignee and executor after reopen ticket not reset 
After: if employee is blocked or is deleted, then it reset from assignee or executor
=> fix(condo): DOMA-4309 added check assignee and executor after reopen ticket

apps/condo/index.js
Trying to prevent occasional down of production pods.
=> fix(condo): DOMA-4336 use expressErrorHandler to catch unhandled errors

apps/condo/cypress/objects/Ticket.js, apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx, apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, apps/condo/pages/meter/index.tsx, apps/condo/pages/ticket/index.tsx
Problem: selected template was reset because MultipleFiltersModal was re-renders. 
Solution: use useMemo instead of useCallback
Some changes: 
1. Also wrong template order - `New template` should be first.
2. Was selected first loaded template, should `New Template` or applied template. 
3. Was added label and placeholder in filed for changing template name
4. Change layout for TabPane
Before:
After:
=> fix(condo): DOMA-4222 fixed selected template in modal filter. 

apps/condo/domains/ticket/hooks/useModalFilterClassifiers.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
Problem: if loading in FilterModalBaseClassifierSelect then was show empty input
Solution: was added loading label and disabled input if it load data
Before: 
After:
=> fix(condo): DOMA-2995 fixed loading for FilterModalBaseClassifierSelect

apps/condo/lang/en/messages/DIRTY_INVITE_NEW_EMPLOYEE/default.njk, apps/condo/lang/en/messages/INVITE_NEW_EMPLOYEE/default.njk, apps/condo/lang/ru/messages/DIRTY_INVITE_NEW_EMPLOYEE/default.njk, apps/condo/lang/ru/messages/INVITE_NEW_EMPLOYEE/default.njk
Employee invitation message is too long and takes up to 3 SMS messages. We tried to shorten it but keep still informative.
=> fix(condo): DOMA-4369 shortened invitation message

apps/condo/domains/ticket/components/TicketPropertyHint/SettingsContent.tsx, apps/condo/domains/ticket/components/TicketPropertyHint/TicketPropertyHintContent.tsx, apps/condo/domains/ticket/hooks/useTicketPropertyHintTableColumns.tsx
After the design review, it was decided to remove the ellipsis after ticket property hint content
=>  DOMA-3889 removed ellipsis from ticket hint content

packages/featureflags/featureToggleManager.js
An error occurs in `FeatureFlagsContext` when parsing a response in json, if this response is `undefined`
**Solution:** return an empty object in cases when we can't get feature flags
=> fix(condo): DOMA-4388 fixed parse empty response with feature flags

apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx, apps/condo/domains/common/components/GraphQlSearchInput/Renders.tsx, apps/condo/domains/common/components/GraphQlSearchInput/index.ts, apps/condo/domains/division/components/BaseDivisionForm/index.tsx, apps/condo/domains/ticket/components/BaseTicketForm/TicketAssignments.tsx, apps/condo/domains/ticket/utils/clientSchema/search.ts, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
Problem: users can selecting blocked employees
Resolve: users can changed blocked employees.  And added mark `(blocked)`
Before:
After:
in divisions just like in tickets
=> fix(condo): DOMA-2678 blocked employees are hidden from select

apps/condo/domains/common/components/containers/FormList.tsx, apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
Changed submit and save logic for modal filters.
Added error and scrolling to field for 'template name'. 
Removed disabling 'save and submit' button. 
Before: if invalid template name then disabling "save and submit" button
After: if click "save and submit" button and template name is invalid then scrolling to field "template name" and showing error "it's field is required, bla-bla-bla..."
=> fix(condo): DOMA-4112 changed submit and save logic for modal filters

apps/condo/pages/settings/hint/[id]/index.tsx
Displaying only the address of the property in the property hint id page, even if there is property name
**Before:**
**After:**
=> fix(condo): DOMA-4261 fix property hint address render

apps/condo/pages/ticket/index.tsx
In the call center, we need to wait for the `relatedOrganizations` request, which are forwarded to the `baseQuery`.
If this is not done, then `ticketsWithoutFilters` will initially be empty and a stub will be displayed.
=> fix(condo): DOMA-4231 added baseQueryLoading prop to TicketPageContent

apps/condo/domains/common/utils/text.js, apps/condo/domains/common/utils/text.spec.js
Problem: We used to process ticket description text with `normalizeText`. And it util add space after each punctuation if it not exist. 
So, emails and urls would be broken. For example `Hey, here is my email: example@domain.com` -> `example@domain. com`
Solution: It could not be done with just modifying existing regex pattern, so my suggestion is add 'immutable tokens', that should be ignored in some cases
=> DOMA-3541 ignore emails and links at normalizeText util

apps/condo/domains/common/hooks/useNotificationMessages.tsx, apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx, apps/condo/domains/ticket/components/TicketOrganizationDeadline/TicketDeadlineSettingsForm.tsx, apps/condo/domains/ticket/components/TicketStatusSelect.tsx
changed successful change notification after changing ticket status. 
And some refactoring with using `useNotificationMessages`
Before: 
After:
=> fix(condo): DOMA-3764 fixed successful change notification.

apps/condo/pages/_app.tsx
Added access check for links in the sidebar. If an organization is not selected - all links will be visible, but all will be inactive until the user selects an organization. Some accesses are not described in the role. For example, `canReadB2BApps`. If there is no access in the role, the link will be displayed
P.S.: git displayed the diff a little awkwardly
=> DOMA-4406 access check for side menu links

apps/condo/domains/acquiring/components/payments/PaymentsTable.tsx, apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx, apps/condo/pages/meter/index.tsx, apps/condo/pages/ticket/index.tsx
Problems: 
- was reseted selected templates,
- incorrect operation of filter reset
Solution: 
- 'MultipleFilterContextProvider' saving selected filters template without passing props (It doesn't cause unnecessary rendering)
- Reverting "MultipleFiltersModal" to "useCallback" allows the display of "MultipleFiltersModal" to properly update when visibility changes
=> fix(condo): DOMA-4416 fixed multiple filter modal

apps/condo/domains/contact/components/ContactsEditor/ContactSyncedAutocompleteFields.tsx
=> fix(condo): DOMA-2285 fixed option keys in contact editor

apps/condo/domains/common/components/BaseSearchInput/index.tsx, packages/next/organization.jsx
If you click on the address selector before the related organizations are loaded, then the properties in search function will not be found.
Made property select disabled before the related organizations are loaded.
=> DOMA-4487 fix empty address select in ticket and meter forms in callcenter

apps/condo/domains/property/components/AddressSuggestionsSearchInput.tsx, apps/condo/domains/property/components/BasePropertyForm/index.tsx
Problem:
During property creation, we get some validation errors, like "It doesn't look like a house address" or "Select address from the list". While error is showing, we can't add property. But validation errors are not consistent! Error can be set in one place and reset in another. It causes that error "It doesn't look like a house address" is reseted by "Select address from the list", because address is selected.
Solution:
Add check to validation error. It can be reseted only in the place, where it was setted
=> Fix/condo/doma 4224/fix address validation

apps/condo/domains/common/components/Table/Filters.tsx
Problem: When the filter in the modal is changed, the value in the dropdown list may not have the selected element data loaded and will just show the id.
Solution: To overcome this, the dropdown filter with "GraphQlSearchInput" will be intentionally added and removed so that the actual data is loaded
=> fix(condo): DOMA-4333 fixed updating values in getGQLSelectFilterDropdown

apps/condo/domains/ticket/components/TicketPropertyHint/BaseTicketPropertyHintForm.tsx
Problem: cant find property if property selected in current hint (or was selected and then unselected)
=> fix(condo): DOMA-3725 fixed search property on hint editing page

apps/condo/domains/user/components/containers/styles.tsx
=> HOTFIX fix auth layout

apps/condo/domains/property/components/panels/Builder/MapConstructor.ts, apps/condo/domains/property/components/panels/Builder/forms/ParkingUnitForm.tsx, apps/condo/domains/property/components/panels/Builder/forms/UnitForm.tsx
I set the name for the `unit` only if the `unit.label` cannot be converted to a number.
Removed validation in the `unit` change popup. She remained only while maintaining the chessboard
=> DOMA-4507 fix map constructor

apps/condo/domains/organization/constants/common.js, apps/condo/migrations/20221101131455-0182_manual_organizationemployeerole_canreadbillingreceipts_change_to_manager.js
Extension of manager accesses to be able to read connected billings
=> DOMA-4406 manual migration canReadBillingReceipts = true to Manager role

apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx, apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx, apps/condo/domains/ticket/utils/clientSchema/search.ts, apps/condo/domains/ticket/utils/tables.utils.ts, packages/keystone/cache.js
1. Displaying the same properties and executors in divisions table (all as in the last created one)
**Problem:** Requests for m2m fields (`properties`, `executors`) are executed without `args` and get into the same value in the cache.
**Solution:** Added a parent object id (ex `Division`) to request key, thus such values will fall into different cache values.
2. Tickets are not filtered by properties in divisions.
**Solution:** Added `keyFiled` to `GQLSearchInput` so that options with the same values are not removed from the select by the `uniqBy` condition
=> DOMA-4438 fix display division properties and executors

apps/condo/domains/common/components/ExportToExcelActionBar.tsx, apps/condo/domains/ticket/schema/TicketExportTask.js, apps/condo/pages/meter/index.tsx, apps/condo/pages/ticket/index.tsx
Problem: When exporting tickets, the time zone is not transmitted. 
Solution: `timeZoneFromUser ` --> `timeZone `
Also, callcenter app, the time in exported tickets and meters must be in the MSK time zone
=> fix(condo): DOMA-4522 fixed timezone in tickets and meters export

apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
**Problem**: When set `editMod` to `null` inside `removeSection`, the function `removePreviewSection` was called inside which `removeSection` was called and thus the functions called each other endlessly.
**Solution**: changed set `editMode` to set `mode`
=> DOMA-4557 fix cyclic function call

apps/condo/bin/fix-tickets-status-updated-at.js
Problem: some tickets are not closed automatically. This is because "statusUpdatedAt" is null.
Solution: set "statusUpdatedAt" on these tickets based on the creation date of the corresponding TicketChange
PS Such tickets appeared all the time until October 17, 2022 (Auto-generation of the "statusUpdatedAt" field appeared in release 2.8.0 on October 17, 2022)
=> chore(condo): DOMA-4552 added script for broken tickets statusUpdatedAt

apps/condo/domains/onboarding/components/OnBoardingContext.tsx, apps/condo/domains/onboarding/constants.js
Added two new items to the onboarding menu: `Billing` and `Acquiring`. They become available only after the creation of the `organization`. `Billing` redirects to the billing page, and `Acquiring` to the payments page. This will only be available for new organizations.
=> DOMA-4543 billing and acquiring to onBoarding steps

apps/condo/migrations/20221101131455-0182_manual_organizationemployeerole_canreadbillingreceipts_change_to_manager.js, apps/condo/migrations/20221102124530-0183_manual_organizationemployeerole_canreadpayments_change_to_manager.js
needed so that the next migrations are generated with the correct number
=> HOTFIX added number of migration into start manual migration file

apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
Before deleting `sections`, I create a copy of it and pass it to the function of recalculating serial numbers. It is impossible to make the correct logic when deleting a `sections` without creating a copy of the remote `sections`. Both the correct `index` and the name are lost.
=> DOMA-4566 fix remove section

apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx, apps/condo/pages/ticket/index.tsx
Added analytics on the use of filters. Data is sent only when filtering is applied. 
You can specify the fields for which you need detailed statistics. (no default)
You can find out which filters are used most often.
Also for some filters there are statistics on the selected values. Only those filters are taken, the values of which are unchanged (except for classifiers)
=> feat(condo): DOMA-4585 added analytics to MultipleFiltersModal

apps/condo/cypress/objects/Property.ts, apps/condo/domains/property/components/panels/Builder/MapConstructor.ts
When remove last section/parking from property map `viewMode` will not changed.
After:
https://user-images.githubusercontent.com/25844927/201318372-f0a0dda2-a319-408d-b930-873ed3225a47.mov
Before:
https://user-images.githubusercontent.com/25844927/201318548-174bcdde-ad67-4565-a558-0c16c429e598.mov
=> DOMA-4630 reset property map viewMode on section remove

renovate.json
This may be a possible solution of broken PRs generated by renovate bot
=> chore(global): add renovate permission to clone submodules

apps/condo/cypress/tsconfig.json, apps/condo/tsconfig.json
Problem: cypress v10^ comes with chai types, that conflicts with jest `assert` module
Solution: exclude cypress config from app
Ref: https://github.com/cypress-io/cypress/issues/22059
=> chore(condo): exclude cypress chai types from tsconfig

apps/condo/domains/division/components/DivisionsTable.tsx
there was no cross in the search field in divisions section
add cross to clear search field in divisions section
=> fix(condo): DOMA-4631 add cross to clear search field

apps/condo/domains/user/components/containers/PosterLayout.tsx
on small screens recaptcha overlapped sbbol button
now recaptcha doesn't overlap
=> fix(condo): DOMA-4633 make recaptcha doesn't block sbbol button

apps/condo/pages/meter/index.tsx
filters button doesn't show how many filters are applied before
now when you apply filters there is a reset button and the number of applied filters is shown
=> fix(condo): DOMA-4492 add number of applied filters and reset button

apps/address-service/package.json, packages/codegen/templates/app00/package.json, yarn.lock
This PR fixes critical vulnerability related with `immer` package version < 9.0.6
https://github.com/open-condo-software/condo/security/dependabot/62
=> DOMA-4728 update immer

apps/condo/domains/user/constants/errors.js, apps/condo/domains/user/schema/ConfirmPhoneActionService.js, apps/condo/domains/user/utils/serverSchema/guards.js, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, apps/condo/schema.graphql, apps/condo/schema.ts
There is no way to pass keystone context to `RedisGuard` instance, that required for extracting user locale and get human-readable errors. So I added this param to required methods
=> DOMA-4657 add messageForUser to user TOO_MANY_REQUESTS error

apps/condo/domains/common/constants/featureflags.js, apps/condo/domains/ticket/tasks/closeCompletedTickets.js, apps/condo/domains/ticket/tasks/closeCompletedTickets.spec.js, apps/condo/domains/ticket/tasks/index.js, packages/featureflags/FeatureFlagsContext.tsx, packages/featureflags/featureToggleManager.js
Problem: Mobile apps can take a long time to download a large number of updated tickets.
Solution: Therefore, you should limit updating tickets for each organization at one time if there are a lot of them.
With the help of the feature flag, you can manage this restriction.
Also:  added the ability to get the value of the feature flag
=> fix(condo): DOMA-4703 fix ticket close task

apps/address-service/domains/common/utils/addressKeyUtils.js, apps/address-service/domains/common/utils/addressKeyUtils.spec.js
- Remove `№` from address parts. For example `тер Коллективный сад № 1 (поселок Большой Исток)`
- Remove symbols `|`, `<`, `>`, `~`
- Also, test was improved
=> feat(address-service): DOMA-3580 Address key generator improved

apps/condo/domains/ticket/hooks/useStatusTransitions.ts
Problem: `getPossibleStatuses` function takes only 4 arguments
=> fix(condo): DOMA-4667 remove unused code

apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
Circular dependency caused a following error:
> TypeError: getSbbolSecretStorage is not a function at changeClientSecret (/app/apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js:13:32)
=> fix(condo): DOMA-4798 error in changeClientSecret invoked from `refreshSbbolClientSecret`

apps/address-service/domains/address/schema/AddressInjection.js, apps/address-service/domains/common/constants/contexts.js, apps/address-service/domains/common/utils/services/InjectionsSeeker.js
1. Ask dadata to return addresses with houses numbers
2. Keep words length 3+ symbols during injections searching
=> fix(address-service): DOMA-4797 Import improvements

apps/condo/bin/sbbol/credentials.js, apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js
Used for inspection of stored values in case when there is no direct access to Redis
=> feat(condo): DOMA-4798 implemented `get` command for sbbol/credentials.js util

apps/condo/domains/billing/components/ServicesModal.tsx
if a receipt's services filed is `null` or `[]` then receipt modal won't appear on receipt click
=> fix(condo): DOMA-4793 don't show receipt modal if no services

apps/address-service/domains/address/constants.js, apps/address-service/domains/address/schema/AddressInjection.js, apps/address-service/domains/common/utils/services/InjectionsSeeker.js, apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js, packages/keystone/plugins/addressService.js
Creating and searching of keywords was unified and both use same regexp to replace special symbols.
=> fix(address-service): DOMA-4822 fix property import

packages/ui/src/components/Markdown/style.less, packages/ui/src/components/style/mixins/table.less
table in the markdown used to look nothing like the table
now it looks like a table because of the addition of basic table styles into ui kit mixins
=> fix(ui): DOMA-4653 add basic table styles to ui kit mixins

apps/condo/domains/ticket/schema/Ticket.js
In the case there is no `status` field during ticket creation
Newly created ticket (1538) is at the bottom of the tickets list
Newly created ticket (1539, 1542) is at the top
=> fix(condo): DOMA-4940 fix order calculation

yarn.lock
`@keystonejs/app-admin-ui` updated to ^7.5.0 within insurance's package.json, so some old packages were removed from yarn.lock file
=> Fix/insurance/doma 4987/fix admin interface

apps/condo/domains/common/hooks/useDownloadFileFromServer.ts
Problem: the function of downloading files from the server worked only for the sbercloud file adapter, which uses a redirect.
If you use a local file adapter, then there is no redirect. Lack of redirect resulted in file download error. 
Solution: if there is a link for a redirect, then use the redirect and then download the file. If there is no redirect, then immediately download the file
=> fix(condo): DOMA-4998 fix files download without redirect url

packages/ui/src/components/Markdown/style.less
=> fix(ui): DOMA-5035 added bottom margin to first header in markdown

apps/condo/bin/sbbol/credentials.js, apps/condo/bin/sbbol/crypto.js, apps/condo/domains/organization/integrations/sbbol/SbbolFintechApi.js, apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js, apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.spec.js, apps/condo/domains/organization/integrations/sbbol/sync/index.js, apps/condo/domains/organization/integrations/sbbol/sync/syncTokens.js, apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js, apps/condo/domains/organization/integrations/sbbol/utils/getOrganizationAccessToken.js
**accessToken needs to be stored for the current user, not for our organization.**
Previously, we did not request any other information about the authorized user after he was authorized. Now it is necessary to receive transactions and extended data on the client's organization through the SBBOL Fintech API in the cron task format.
=> DOMA-4658 feat user scoped access and refresh SBBOL tokens

apps/condo/domains/common/components/tasks/TaskProgress.tsx
Some fixes to match layouts. Refactoring of icon changing logic. Found strange behavior when using gradients in css or the `@emotion` bug. The icon switch logic has been rewritten from css styles to use a react state and a chain of condition checks.
**After:**
**Before:**
=> DOMA-3960 fix layout task progress bar

apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js, apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
Now if Management company changes its billing integration context users will get error (when trying to pay for receipts)
`BillingReceipt with id "{receiptId}" does not have common BillingAccount with specified ServiceConsumer with id "{serviceConsumerId}`
This PR address this issue.
=> Let resident pay for receipts if management company changes billing integration context

packages/ui/src/components/Checkbox/style.less
importing checkboxes into condo from ui kit breaks checkmarks and reduces the size of the checkbox
now it's fixed and when you import it, it looks like in the storybook
=> fix(ui): DOMA-5085 fix checkboxes checkmark on import

apps/condo/domains/contact/components/ContactsEditor/index.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
Removed warning that a contact will not be created when creating/updating a ticket or meter. 
Now when adding a new contact to the ticket, it is created in any case, so should to remove this warning
=> fix(condo): DOMA-4674 removed warning in contact editor

apps/condo/domains/common/components/PhoneInput.tsx, apps/condo/domains/common/hooks/useSearchByPhoneModal.tsx
**Problem:** For operators, the number is copied in the format 7xxxxxxxxxx. Each time they erase +7 and insert a number. 
**Solution:** Removed `+7` prefix.
**Before:**
**After:**
=> fix(condo): DOMA-5101 added showCountryPrefix prop to PhoneInput

apps/condo/domains/common/components/PostMessageProvider/Provider.tsx, apps/condo/domains/common/components/PostMessageProvider/errors.ts, apps/condo/domains/common/components/PostMessageProvider/index.ts, apps/condo/domains/common/components/PostMessageProvider/types.ts, apps/condo/domains/common/components/PostMessageProvider/validators.ts, apps/condo/pages/_app.tsx, apps/condo/tsconfig.json, packages/bridge/src/promisify.ts, packages/bridge/src/types/bridge.ts
`PostMessageProvider` is unified hub, which goal is to process all incoming messages from different sources and manage different handlers in single  place.
- Analytics events from UI-components inside condo
- Analytics events from miniapps sent via UI-kit
- All bridge events
- By default allowedOrigins is only current `serverUrl`, you can add any trusted source by using `registerOrigin` on component (iFrame) mounting, and removing it `resetOrigin` on unmounting
- You can register local handlers for this origin....For example events, affecting state such as Window resizing
- You can also register global handlers by specifying `"*"`origin... Example: processing notifications somewhere else, or processing analytic events inside analytics context
No need to stack all handlers inside Global or …
=> feat(DOMA-5106): unified postMessage provider

.github/workflows/nodejs.apps.build.yml
That's handle case, when keystone build ends with 0 code, but actually not create a `dist` directory with result static files
More information about this case you can find [here](https://github.com/keystonejs/keystone/issues/4339)
=> ci(global): properly check for keystone build successful

apps/condo/pages/property/index.tsx
Call `getServerSideProps` inside page component will cause nextjs to create json file with all query results and block user render until it's done. This is an unnecessary action, so just remove it from code)
=> DOMA-5097 remove force upload ssr props

apps/condo/domains/contact/utils/clientCard.tsx, apps/condo/pages/phone/[number]/index.tsx
If the contact's property is deleted, then such a contact does not need to be displayed in the search by phone modal or in the contact card
=> fix(condo): DOMA-5130 filter contacts with deleted property in contact card

apps/condo/domains/common/utils/filters.utils.ts
removed icon in tag select filter dropdown
<details>
<summary><h3>Before</h3></summary>
</details>
<details>
<summary><h3>After</h3></summary>
</details>
=> fix(condo): DOMA-5077 fixed tag select filter dropdown icon

apps/condo/domains/common/components/Comments/index.tsx, apps/condo/pages/ticket/[id]/index.tsx
Problem: usedesk widget does not allow clicking on file upload button
<details>
<summary><h3>Before</h3></summary>
</details>
<details>
<summary><h3>After</h3></summary>
</details>
=> fix(condo): DOMA-4947 fixed ticket layout

apps/address-service/domains/common/utils/services/search/plugins/SearchByFiasId.js, apps/address-service/domains/common/utils/services/search/plugins/index.js, apps/address-service/domains/common/utils/services/search/providers/DadataSearchProvider.js, apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js, apps/address-service/index.js
An ability to search houses by fias id.
For now, the plugin will return only houses. Streets and cities will be ignored.
=> Feat/address service/doma-4706/search by fiasid

apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
=> fix(address-service): DOMA-5199 add space before sending query to dadata

apps/condo/domains/contact/components/ContactsEditor/index.tsx
**Problem:** if user click on minus button in contact editor form, then first contact will be setted in `selectedContact` state, but not in `value` state => when submitting the form, the value from the manually typed contact is sent
**Solution:** use `triggerOnChange`, which updates also `value`
=> fix(condo): DOMA-5181 set first contact value on minus click

apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.js, apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js
Refactoring that removes the ability to work with deleted entities in order to avoid possible errors and update the code.
If you delete a user who had an sbbol account, and then log into the system through sbbol authorization, you will get an infinite page 500 renderer, because the further code does not see these entities. So that such errors would not be repeated, I refactored using the same utilities as in the further part of the system.
=> refactor(condo): DOMA-5149 refactoring syncOrganization in SBBOL integration

apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Before: comment indicator is hidden under checkbox
After: comment indicator visible on the side of the table
=> fix(condo): DOMA-5055 fixed unread resident comments indicator

apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js, apps/condo/domains/organization/integrations/sbbol/utils/getAccessTokenForUser.js
The `keyStorage.ttl` asynchronous function without `await` returns a `Promise` in the `pending` state. Therefore, the logic for `getAccessTokenForUser` did not work correctly and could not update the `accessToken`
=> DOMA-5209 fix isExpired method in SbbolSecretStorage

apps/condo/domains/ticket/hooks/useTicketTableFilters.tsx, apps/condo/domains/ticket/utils/tables.utils.ts
Now the search works only by `clientName`.
Made it to be searched for by `contact.name`, if there is a `contact`
=> fix(condo): DOMA-5207 search tickets by contact name

apps/condo/domains/common/hooks/useDownloadFileFromServer.ts, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
If it was not possible to automatically download file (svg|html|htm|xml|txt) in the current tab,
then instead of notifying about an error, open a new tab with link on this file
=> fix(condo): DOMA-5219 fixed downloading files

apps/condo/domains/organization/integrations/sbbol/SbbolSecretStorage.js, apps/condo/domains/organization/integrations/sbbol/sync/index.js, apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js
To regularly update clientSecret, we created an SBBOL account in our organization and decided to use it for service purposes.
=> DOMA-1722 use serviceUser for updating clientSecret

apps/condo/domains/organization/integrations/sbbol/sync/syncOrganization.spec.js, apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js, apps/condo/domains/organization/integrations/sbbol/sync/syncUser.spec.js
The `gql.js` `registerNewUserService` does not have a `phone` and `email`. Therefore, after creating a new `user`, the instance returns without the required `phone` and `email` fields. And, when a custom organization registration mutation is performed, the created `employee` does not have a `phone` and `email`, since the transferred `user` instance was received without them
=> DOMA-5243 fix sbbol employee creation

apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.js, apps/condo/domains/billing/schema/AllResidentBillingReceiptsService.test.js
Get all receipts in a single query, 
This was made to add support for first, sortBy for a case with multiple billing accounts / multiple service consumers
=> Rewrite AllResidentBillingReceiptService.

apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
if there are no receipts, datapicker will show current month
=> fix(condo): DOMA-5168 fixed incorrect datapicker on empty lastReport

apps/condo/pages/phone/[number]/index.tsx
When opening a card on a call, a card is opened without the selected address.
Made it so that the first address is selected.
=> fix(condo): DOMA-5259 open first contact address if no activeTab

apps/condo/pages/phone/[number]/index.tsx
Hid the link "Show all tickets for this property" and the table with tickets for the property if no address was selected.
Before:
After:
=> fix(condo): DOMA-5273 hide property data if no selected address in contact card

apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.js, apps/condo/domains/acquiring/schema/RegisterMultiPaymentService.test.js
In case we have different commissions for different categories inside one acquiringIntegrationContext 
For example, organization have implicitFee on housing category and explicit fee for overhaul category
=> fix(condo): DOMA-5268 register multipayment for payments with different fees

apps/condo/domains/common/components/PhoneInput.tsx
**Before:**
https://user-images.githubusercontent.com/52532264/217920235-950a84e1-7cd5-48b5-9b07-ebf088c9ec12.mov
**After:**
https://user-images.githubusercontent.com/52532264/217920593-da28820e-d2ff-4df2-9923-4ca44228d0f6.mov
=> fix(condo): DOMA-5107 fixed onMouseDown in case of using ReactPhoneInput in AutoComplete

apps/condo/domains/common/components/containers/GlobalStyle.tsx, apps/condo/domains/miniapp/components/AppDescription/TopCard.tsx
done that when you click on miniapps carousel arrow buttons correspond to layout and were adaptive
adaptive behaviour
=> fix(condo): DOMA-5068 increased arrow buttons miniapps carousel

apps/condo/domains/common/components/LayoutContext.tsx, apps/condo/domains/common/components/containers/BaseLayout/BaseLayout.tsx
The current solution to the problem (adding a `hasSider` prop for the `Layout`) breaks opening pages that are not in the browser cache - they open with a blink (https://jira.in.doma.ai/browse/DOMA-5339).
So far, we decided to roll back the task so as not to delay the release
=> Revert DOMA-5339 task

packages/keystone/package.json, packages/keystone/schema.js, yarn.lock
Hide useless debug output:
```
Transform Organization GQLListSchema by preprocessors
✔ schemaDocPreprocessor
✔ escapeSearchPreprocessor
Transform OrganizationEmployeeHistoryRecord GQLListSchema by preprocessors
✔ schemaDocPreprocessor
✔ escapeSearchPreprocessor
Transform OrganizationEmployee GQLListSchema by preprocessors
✔ schemaDocPreprocessor
✔ escapeSearchPreprocessor
Transform OrganizationEmployeeRoleHistoryRecord GQLListSchema by preprocessors
✔ schemaDocPreprocessor
✔ escapeSearchPreprocessor
```
=> use debug package instead of hardcoded env checks

apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx, apps/condo/domains/billing/components/ServicesModal.tsx, apps/condo/domains/billing/hooks/useServicesTableColumns.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
minor UX fixes in services modal of a receipt:
- changed TotalCharged column name
- added category info
- added period info
- fixed incorrect unit type
=> fix(condo): DOMA-3292 services modal ux fixes

apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js
If the user has already been imported, then when finding it by `UserExternalIdentity`, only its `id` is returned instead of the entity instance
=> DOMA-5432 return User instance instead user.id

packages/ui/src/components/Radio/radiogroup.tsx, packages/ui/src/components/Radio/style.less, packages/ui/src/stories/Radio/RadioGroup.stories.tsx
Need for https://github.com/open-condo-software/condo/pull/2821
Simple `RadioGroup` does not work.
Only list with `RadioGrop`s
Simple `RadioGroup` does work.
And list too
=> fix(ui): DOMA-5408 fixed RadioGroup component

apps/condo/domains/common/utils/cors.utils.js, apps/condo/domains/common/utils/cors.utils.spec.js, apps/condo/index.js
npm module cors do not support wildcards - only regexps in origin settings
so, I added wildcard to regexp convert util, as we want to store cors settings in JSON env field
=> hotfix(condo): DOMA-5439 added wildcard support to cors

apps/condo/domains/common/components/Comments/Comment.tsx
if comment was not updated then should not show title with text "updated"
=> fix(condo): DOMA-5431 fixed comment datetime title

apps/condo/domains/billing/gql.js, apps/condo/domains/billing/schema/BillingReceipt.test.js, apps/condo/domains/billing/schema/fields/BillingReceipt/ToPayDetailsField.js, apps/condo/schema.graphql, apps/condo/schema.ts
Added paid field to billing receipt details
in this field will be stored information from billings about already paid amount of the receipt
in GIS - it is paidCache field
in KV24 - it is a sum of payments 
This field will be displayed in receipts table and on mobile device
field formula is not a required field now (because, this field is not used)
=> Doma-3904 paid field in billing receipt details

.dockerignore, .env.example, Dockerfile, docker-compose.yml
So, to simplify CI and local development we need to build one docker container for all apps. 
It's after then build container every app and easier for local development.
=> Remove useless `Dockerfile` args and simplify `docker-compose.yml`

apps/condo/domains/common/components/antd/Select.tsx
Problem: component TagsSelect does not send event to amplitude because `option` is empty
Solution: get selected value from `value`
=> fix(condo): DOMA-5456 fixed tracking for Select with mode "tags" 

apps/condo/domains/user/schema/ResetUserService.js, apps/condo/domains/user/schema/ResetUserService.test.js, apps/condo/schema.graphql, apps/condo/schema.ts
When an employee is fired `resetUser` mutation is used and the user’s name is erased. 
It is important for other employees to know who made the changes to the ticket, so we will delete the username only if the user requests.
=> refactor(condo): DOMA-5201 added deleteName param to resetUser mutation

apps/condo/domains/organization/hooks/useCreateOrganizationModalForm.tsx
Just prevent an empty name. ASAP (as simple as possible) If someone wanna use special symbols, it's up to him.
https://user-images.githubusercontent.com/25384290/225225883-e3e8e78d-4d22-49e0-bd13-fb8cf619bdc8.mov
https://user-images.githubusercontent.com/25384290/225225941-7969392d-57d9-4b6f-be47-6a6c07089dae.mov
=> fix(condo): DOMA-2668 Prevent empty organization name

apps/condo/domains/common/components/ChangeHistory/index.tsx, apps/condo/domains/ticket/schema/Incident.js, apps/condo/pages/incident/[id]/index.tsx
Also: 
- fixed blinking on incident page when update status;
- fixed blinking loading indicator in change history when update
https://user-images.githubusercontent.com/56914444/225356906-8d31e889-53bb-406d-b2c7-80c96b9483e9.mov
https://user-images.githubusercontent.com/56914444/225356942-86c0b855-b0fe-4642-80e7-b275cf054024.mov
=> fix(condo): DOMA-5532 fixed resetting field "textForResident" in incident

apps/condo/package.json, yarn.lock
Support had a problem with not be able to add a mobile number that starts with +7835
=> chore(deps): DOMA-5407 updated package "phone" to v3.1.36

apps/condo/domains/ticket/schema/TicketChange.test.js
Sometimes `unitName1` and `unitName2` are generated the same and `TicketChange` is not created
=> fix(condo): DOMA-5619 fix case when unitName1 and unitName2 are same

apps/condo/domains/notification/adapters/hcm/constants.js, apps/condo/domains/resident/gql.js, apps/condo/domains/resident/schema/Resident.test.js, apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
- add deeplink to account creation form for billing receipt notifications to residents without accounts
- added foreground_show setting for huawei pushes
=> feat(condo): DOMA-5021 add deeplink to account creation form 

apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx
BEFORE:
on page refresh period wasnt't set from period filter query
NOW:
we check if there is period in filter query and if so -- set it
=> fix(condo): DOMA-5698 fixed wrong period on billing page refresh

apps/condo/domains/contact/schema/Contact.js, apps/condo/domains/contact/schema/Contact.test.js, apps/condo/domains/meter/schema/MeterReading.js, apps/condo/domains/meter/schema/MeterReading.test.js, apps/condo/domains/meter/utils/serverSchema/resolveHelpers.js
There was an error creating a contact if there was already contact with the same `phone`, `property`, `unitName`, but other `unitType`
=> fix(condo): DOMA-5614 fix meterReading contact connection

packages/ui/src/components/_utils/hooks/useBreakpoints.tsx
`breakpoints` in ssr = {}, so the mobile layout was opened first.
Returned the same logic as when `breakpoints` from ant (first opens desktop layout)
=> fix(condo): DOMA-5838 fix isSmall variable

apps/condo/domains/common/components/EmptyListView.tsx, apps/condo/pages/ticket/index.tsx
Removed the filtering buttons if there are no tickets.
Aligned EmptyListView in the center. 
Changed the import button to the same as on other screens
**Before:**
**After:**
=> fix(condo): DOMA-6048 fix empty tickets layout

apps/condo/domains/banking/hooks/useCategoryModal.tsx, apps/condo/domains/common/hooks/useMultipleFiltersModal.tsx, apps/condo/lang/en/en.json, packages/ui/src/components/Modal/modal.tsx, packages/ui/src/components/Modal/style.less, packages/ui/src/stories/Modal.stories.tsx
Some of the components implements logic of use all of the parent container space (for example, tabs). But modal can't handle component like that.
Examples going below
Before:
After:
=> DOMA-5893 add fixedContentWidth prop to Modal component

apps/condo/domains/acquiring/access/AcquiringIntegrationContext.js, apps/condo/domains/acquiring/schema/AcquiringIntegrationContext.test.js
For self service billing and spp we need employee to choose and save fee settings
so if acquiring context do not have status Finished - we allow employee to update it
=> DOMA-6058 allow employee to update acquiring context

apps/condo/domains/notification/templates.js
if you put substituteTranslations(...) like this: 
1. if isObject(item) => return A
2. if isArray(item) => return B
then the 2 will never be executed, since typeof [] === 'object' in JS.
=> fix(condo) HOTFIX: fix email translation function in templates.js

apps/condo/domains/meter/hooks/useUpdateMeterModal.tsx
Problem: when employee from callcenter updates meter then user's organization is used. Because of this, field validation in the form worked incorrectly and skipped invalid values
Solution: now using organization from current meter
=> fix(condo): DOMA-5588 fixed validation for meter number in useUpdateMeterModal

apps/condo/pages/employee/[id]/index.tsx
chore(condo): DOMA-5905 removed unused import
Problem: specialization not display on employee page **in callcenter**
=> fix(condo): DOMA-5905 fixed specialization display on employee page in callcenter

apps/condo/domains/common/components/Table/Renders.tsx
Problem: Incorrect display of readings if different tariffs are used
Before:
After:
=> fix(condo): DOMA-5494 fixed meter table rendering

apps/condo/domains/contact/utils/serverSchema/index.js
Problem: column `isVerified` when exporting contacts is always with the value `No`
=> fix(condo): DOMA-6177 fixed export contacts

apps/condo/domains/user/components/UserOrganizationsList.tsx
Problem as here (https://github.com/open-condo-software/condo/pull/3360): if user have more than 100 organizations then will be load only first 100
=> fix(condo): DOMA-6196 fixed display of organizations on user page

apps/condo/domains/contact/components/contactRoles/BaseContactRoleForm.tsx, apps/condo/domains/contact/components/contactRoles/useExistingContactRoles.tsx
Problem: 
1) You can't save existing contact role without changes
2) If a user is in multiple organizations and one of the organization's has an "A" role, then the user cannot create a contact role with the same "A" name in another organization.
=> fix(condo): DOMA-4512 fixed contact role form validation

apps/condo/domains/ticket/hooks/useIncidentTableColumns.tsx, apps/condo/domains/ticket/utils/clientSchema/IncidentRenders.tsx
Problem: last column with ellipsis - text is not displayed completely
=> fix(condo): DOMA-6130 fixed incident table

apps/condo/domains/meter/hooks/useImporterFunctions.ts, apps/condo/domains/meter/utils/helpers.spec.ts, apps/condo/domains/meter/utils/helpers.ts, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json
You get error from meters import when imported file has invalid meter values
Errors are displayed in the table without completing the import with an error. 
Empty values are ignored.
=> fix(condo): DOMA-5070 added validation meter values when meters import

apps/condo/domains/common/components/trackers/AmplitudeInstance.ts
Due to amplitude docs `setUserProperties` become deprecated.
So we need to migrate to the `identify` API
=> DOMA-6300 replace setUserProperties with identify api at amplitude provider

apps/condo/domains/common/components/PostMessageProvider/Provider.tsx, apps/condo/domains/common/hooks/useGlobalHints.tsx, apps/condo/domains/property/components/BasePropertyForm/index.tsx
1. Hints should have classnames, should it could be hidden by css in mobile app web view
2. Mobile web view does not have type `ServiceWorker` (idk why, since its specs says they're having one), so I refactored check in `postMessage`
3. Antd with horizontal gutter use negative margins to fit content in it, in some mobile cases width can be > 100% which cause scroll (I could possible do it with `overflow-x: hidden`, but I think I can cause shadow issues in other places, so I solved it "on the spot")
=> fix(condo): DOMA-6311 Condo WebKitView minor issues 

apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx, apps/condo/domains/news/components/NewsForm/ResendNewsForm.tsx, apps/condo/domains/news/components/NewsForm/UpdateNewsForm.tsx, apps/condo/domains/news/components/RecipientCounter.tsx
made actual data to be sent to the RecipientCounter to display correctly
there used to be a problem that if we created news item with some sections, when we tried to update this news item in the update form, the initial values were units instead of sections now it fixed
=> fix(condo): DOMA-6334 fixed RecipientCounter by form update and display of sections in form

apps/condo/domains/meter/components/BaseMeterModal/BaseMeterModalForm.tsx, apps/condo/domains/meter/hooks/useMeterValidations.ts
Problem: search by `number` during `Meter` validation was incorrect. For example, `number 1` and `    number 1     ` were considered different numbers, although in fact they are the same if you trim the spaces
=> fix(condo): DOMA-6297 fixed meter validations

apps/condo/domains/organization/components/OrganizationSelect.tsx, apps/condo/domains/user/components/UserOrganizationsList.tsx
Problem: when `user 1` is authorized and resets the password for another `user 2`, then after resetting password, `user 2` is automatically authorized, but selected organization from previous `user 1` remains
=> fix(condo): DOMA-6299 added auto organization reset  when changing user

apps/condo/domains/acquiring/components/payments/PaymentsPageContent.tsx, apps/condo/domains/organization/components/Recipient/SettingsContent.tsx
Now these queries do not have a filter `status: FINISHED` and if `useObject` is used, the frontend falls if there are two contexts (validation is prohibited to create 2 contexts in status `FINISHED`)
=> fix(condo): DOMA-6421 added status filter to context queries

apps/condo/domains/user/constants/errors.js, apps/condo/domains/user/schema/ForgotPasswordService.js, apps/condo/domains/user/schema/ForgotPasswordService.test.js, apps/condo/domains/user/schema/RegisterNewUserService.js, apps/condo/domains/user/schema/RegisterNewUserService.test.js, apps/condo/domains/user/schema/User.js, apps/condo/domains/user/schema/User.test.js, apps/condo/domains/user/utils/serverSchema/validateHelpers.js, apps/condo/domains/user/utils/serverSchema/validateHelpers.test.js, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, apps/condo/schema.graphql, apps/condo/schema.ts
Problem: the user name can be of any length. Because of this, if the name is short, then there is a high probability that it will be contained in the password. 
This is a rare case indeed. But in a couple of days, random tests have already fallen several times
Solution: remove this check
Related to https://github.com/open-condo-software/condo/pull/3420
=> fix(condo): DOMA-6456 removed checking for content of user name in password

apps/condo/pages/initial.tsx, apps/condo/pages/meter/index.tsx
webview cannot start from the page `/`, as there is a redirection logic to `/reports`, which is not in webview (and other unnecessary logic). If webview start from another page that is in webview, then on this page will be broken history and back button. So added a new `/initial` start page for webview.
Also show action bar for meter readings in mobile screens
=> fix(condo): DOMA-6467 added initial page for webview

apps/condo/domains/news/components/RecipientCounter.tsx
=> fix(condo): DOMA-6437 fixed padding excel download recipient counter

apps/condo/domains/banking/schema/BankAccountReportTask.test.js, apps/condo/domains/banking/tasks/generateReports.js, apps/condo/domains/banking/tasks/importBankTransactionsFrom1CClientBankExchange.js, apps/condo/domains/organization/integrations/sbbol/constants.js, apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js, apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.spec.js, apps/condo/domains/property/components/PropertyReportCard.tsx, apps/condo/pages/property/[id]/report.tsx
Refactored the handling of sbbol errors when requesting transactions and balance. Now if an error occurs, you can see the reason in `BankAccount.meta`
=> feat(condo): DOMA-6527 handle sbbol errors from transaction request and write them to BankAccount meta

apps/condo/domains/miniapp/constants.js, apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.js, apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.test.js
There is special B2C app with fixed ID that is used for debugging. Added support for that fixed B2C app id to SendB2CAppPushMessageService
=> feat(condo): DOMA-6555 added fixed debug app id support to SendB2CAppPushMessageService

apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.js, apps/condo/domains/billing/schema/SendNewReceiptMessagesToResidentScopesService.test.js, apps/condo/domains/resident/gql.js, apps/condo/domains/resident/schema/Resident.js, apps/condo/schema.graphql, apps/condo/schema.ts
RSO billing receipts are created within EPS integration, but residents that receive those receipts are created within ordinary organizations, so mapping receipts to residents via billing context is not working for such cases. This PR fixes the issue im most possible optimal way, by mapping such receipts to residents connected to actual property mapped via address in billing property of receipt.
=> feat(condo): DOMA-5825 fix billingProperty to property mapping, types updated, tests fixed

packages/ui/src/components/Tag/style.less, packages/ui/src/components/Tag/tag.tsx, packages/ui/src/stories/Tag.stories.tsx
=> feat(ui): DOMA-6671 added icon for "Tag" component

apps/condo/domains/banking/components/FileImportButton.tsx, apps/condo/domains/common/components/containers/GlobalStyle.tsx
=> DOMA-6722 allow upload component to fit parent width

apps/condo/domains/common/components/Table/Renders.tsx, apps/condo/domains/common/components/containers/GlobalStyle.tsx, apps/condo/domains/ticket/hooks/useTableColumns.tsx, apps/condo/domains/ticket/utils/clientSchema/Renders.tsx
Problem: tables for mobile layout broke after update `antd`
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> hotfix(condo): fixed tables for mobile layout

apps/condo/domains/common/utils/fileAdapter.js, apps/condo/domains/common/utils/sberCloudFileAdapter.js, apps/condo/domains/ticket/schema/CallRecord.js
When you save a conversation record for each organization that has the same `phone` as the conversation participant, the `CallRecord` object is created and a separate file is created in cloud for each `CallRecord`.
The real case: our callcenter has 14 organizations with one `phone` number. This means that for every conversation that is not attached to the ticket, 14 copies of the conversation files will be created. It can take up a lot of space.
The solution is to have the same file attached to such `CallRecord` objects.
1) Added `saveFileName` to `SberCloudAdapter` – if it's `true`, then original file name will be saved and if such file already exist in cloud, it will not be saved again
2) Pass `CallRecord` id in file meta `ids` field in `CallRecord.afterChange` hook when a new …
=> DOMA-6733 one file in many call records

apps/condo/domains/ticket/utils/helpers.ts
It is unclear in what year the ticket was created
Before:
After:
=> fix(condo): DOMA-6788 added year in ticket creation date

apps/condo/domains/ticket/components/TicketId/TicketCallRecordHistory.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, apps/condo/pages/ticket/[id]/index.tsx
Now the button is located at the bottom, under the ticket data, after the hint and incidents. If the screen of the computer is small, the operator has to sweep down the page to the button, the button is not visible.
Solution: move button to action bar
=> fix(condo): DOMA-6740 move attach call record button to action bar

apps/condo/domains/notification/constants/constants.js, apps/condo/domains/ticket/tasks/sendTicketCommentNotifications.js, apps/condo/domains/ticket/utils/handlers.js, apps/condo/schema.graphql, apps/condo/schema.ts
=> fix(condo): DOMA-6834 added organizationId to ticket comment pushes

apps/condo/domains/ticket/schema/TicketChange.test.js, apps/condo/domains/ticket/utils/serverSchema/TicketChange.js
Hey!
We had a problem with field `actualUpdatedAt` filling with wrong values:
== before ==
----
I fixed this by changing the implicit logic inside `createTicketChange` function:
This logic was first implemented in [this](https://jira.in.doma.ai/browse/DOMA-5956) task
> Now ONLY IF STATUS WAS CHANGED, the actualCreatedAt will fill with statusUpdatedAt value
== after ==
=> DOMA-6980 fix actualUpdatedAt bug

apps/condo/domains/common/components/UseDeskWidget.tsx
**Problem:** We received feedback that after writing a message in the chat the management company updates the page or closes it, then they reset the dialogue and have to write again. They also do not receive technical support responses for this reason.
**Solution:** Generate and send chat token to `userIdentify` function. Chat will be saved for a specific browser until cookies are cleared.
=> feat(condo): DOMA-6522 save usedesk chat

apps/condo/domains/news/components/TemplatesTabs.tsx
=> DOMA-7076 ignore ui-kit tabs operations at the custom one in news domain

apps/condo/domains/common/hooks/useCheckTLSClientCert.tsx
Because Sber URLS are not belonging to origin of Doma.ai, there is no possibility to make requests.
The only way was using "no-cors" mode of `fetch`.
Due to using "no-cors" mode, responses of `fetch` does not containing any useful information.
Previously fetch has thrown an Error, and I've relied on it, but now it does not.
It seems to be impossible to do anything now.
So, a manual disabling of feature has been implemented.
=> fix(condo): DOMA-6513 moved CHECK_TLS_CLIENT_CERT_CONFIG variable into condo microservice

apps/address-service/domains/common/utils/services/suggest/providers/DadataSuggestionProvider.js
Before this PR we've always added a trailing space. This is why DADATA searches nothing if there is no full street name:
But in the case of trailing number we have to keep trailing space to make DADATA search addresses correctly:
Without trailing space after number we get wrong suggestions:
=> fix(address-service): DOMA-7110 keep trailing space only for trailing number

apps/condo/domains/common/utils/serverSchema/index.js, apps/condo/domains/news/constants/common.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js, apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js, apps/condo/domains/news/utils/testSchema/index.js
if we use `chunkProcessor` for data loading we can return an empty list in it (It is necessary that `all` variable in `loadListByChunks` does not take up much memory).
Therefore, the length of the new chunk need to be counted before converting the received data in `chunkProcessor`
=> fix(condo): DOMA-7172 fixed case when processed chunk in loadListByChunks is empty

apps/condo/domains/common/utils/sberCloudFileAdapter.js
`sendStatus` it's a terminate operation and in case with `shallow-redirect` it throws error
=> fix(condo): DOMA-7186 used status() instead sendStatus() in obsRouterHandler

apps/condo/domains/property/utils/serverSchema/helpers.js
Trying to get `rawValue` first to detect the resident's address. This field may contain the UUID of address injection at address service.
=> fix(condo): DOMA-7223 resident registration: get `rawValue`

apps/condo/domains/organization/access/OrganizationEmployeeRole.js, apps/condo/domains/organization/components/OrganizationRequired.tsx, apps/condo/domains/organization/components/PageAccess.tsx, apps/condo/domains/organization/hooks/useEmployeeRolesTableData.tsx, apps/condo/domains/organization/schema/OrganizationEmployeeRole.test.js, apps/condo/domains/property/components/BuildingsTable.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, apps/condo/pages/employee/create.tsx, apps/condo/pages/news/index.tsx
1. Employee without `canReadEmployees` role can read own `OrganizationRole`
2. Added `canInviteNewOrganizationEmployees` permission to table
3. Fix display empty action bar on property and news pages
=> fix(condo): DOMA-7259 fix settings table after testing

apps/condo/domains/common/components/settings/MobileFeatureConfigContent.tsx
all cards are positioned to the left edge, 2 in a row
before: 
after:
=> fix(condo): DOMA-7340 fix layout of MobileFeatureConfigContent

apps/condo/domains/common/schema/fields.js, apps/condo/domains/organization/schema/InviteNewOrganizationEmployeeService.js, apps/condo/domains/user/constants/errors.js, apps/condo/domains/user/schema/ConfirmPhoneAction.js, apps/condo/domains/user/schema/RegisterNewUserService.js, apps/condo/domains/user/schema/RegisterNewUserService.test.js, apps/condo/domains/user/utils/serverSchema/index.js, apps/condo/domains/user/utils/testSchema/index.js, apps/condo/schema.graphql, apps/condo/schema.ts
Now any user (also without auth) can create a `user` without an phone confirmation using `registerUser`.
**Fix**: Made `confirmPhoneActionToken` required in `registerUser`
=> DOMA-7184 made confirmPhoneActionToken required in RegisterNewUserService

apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js, apps/condo/domains/resident/tasks/helpers/sendResidentsNoAccountNotifications.js
The first commit fixes the problem with connected but deleted/missing `billingContext` in `ServiceConsumer`. Since the deprecated field no one fills it with current data and it interferes with the correct search for SC instances.
the second commit fixes the case when at 3 addresses with different beginnings of the period, but the same end of the period, also for the reverse case
=> fix(condo): DOMA-7560 fix notification about meter readings and receipts

apps/condo/domains/common/components/GraphQlSearchInput/GraphQlSearchInput.tsx, apps/condo/domains/common/components/GraphQlSearchInputWithCheckAll.tsx, packages/codegen/generate.hooks.ts, packages/codegen/generate.server.utils.js
<details>
<summary> <h2>Added a multiform for create pass setting </h2></summary>
<h3>Before</h3>
https://github.com/open-condo-software/condo/assets/56914444/6ed577f3-bc6b-4aa5-b16c-30cf80544598
<h3>After</h3>
https://github.com/open-condo-software/condo/assets/56914444/9bd05bf5-d6dd-4000-81b3-462bcef49de1
</details>
-------
<details>
<summary> <h2>Fixed pass setting updating </h2></summary>
<h3>Before</h3>
https://github.com/open-condo-software/condo/assets/56914444/515494ff-c86b-4787-862a-c0fe86347fe3
<h3>After</h3>
https://github.com/open-condo-software/condo/assets/56914444/b104a8bb-546b-4548-9ecc-18665b293e0a
</details>
-----
<details>
<summary> <h2>Added bulk-operations in passapp (and added utils for working with them)</h2></summary>
Previously, when adding/updating/deleting 10 …
=> feat(pass): DOMA-7035 added a multiform for create pass setting

yarn.lock
We need to support different excel formats. Now excel parser breaks on parsing 1C excel files
=> feature(registry): DOMA-7601 changed library to work with excel files

apps/condo/domains/ticket/components/BaseTicketForm/AutoAssigner.tsx
Current user from holding is automatically assigned as assignee for ticket if the user is not in the selected organization as an employee 
https://github.com/open-condo-software/condo/assets/56914444/b8b1113f-0bd9-436c-a405-6b59dcfa3207
https://github.com/open-condo-software/condo/assets/56914444/e5323ef2-6c23-4e2e-ae42-29bc2b100636
=> fix(condo): DOMA-5584 fixed automatic assigner tickets for employees from holding

apps/condo/domains/billing/access/BillingReceipt.js, apps/condo/domains/billing/schema/BillingReceipt.test.js, apps/condo/domains/billing/schema/BillingReceiptFile.test.js
ServiceConsumer do not updates on billingContext change and user looses access to billingReceipts
Now access check do not depends on deprecated fields
=> fix(condo): DOMA-7657 remove deprecated fields in access check

apps/condo/domains/billing/schema/RegisterBillingReceiptsService.js, apps/condo/schema.graphql, apps/condo/schema.ts
Extended RegisterBillingReceipt service's input to support accountMeta and addressMeta
We can now pass raw address from integration together with FIAS id
For billing account, integration can pass additional info as ELS, Person/Company is an owner and importId to determine weather it is the same account or is a new account
All new fields are optional
=> feature(condo): DOMA-7682 extend register billing receipt input type

apps/condo/domains/organization/integrations/sbbol/routes.js, apps/condo/domains/organization/integrations/sbbol/sync/getOnBoadringStatus.js, apps/condo/domains/user/integration/appleid/utils/helper.js, apps/condo/domains/user/integration/sberid/routes.js, apps/condo/pages/onboarding.tsx
**Problem**: If a user auth by sbbol/sberId/appleId and does not have an onboarding entity, then he will be redirected to `/onboarding` page, and then `/reports` page. 
Now it will redirect to `/` to avoid these unnecessary redirects
=> fix(condo): DOMA-7693 fixed redirect to onboarding page after auth by sbbol/sberId/appleId

apps/condo/domains/organization/access/Organization.js, apps/condo/domains/organization/schema/Organization.js, apps/condo/domains/organization/schema/Organization.test.js, apps/condo/domains/organization/utils/testSchema/index.js
For security reasons now we deny updates on importId and tin organisation's fields
=> fix(condo): DOMA-7765 now TIN of organization can be changed only by admin

apps/condo/bin/update-b2b-app-roles-for-passapp.js
You can now allow employees to update pass ticket statuses, but prohibit pass ticket creation
This is necessary so that security guards cannot create passes unless they are explicitly allowed to do so.
----
Before release, need to add a new B2BAppPermission and run the script to fill new field
=> feat(pass): DOMA-7653 added access to manage pass ticket status field

apps/address-service/schema.ts, apps/condo/domains/common/schema/fields.js, apps/condo/schema.graphql, apps/condo/schema.ts, apps/dev-portal/lib/gql/index.ts, apps/miniapp/schema.ts, packages/keystone/plugins/dvAndSender.js
I just made that help text near `sender` helping text is actually a valid JSON, so it can be copy-pasted to the field below
Here is how it looks now:
And a proof its a valid JSON now
=> refactor(condo): HOTFIX: Make JSON in sender help text valid

apps/condo/domains/billing/schema/RegisterBillingReceiptsService.new.test.js, apps/condo/domains/billing/schema/resolvers/recipientResolver.js
If support user marks recipient as not approved - UM will not change this
=> fix(condo): Do not change isApproved on existing recipients

apps/condo/migrations/20231214092431-0352_auto_20231214_0424.js
The `TicketPropertyHintProperty` UPDATE expression did not take into account that these must be different records
=> fix(condo): DOMA-8022 fix delete proeprty hint property duplicates migration

apps/condo/domains/common/schema/fields.js, apps/condo/domains/meter/schema/MeterReading.js, apps/condo/domains/meter/schema/MeterReading.test.js
Fixed error code for client phone validator
**Before**: `[phone:wrongFormat:phone]` - It is not clear which field the error relates to
**After**: `[phone:wrongFormat:clientPhone]` or Before: `[phone:wrongFormat:some-your-field-name]`
=> fix(condo): DOMA-8029 added supporting of landline phone for MeterReading

apps/condo/domains/common/components/PopupSmart.tsx, apps/condo/next.config.js
On production, `popupsmart` works through an old api, which does not work on dev and review stands.
=> feat(condo): DOMA-8175 updated popupsmart

apps/condo/domains/marketplace/access/MarketPriceScope.js
The resident mobile app adds all received scopes to the local database and if a scope arrives with deletedAt set, the record is deleted from the local database. Since access filtering on the server cuts off all remote instances, the logic for updating the database locally does not work and the user sees deleted records.
=> fix(condo): DOMA-8192 return deleted instance of MarketPriceScope to Resident user

packages/keystone/setup.utils.js
By default knex adapter will create 10 postgres connections.
This PR reduces maximum available connections count for the pool to 4 and sets min connection count to zero for resolving issue with non terminated idle connections
=> fix(keystone): INFRA-247 set min pg conn pool to zero & max to 4

packages/keystone/KSv5v6/v5/registerSchema.js
If you make a query for schema with many objects, for example `allTickets`, without specifying `first` argument, instead of an `Your request exceeded server limits` error from the server, it returns a timeout error from database select `select \"t0\".* from \"public\".\"Ticket\" as \"t0\" where true and (\"t0\".\"deletedAt\" is null) - canceling statement due to statement timeout` or 502 error with falling pod.
The `maxResults` parameter is set to `first` argument if it passed.
Now we are already specify `maxTotalResults` (maximum number of returned objects, including nested ones) = 1000 in `prepareDefaultKeystoneConfig`, in this pr i set `maxResults` to 1000 too to prevent database queries when `first` not set or set > 1000.
Keystone `_itemsQuery` limits check:
=> fix(condo): DOMA-8275 added maxResults 1000 to keystone lists

apps/condo/domains/notification/adapters/apple/AppleMessaging.js, apps/condo/domains/notification/adapters/apple/constants.js, apps/condo/domains/notification/adapters/appleAdapter.js
Before release, you need to delete the task with the old config in production. So that after the release there is no duplication
=> hotfix(condo): add retrying for deliverMessage task

packages/keystone/KSv5v6/v5/prepareKeystone.js
Hi, I want to add a small feature to `prepareKeystone()` function. 
My usecase: I need to override `cookie` param, so a `miniapp` can access cookies on other domains.
I can achieve such functionality using built in `extendExpressApp` but this way code is cleaner, and we do not override cookie secret and other variables. 
Example usecase: 
```(js)
const extendKeystoneConfig =(defaultConfig) => {
cookie: {
...defaultConfig.cookie,
// Enable cross-site usage
sameSite: 'none',
secure: true,
}
}
module.exports = prepareKeystone({
lastApp, schemas, apps, extendKeystoneConfig
})
```
=> feat(condo) HOTFIX: add the ability to extend keystone config

apps/condo/domains/news/components/NewsPreview.tsx
**Problem**: The news in preview is displayed differently than in mobile app
<details>
<summary><h2>Before</h2></summary>
</details>
<details>
<summary><h2>After</h2></summary>
</details>
=> fix(condo): DOMA-8309 added line breaks in news item preview

packages/ui/src/components/Card/header/cardHeader.less, packages/ui/src/components/Card/header/cardHeader.tsx, packages/ui/src/components/Tag/tag.tsx
In cardHeader.less there was overridden styles for all tags in `.condo-card`, not only in `CardHeader` (which specified with `tag` prop)
**Before**
**After:**
=> hotfix(condo): fix tag in services cards

apps/condo/domains/notification/adapters/apple/AppleMessaging.js, apps/condo/domains/notification/adapters/apple/AppleSession.js, apps/condo/domains/user/utils/serverSchema/guards.js
what's changed:
The second point is a temporary solution. There is an opinion that this will slow down voip push notifications. An alternative to blocking the connection is a dedicated server, which will maintain a constant connection and all pushes from the conda will be proxied through it. Another option is to create a separate queue and a separate worker who processes this queue. In this case, everything will work within Conda, but will not require a dedicated service. There is no clear understanding yet of how to implement this.
=> feat(condo): DOMA-8441 Reuse opened connection to send a batch of VOIP pushes & use RedisGuard to prevent opening multiple connection with APNS

apps/condo/domains/miniapp/schema/SendB2CAppPushMessageService.js, apps/condo/domains/notification/constants/constants.js, apps/condo/schema.graphql, apps/condo/schema.ts
Mutation types and push types have been expanded. The added fields are necessary for the mobile phone to work directly with the SIP server
type - call interface type, currently always sent 'sip'
address - server address for connection
login - user login to connect to the voip server
password - user password for connecting to the voip server
dtfmCommand - dtfm command for door open button
automaticallyAcceptIncomingCall - Whether to automatically accept an incoming call when you open the VoIP calling interface. Currently always true
=> feat(condo): DOMA-8519 expand sendB2CAppPushMessage to VoIP native support

packages/keystone/tracing.js
This should stop our .d and v1 environments to send requests to `localhost` address
=> HOTFIX: Remove metrics exporter

apps/condo/domains/common/components/EmptyListContent.tsx
On ticket page there can be 2 empty lists: with import if featureflag enabled and without import. In empty list without import `createLabel` was not passed and button was not displayed.
Added default label for create button in empty list conent.
Before:
After:
=> fix(condo): DOMA-8607 show ticket create button on empty ticket view

apps/condo/domains/marketplace/schema/Invoice.js, apps/condo/domains/marketplace/schema/Invoice.test.js
- added the invoice id to uniqKey so that when several invoices are attached to one ticket, push notifications will be created for each invoice and will not result in an error due to the non-uniqueness of the key
- added a throttling check to the test
- I extract the sender from the context so that the invoice and ticket have the correct sender
=> fix(condo): DOMA-8344 fix push about invoice connected to ticket

apps/condo/domains/organization/integrations/sbbol/sync/syncUser.js, apps/condo/pages/auth/register.tsx
Enabled `ORGANIZATION-TOUR` featureflag for testing on review stand affecs condo.d and other review stands.
Kept this logic only in a branch with a new onboarding
=> hotfix(condo): remove featureflag check for creating onboarding

apps/condo/domains/organization/integrations/sbbol/oauth2.js, apps/condo/domains/organization/integrations/sbbol/routes.js, apps/condo/pages/property/[id]/report.tsx
Now, during the initial authorization via sbbol, an offer is made with access to accounts, but accounts are not added to the offer. **Accounts cannot be added immediately upon making an offer due to legal and security restrictions**. Therefore, it is necessary to remove the accounts parameter from the scope. So that the offer could be concluded without them. **And all subsequent authorizations must use the extended config**, which contains the accounts parameter. Then SBBOL will see that we are asking for something that was not previously available and will expand the offer. When expanding the offer, the accounts must be hooked up. **This is necessary to bypass legal restrictions**
=> feat(condo): DOMA-8709 add extended config for sbbol authorization

apps/condo/domains/common/components/Table/Index.tsx
https://github.com/open-condo-software/condo/assets/56914444/498c26bf-ad37-40f2-979f-05a96ff9b576
https://github.com/open-condo-software/condo/assets/56914444/1c88e5ec-026a-4f40-bb08-a0b902557392
=> fix(condo): DOMA-8653 fixed table filters

apps/condo/domains/billing/schema/resolvers/accountResolver.js, apps/condo/domains/billing/schema/resolvers/propertyResolver.js, apps/condo/domains/billing/schema/resolvers/utils.js
1. Fixed find organization properties query in account resolver
2. Some times globalId was saved with unit in property
3. If dadata returns the correct value not in first place of array - wrong address was registered
=> fix(condo): DOMA-8650 fixed case when address was not resolved correctly

apps/condo/domains/common/hooks/useGlobalHints.tsx, apps/condo/pages/user/index.tsx
We should not hide hints for non-ru locales.
The logic of the global hints works in such a way that they are shown only if there are translations of hints for the selected locale (This is configured in the config. You can watch it here: https://github.com/open-condo-software/condo/pull/3246)
=> fix(condo): DOMA-8748 removed global hints for non-ru locales

apps/condo/domains/common/components/GraphQlSearchInput/Renders.tsx, apps/condo/domains/property/utils/clientSchema/Renders.tsx, apps/condo/domains/ticket/components/IncidentForm/BaseIncidentForm.tsx, apps/condo/domains/ticket/components/IncidentForm/UpdateIncidentForm.tsx, apps/condo/domains/ticket/hooks/useIncidentTableColumns.tsx, apps/condo/domains/ticket/utils/clientSchema/IncidentRenders.tsx, apps/condo/pages/incident/[id]/index.tsx, apps/condo/pages/incident/index.tsx
<details>
<summary><h2>Before</h2></summary>
- Problems with deleted properties
- No button to cancel editing
- `undefined` is displayed instead of deleted property address
- page crashes
</details>
<details>
<summary><h2>After</h2></summary>
- Added button to cancel editing
- Deleted properties are displayed correctly
- Incident view page does not crash
https://github.com/open-condo-software/condo/assets/56914444/195494cc-6ac3-4350-b8c2-d68a32ffdb6f
</details>
=> fix(condo: DOMA-8777): fixed incidents with deleted property

apps/condo/domains/onboarding/utils/clientSchema/constants.ts
Click on createPropertyMap tour step redirects on `/property/${lastCreatedPropertyId}/map/update`, but if user delete all properties, then he will be redirected to `/property/undefined/map/update`.
Fixed it, now when no properties in organization, click on createPropertyMap tour step will redirects to `/property` page
=> fix(condo): DOMA-8829 fix redirect on click to createPropertyMap tour step if no properties

apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx, apps/condo/domains/news/components/RecipientCounter.tsx, apps/condo/domains/news/constants/common.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js, apps/condo/domains/user/components/NotDefinedField.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, apps/condo/pages/news/[id]/index.tsx
<details>
<summary><h2>Before</h2></summary>
- No news sending status
- News recipients take a long time to load
- No loading indicator
- Repeated requests for counters are sent every time
https://github.com/open-condo-software/condo/assets/56914444/0f4dc986-793c-42b0-922a-e24299ee370e
- No adaptive layout
https://github.com/open-condo-software/condo/assets/56914444/7069d933-ad48-427d-9aec-78c07b6e4b67
- The `getNewsItemsRecipientsCounters` query could return a timeout during a complex query to the database
</details>
<details>
<summary><h2>After</h2></summary>
- Added news sending status (as in table)
- Recipients load quickly
- Counters still take a long time to load, but with a loading indicator
- Repeated requests for counters are retrieved from the cache …
=> fix(condo): DOMA-8789 fixed news items recipients loading

apps/condo/domains/common/components/settings/MobileFeatureConfigContent.tsx, apps/condo/domains/common/constants/featureflags.js, apps/condo/pages/settings/index.tsx
**Removed MOBILE_FEATURE_CONFIGURATION and SUBMIT_ONLY_PROGRESSION_METER_READINGS Feature Flags**
Now every organization will have the Mobile App tab on the Settings page by default
And there is going to be the MeterReading setting under this tab
=> feat(condo): DOMA-8864 make mobileFeatureConfig available for all Orgs

apps/condo/pages/_app.tsx, apps/condo/pages/settings/index.tsx
make settings tab available for RSO so that they have MobileConfig settings only for MeterReadings
=> fix(condo): DOMA-8864 make settings tab available for RSO

apps/condo/domains/common/constants/regexps.js, apps/condo/domains/organization/schema/Organization.js, apps/condo/domains/organization/schema/Organization.test.js
If regex have `g` flag, then `regex.test(str)` will return different results. because we should use `str.match(regex)`
Example:
```
const reg = /test/g
reg.test('my-test') // return true
reg.test('my-test') // return false
reg.test('my-test') // return true
reg.test('my-test') // return false
'my-test'.match(reg) // return ['test]
'my-test'.match(reg) // return ['test']
'my-test'.match(reg) // return ['test']
'my-test'.match(reg) // return ['test']
'my'.match(reg) // return null
'my'.match(reg) // return null
```
=> hotfix(condo): DOMA-8985 fixed a validation of organization name

apps/condo/domains/meter/components/Import/Index.tsx, apps/condo/domains/onboarding/contexts/TourContext.tsx
After meter readings import changes to back-end implementation, the default logic of complete `createMeterReadings` step modal stopped working (Now, there is no `createMeterReading` actions from client).
Fixed it: send import event in importer `onFinish` and handle it in `TourContext` importHandler
=> fix(condo): DOMA-9004 fix complete step modal show after first meter readings import

apps/condo/domains/meter/schema/Meter.test.js, apps/condo/domains/meter/utils/serverSchema/index.js
Removed checks that resident unitName matches meter's unitName. Only checks for accountNumber matching
=> fix(condo): Doma-8869 fix permission check to access meters

packages/keystone/KSv5v6/v5/prepareKeystone.js, packages/keystone/logging/GraphQLLoggerApp.js, packages/keystone/logging/getKeystonePinoOptions.js, packages/keystone/logging/index.js
=> fix(condo):INFRA-296 logging pipeline adjustments

apps/condo/domains/news/schema/GetNewsSharingRecipientsService.js, packages/keystone/fetch.js, packages/keystone/fetch.spec.js
We need more control for online interactions. Such as: abort request by timeout and make retries
=> feat(condo): Doma-9300 fetch with retries

apps/condo/domains/organization/integrations/sbbol/utils/changeClientSecret.js, apps/condo/domains/organization/integrations/sbbol/utils/getAccessTokenForUser.js, apps/condo/domains/organization/tasks/refreshSbbolClientSecret.js
Fixed 2 problem:
1. On development we have a deleted user for auto refresh clientSecret. Updated it in .helm
2. Authorization was called twice for one user to update clientSecret, and in the second integration (sbbolSecretStorageExtended) there was a expired refreshToken. Made getAccessTokenForUser be called once
=> fix(condo): DOMA-9343 fix refresh sbbol client secret

apps/condo/domains/meter/components/TabContent/MeterReading.tsx, apps/condo/domains/meter/components/TabContent/PropertyMeterReading.tsx, apps/condo/domains/meter/hooks/useMeterFilters.tsx, apps/condo/domains/meter/hooks/useMeterReadingFilters.tsx
allow choose select tags with spaces in meter and meter reading tables
=> fix(condo): DOMA-9585 fix select filter with spaces

apps/condo/domains/ticket/tasks/closeCompletedTickets.js
When executing a task, there is no need to pass the Keystone context.  if you pass it, then the data about feature flags will not be up-to-date
=> fix(condo): DOMA-9737 fixed context for getting of feature flag in task of close completed tickets

apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.js, apps/condo/domains/news/tasks/notifyResidentsAboutNewsItem.spec.js
When sending news, not all residents from the scope received a notification (there was a limit of 100 scopes). Now any number of scopes will be supported.
1. A test was written that checks that 101 residents receive notification of the news.
2. The task has been changed, which notifies the resident about the news in which the limit of 100 scopes has been lifted
=> fix(condo): DOMA-9647 pushing newItem in all scopes

apps/condo/domains/notification/adapters/appleAdapter.js, apps/condo/domains/notification/adapters/appleAdapter.spec.js, apps/condo/domains/notification/adapters/firebaseAdapter.js, apps/condo/domains/notification/adapters/firebaseAdapter.spec.js, apps/condo/domains/notification/adapters/hcmAdapter.js, apps/condo/domains/notification/constants/constants.js
I googled that the error occurs when incorrect data is used for the team_id, key_id and private_key variables.
We use exactly the correct data, but if the connection is raised to push the old mobile application, and then in the same connection we configure another application(new mob app), then apns throws an error, because they opened a connection with it for one application, and are trying to send a push to another, That's why they swear that the provider is invalid. If the hypothesis is correct and this is the reason, then you need to make a separate sending queue for each application so that the configs do not change within the same open connection. The easiest way to check is this: if old application -> return 0. If errors disappear in voice pushes, then this hypothesis is correct.
=> feat(condo): DOMA-9739 disabling notifications for specific appIds

apps/condo/domains/marketplace/components/MarketSetting/MarketSettingForm.tsx
"Variable \"$data\" got invalid value { dv: 1, sender: { dv: 1, fingerprint: \"ZOEdK5UUn9Ru\" }, organization: { connect: [Object] }, isPaymentCashTypeBlocked: false, residentAllowedPaymentTypes: [\"online\", \"cash\"] }; Field \"isPaymentCashTypeBlocked\" is not defined by type \"MarketSettingCreateInput\"."
=> fix(condo): DOMA-9843 fix marketSetting formValuePreprocessor

apps/condo/domains/news/constants/common.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js, apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
**Problem**: `getNewsItemsRecipientsCounters` crashes with large data
**Solution**: changed `loadListByChunks` to `allItemsQueryByChunks` so that flat objects are returned, without nesting and virtual fields
_Сan also think about caching queries, but I haven't done it yet._
=> refactor(condo): DOMA-8306 refactored mutation "getNewsItemsRecipientsCounters"

apps/condo/domains/billing/components/BillingPageContent/ServicesModal.tsx, apps/condo/domains/billing/gql.js
If no receipt id passed, page tries to load 100 billing receipt files
now receipts will be fetched together with file
=> fix(condo): DOMA-9763 fixed billing files load

apps/condo/domains/acquiring/access/SumPaymentsService.js, apps/condo/domains/acquiring/schema/SumPaymentsService.test.js, apps/condo/domains/billing/schema/SumBillingReceiptsService.test.js
If no `organizationId` was presented in `where` args, then user with directAccess can not execute mutation. 
Fixed it
=> fix(condo): DOMA-9902 fix canSumPayments access for directAccess

apps/condo/domains/property/hooks/useImporterFunctions.tsx
When importing properties, it is inconvenient that the total number of units is rounded down - users have to recalculate the number of units on the floor and modify the property map manually.
We have rounded up the number of units on floor. Now users only need to delete unnecessary units when importing a property with a non-multiple number of units.
=> fix(condo): DOMA-9287 use math ceil instead math floor for unitsOnFloor

yarn.lock
Send default value for request (zero value) if the organization is not in the condo to prevent many redundant requests
=> feat(condo-restapi): DOMA-10004 check organization existence

packages/keystone/tracing.js
To track request traces between applications
=> feat(keystone): DOMA-10066 set startReqId to tracing span if it exists in execution context

apps/condo/domains/resident/schema/RegisterResidentService.js, apps/condo/domains/resident/schema/RegisterResidentService.test.js
Problem: 
Users can not change unitName for resident. That leads to issues with transmission of meter readings.
With these changes user can delete resident with wrong unitName case and add new one with different case
=> fix(condo): DOMA-9474 creating new resident, if it was deleted instead of restoring

apps/condo/domains/news/components/RecipientCounter.tsx, apps/condo/domains/news/constants/common.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.js, apps/condo/domains/news/schema/GetNewsItemsRecipientsCountersService.test.js, apps/condo/domains/news/utils/serverSchema/recipientsCounterUtils.js
– if resident unitName does not exist in property map – this resident will still be counted
As it was discussed in ADR-36, we should remove all loadListByChunks-like operations, here I switch from allItemsQuery for Residents table (which is quite big) to raw sql query (just like in analytics domain)
- Raw SQL query will not be fixed, If needed I will implement LRU cache decorator
- Should we handle unitTypes here? I'll ask around.
- Usage of `distinct(count` + lack of index on `unitName` table will still be quite expensive for large users, we should take a close look to the timeout errors
=> proof of work: fix(condo): DOMA-10099 change counters logic

apps/condo/domains/notification/adapters/firebaseAdapter.js
After updating the `Firebase` libraries, I noticed that in the new version, the method we used to send notifications in batches was outdated and marked deprecated. Changed the method used to the current one.
=> refactor(condo): DOMA-10178 use sendEach() instead of deprecated sendAll() in firebaseAdapter.js

packages/featureflags/FeatureFlagsContext.tsx, packages/featureflags/featureToggleManager.js
We had case when growthbook's server was not responding. For that case TTL for featureflags was removed, we still update features once per minute, but not removing old one. 
Also extended refetch interval for /features api route, because client spamming fetch queries too much
=> fix(condo): DOMA-10091 growthbook features keeping

apps/condo/domains/ticket/components/IncidentForm/BaseIncidentForm.tsx
In filed "Whats happend" in incident log there was a 500 character limit. Now there is a 1500 character limit. This change is in both callcenter and condo
=> fix(condo): DOMA-10216 increasing number of char in incident

apps/address-service/domains/common/utils/services/search/SearchKeystoneApp.js
At the moment its a runtime error
=> hotfix(address-service): return 400 in case of `?q=...&q=...`

apps/condo/domains/acquiring/gql.js, apps/condo/domains/acquiring/schema/Payment.js, apps/condo/domains/acquiring/schema/Payment.test.js
We have raw address in raw field of receipt.
Inside it's json addres there is no global path for all receipts, where address is stored, so try different paths.
Raw address is needed later, when we allow to load payments, so managing company can compare them with their data by address
=> feat(condo): DOMA-10496 fill raw address in payment

apps/condo/domains/billing/components/BillingPageContent/MainContent.tsx, apps/condo/domains/billing/components/BillingPageContent/ReceiptsTable.tsx, apps/condo/domains/billing/components/BillingPageContent/ReportMessage.tsx, apps/condo/domains/billing/components/BillingPageContent/index.tsx, apps/condo/domains/common/components/Table/Renders.tsx, apps/condo/domains/common/components/Tooltip.tsx, apps/condo/domains/miniapp/components/IFrame.tsx, apps/condo/lang/en/en.json, apps/condo/lang/ru/ru.json, packages/ui/src/components/ActionBar/actionBar.tsx
New flow for uploading receipts in integrations
Now uploading will be in the extension tab with history of uploading
Registry: new table form for uploading receipts with ability to edit cells or columns if necessary
review: https://review-new-registry-upload-form-condo.r.doma.ai/billing?tab=extension
=> feat(condo): DOMA-9269 move receipts upload to extension tab

apps/condo/domains/ticket/gql.js, apps/condo/domains/ticket/tasks/exportTickets.js, apps/condo/domains/ticket/utils/serverSchema/exportTicketBlanksToPdf.js
Ticket export does not contain comments even if you explicitly selected this option in interface
Add missing options field to getOne
P.S We need typescript and tests (DOMA-10612)
=> fix(condo): DOMA-10550 add missing field to export task graphql

apps/condo/pages/_app.tsx
fix:
```
VM60962 _app.tsx:391 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `MenuItems`. See https://fb.me/react-warning-keys for more information.
in Fragment (created by MenuItems)
in MenuItems (at _app.tsx:499)
in div (at DesktopSideNav.tsx:64)
in div (created by Sider)
in aside (created by Sider)
in Sider (at DesktopSideNav.tsx:46)
in DesktopSideNav (at SideNav/index.tsx:20)
in SideNav (at BaseLayout.tsx:51)
in section (created by ForwardRef)
in ForwardRef (created by Layout)
in Layout (created by EmotionCssPropInternal)
in EmotionCssPropInternal (at BaseLayout.tsx:50)
in BaseLayout (at _app.tsx:499)
in ConnectedAppsWithIconsContextProvider (at _app.tsx:498)
in ActiveCallContextProvider (at _app.tsx:497)
in TicketVisibilityContextProvider …
```
=> fix(condo): close #5463 no more useless warning

apps/condo/domains/notification/adapters/hcm/messaging.js
Turns out destructing does not create a new object
```js
const defaultConfig = {
android: {
settings: {
ttl: '1000s'
}
}
}
const message1 = {
android: {
...defaultConfig.android,
data: 'some data'
}
}
message1.android.settings.ttl = '2000s'
console.log(defaultConfig.android.settings.ttl) // Prints: '2000s'
```
=> chore(condo): use Object.freeze on DEFAULT_ANDROID_PAYLOAD

apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx
Because of this, there are unnecessary authorization requests in global miniapps
=> fix(condo): DOMA-10682 do not render global apps when no organization selected

apps/condo/pages/contact/[id]/index.tsx, apps/condo/pages/ticket/[id]/index.tsx, apps/condo/pages/ticket/[id]/update.tsx
**Before:**
https://github.com/user-attachments/assets/050faf80-74fe-42d2-a947-2d33539d978a
**After:**
https://github.com/user-attachments/assets/fc9dc0d9-af7f-41d3-a3f9-9a6510b88c3a
=> fix(condo): DOMA-10739 get contact from ssr

apps/condo/domains/news/components/NewsForm/BaseNewsForm.tsx
Made a redirect and notification when there was a time error
=> fix(condo): DOMA-10125 add time validate

apps/condo/domains/meter/tasks/importMeters.spec.js, apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.js, apps/condo/domains/meter/utils/taskSchema/AbstractMetersImporter.spec.js, apps/condo/domains/meter/utils/taskSchema/importerResolver.js
Previously i added date validation here, but failed rows still were sent to mutation.
Sending failed rows to mutation can lead to unreadable message for user, for example if column has different type, than mutation requires. In that case it is better to make validation here and skip failed rows, so user can read normal error message
=> fix(condo): DOMA-10614 do not send meter readings in mutation if date validation failed

apps/condo/domains/meter/components/MeterReportingPeriodForm.tsx, apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.js, apps/condo/domains/meter/tasks/sendSubmitMeterReadingsPushNotifications.spec.js
removed check that start notify period date must be smaller than end date (for MeterReportingPeriod)
=> fix(condo): DOMA-8764 allow notify period end be smaller than start

apps/condo/domains/ticket/hooks/usePollTicketComments.tsx, apps/condo/domains/ticket/queries/TicketComment.graphql
Query only last 100 comments (how it was before we rewrote the queries) and wrap `refetch` call in try/finally, to define `syncTicketCommentsAt` (date key in localStorage) even if the request fails
=> fix(condo): DOMA-10792 fix getPollTicketComments query

apps/condo/domains/common/utils/tables.utils.ts
Do not fire a search request on `number: <value>` if value > INT_32
=> fix(condo): HOTFIX: use INT_32 cap in global table utils

apps/condo/domains/ticket/constants.js, apps/condo/domains/ticket/gql.js, apps/condo/domains/ticket/queries/Ticket.graphql, apps/condo/domains/ticket/schema/Ticket.js, apps/condo/domains/ticket/schema/Ticket.test.js
We want to make sure that push notifications do not come to the technician's mobile app when mass reassigning requests. However, the logic requires a custom query name, so the test in this PR checks this logic.
And here are added the current changes for the callcenter, so that the feature works, and the project is assembled
=> fix(condo): DOMA-10516 add test and update callcenter

apps/condo/domains/miniapp/components/GlobalApps/GlobalAppsContainer.tsx, apps/condo/domains/ticket/contexts/TicketVisibilityContext.tsx
Added `skip` for requests in TicketVisibilityContextProvider and GlobalAppsContainer, so that they are not executed until the user is authorized
=> fix(condo): DOMA-10927 added skip in global providers

apps/condo/domains/ticket/tasks/sendTicketChangedNotifications.js
If we do not add filtering for remote residents, the task that sends push notifications about changing the ticket status will not work
=> hotfix(condo): don't search removed resident

packages/keystone/KSv5v6/v5/prepareKeystone.js, packages/keystone/graphiql/graphiql.html, packages/keystone/graphiql/index.js, packages/keystone/package.json, yarn.lock
https://github.com/user-attachments/assets/7102f5e8-cb1f-4e8f-a25f-8c357d093382
=> feat(keystone): DOMA-10930 added "GraphiQL" instead of the outdated "graphql-playground"

apps/condo/domains/ticket/schema/Ticket.test.js, apps/condo/domains/ticket/utils/unit.js
In ticket has info about sectionName and floorName. 
This info taking from map in property. At the same time unitName and unitType taken from Resident App. Sync Map and Resident has is not correct. Bug is happening in moment, when have two identical unit by unitName (in map and in Resident), but different in unitType. Adding this check will allow don't make this bug. 
Bay the way, if unitName will not match in map and Resident - nothing will be displayed.
=> fix(condo): DOMA-10854 add check for unitType

apps/condo/domains/ticket/utils/serverSchema/TicketDocumentGeneration/completionWorks.js
Some users were unable to generate act of completion works, because getByCondition returned multiple objects. 
This happens because we do not skip deleted objects. 
These changes correct the incorrect behavior
=> hotfix(condo): DOMA-10973 add skip deletedAt

apps/condo/domains/property/components/BasePropertyForm/index.tsx
When creating Address Injections manually and then adding a house to this address, an error occurs: `Cannot read properties of undefined (reading 'address') ` when displaying success toast. To solve it, you can output the address property of the property object, otherwise address from the props.
=> fix(condo): fix cannot read property 'address' of undefined in success toast

apps/condo/domains/user/schema/User.js, apps/condo/domains/user/schema/User.test.js
query authenticatedUser for:
simple user:
support / admin user:
support / admin user in ui:
=> feat(user): DOMA-11002 show _label_ in old format for supports and admin

apps/condo/domains/ticket/components/BaseTicketForm/index.tsx
Bug:
If you keep the ticket page (which contains comments) open for one minute and then start editing it (even without changing it), then after saving the data the comments disappear.
Before update:
After update without fix:
Solution:
It's a cache issue. Apollo cache loses the TicketComment:xyz cache after a minute of going to the ticket editing page, but the link to the cache in KShChChE_YGUKN remains. And after returning to the ticket/[id] page, the data is taken from the cache (i.e. the request is not made, since there is a link to this cache), but there is nothing at this link. Therefore, if you add fetchPolicy: 'cache-and-network', the data will first be taken from the cache, and then the current data will be loaded in the background and the comments will appear. The fix should work …
=> fix(condo): DOMA-11007 clear ROOT_QUERY when page is update

apps/condo/domains/marketplace/components/Invoice/BaseInvoiceForm.tsx, apps/condo/domains/marketplace/schema/Invoice.test.js, apps/condo/domains/marketplace/schema/MarketItem.js, apps/condo/domains/marketplace/schema/MarketItemPrice.test.js, apps/condo/domains/resident/schema/RegisterResidentInvoiceService.js
This PR adds the following logic:
1. When mobile application creates an invoice using registerResidentInvoiceService
2. Make invoice.rows.*.measure equal to measure in MarketItem
This PR also fixes some UI inconsistencies in Invoice creation page
=> chore(condo): Fix marketplace measures logic

apps/condo/domains/ticket/utils/serverSchema/TicketDocumentGeneration/paidWorks.js
We can't download the paid work document now because there is no dayjs.extend(localizedFormat)
=> fix(condo): DOMA-11049 add dayjs.extend(localizedFormat) in paid works

apps/condo/domains/organization/integrations/sbbol/constants.js, apps/condo/domains/organization/integrations/sbbol/sync/index.js, apps/condo/domains/organization/integrations/sbbol/utils/getSbbolUserInfoErrors.spec.js
a combination of the "sub" (Subject) Claim and the "iss" (Issuer) Claim is always globally unique
we are using type sbbol instead of the iss, so we can use sub as a external user id
=> fix(spp): sbbol api now do not return userGuid

apps/condo/domains/ticket/tasks/sendTicketCommentCreatedNotifications.js, apps/condo/lang/en/en.json, apps/condo/lang/en/messages/TICKET_COMMENT_CREATED/default.njk, apps/condo/lang/es/es.json, apps/condo/lang/es/messages/TICKET_COMMENT_CREATED/default.njk, apps/condo/lang/ru/messages/TICKET_COMMENT_CREATED/default.njk, apps/condo/lang/ru/ru.json
We decided to display "(files attached)" message in notifications about ticket comment created. This means that the comment was created without content but with attached files (yes, through the API, we can create a comment without content or files, but we agreed on this solution).
Also updated the templates of TICKET_COMMENT_CREATED messages for cases when the notification data does not contain `authorName` (these are old comment created notifications).
=> fix(condo): DOMA-11188 display files attached message in ticket comment created notification

packages/apollo/src/utils/lists.ts
This fix should solve the problem of broken links in the cache
In some cases this caused a problem. For example, the story of comments disappearing after changing the page (not after updating):
If you are interested in how the bug is reproduced now:
https://github.com/user-attachments/assets/c2b650c4-40d4-4c11-98d9-e76c6b10fee3
=> fix(condo): DOMA-11038 add read func for cache

apps/condo/domains/billing/utils/serverSchema/index.js
And add env flag to disable this logic if something bad happens.
Problem with old query was that postgres decided to filter all Payments by sequence scan first, and only then use indexes and used 2 workers for this (usually it's just one worker).
I imitated production database Payments locally, with similar distribution of non nullable receipts, unique organizations, periods and accountNumbers. Also imitated case when all Payments will loose connection to receipt and tested query split and some indexes.
Looks like that easiest solution is to just split queries. In that case postgres uses indexes before sequence scan and works faster. 
Explain analyze of resulting sql on production gave me these results:
Organization with 800 payments - 16ms
Organization with 4.500 payments - 30ms …
=> fix(condo): DOMA-11246 split overcomplicated query for payments sum

apps/condo/domains/billing/schema/resolvers/accountResolver.spec.js, apps/condo/domains/billing/schema/resolvers/categoryResolver.js, apps/condo/domains/billing/schema/resolvers/utils.js
1. Billing category Warehouse will be deprecated as it is will be Housing for unitTypes warehouse, so as a first step it is removed from categoryResolver
2. ownerType detection do not works with not trimmed values, also COMPANY_TYPE regex uses flag global, so it leads to the bug
=> fix(DOMA-11255): fixed ownerType detection and removed warehouse category from category resolver

apps/condo/pages/initial.tsx
Because of this, the switching of the organizationLink cookie in the webview wasn't working
=> fix(condo): DOMA-11841 remove skipUserPrefetch from initial page
